### ISSUE TITLE
Cannot read property 'attemptedTs' of null

### ISSUE THREAD

**Issue by SkeLLLa** [dhowe/AdNauseam#963] opened 2017-03-28 05:54 UTC
Exceptions from extension's console :
```
Uncaught TypeError: Cannot read property 'attemptedTs' of null
var elapsed = (now - xhr.delegate.attemptedTs);
```

I'm not sure, but sometimes when this error appears adnausem seems hang some pages during loading.

**Comment by dhowe** [comment] 2017-03-28 06:34
Thanks for the report. Can you give us some more info so that we can try to recreate (AdNauseam, Browser, OS versions)? Also a line number if there is one in the console...

**Comment by SkeLLLa** [comment] 2017-03-28 07:27
@dhowe 
Here is the line: 
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L555

AdNauseam v3.3.32
Chrome: Version 59.0.3047.0 (Official Build) dev (64-bit)
OS: Linux & Windows

**Comment by dhowe** [comment] 2017-03-28 13:20
Any specific action that causes this message (have you exported/imported ads, etc?), or you just noticed this in the console?

**Comment by SkeLLLa** [comment] 2017-03-28 13:48
@dhowe, it appears from time mo time. I can only say that it happened during browsing. No unusual actions. There were some pages that eat 100% cpu, but when I've tried to reproduce, the error not appeared. So unfortunately there are no specific details. I just open collected errors of extension from time to time.

**Comment by dhowe** [comment] 2017-03-28 14:42
Ok, thanks @SkeLLLa  we'll check it out...

**Comment by SkeLLLa** [comment] 2017-03-28 16:37
@dhowe, I've managed to get this error once again. Here are some traces that I've managed to get:
`ad` object:
```
"{
  "id": 10393,
  "attempts": 1,
  "visitedTs": 0,
  "attemptedTs": 1490718647432,
  "contentData": {
    "src": "data:image/gif;base64,R0lGODlhBAGqAPAAAAAAAAAAACH5BAEAAAAALAAAAAAEAaoAAAL+h…CBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8YXjRw7evwIMqTIkSRLmjyJMqXKlSzxFQAAOw==",
    "width": 260,
    "height": 170
  },
  "contentType": "img",
  "title": "Pending",
  "foundTs": 1490718528193,
  "targetUrl": "http:",
  "pageTitle": "http://nv.ua/ukraine/events/v-napk-nazvali-otvetstvennyh-za-ustranenie-nepoladok-v-rabote-reestra-e-deklarirovanija-881272.html",
  "pageUrl": "http://nv.ua/ukraine/events/v-napk-nazvali-otvetstvennyh-za-ustranenie-nepoladok-v-rabote-reestra-e-deklarirovanija-881272.html",
  "current": true,
  "pageDomain": "nv.ua",
  "version": "3.3.32",
  "targetDomain": "",
  "targetHostname": "",
  "noVisit": false
}"
```

xhr object:
```
"{
  "delegate": null,
  "requestUrl": "http:"
}"
```

**Comment by dhowe** [comment] 2017-03-28 16:46
Very, thanks much.

**Comment by SkeLLLa** [comment] 2017-03-28 16:50
@dhowe if you tell me where should I look (in js files) probably I can try to locate it also. Unfortuantely stack trace has not a lot of info (only some `queueVisit` function calls or something like this)

**Comment by dhowe** [comment] 2017-03-28 16:57
If you enable debugging in the options, you should see more output in the addon console (opened by clicking background.html on the extensions page under AdNauseam):

![image](https://cloud.githubusercontent.com/assets/737638/24417368/b0a890a4-141a-11e7-8928-4a87957853e8.png)

**Comment by SkeLLLa** [comment] 2017-04-02 18:14
@dhowe, thanks, but actually it just puts a lot of stuff not related to a bug itself. For me it's just better to say to debugger to pause on uncaught exceptions and then collect dumps of variables.

**Comment by dhowe** [comment] 2017-04-02 18:22
that works too of course. would be great if you could share any findings, especially as both myself and  the other main dev (who I've assigned this ticket to) are traveling at moment, so it will likely be a few days before a resolution from our end

**Comment by SkeLLLa** [comment] 2017-04-02 18:29
@dhowe no problem. I've spotted this bug on few sites. It seems that it is caused by base64 encoded data in `contentData.src`. But it's just a guess. If I have some time, I'll look through the code in details to find out if it's true or not.

**Comment by cqx931** [comment] 2017-04-13 05:26
It seems to me that the xhr is failing on the very first stage `xhr.open('get', target, true);`, so no attribute is carried with it and we end up with an xhr object without delegate in onVisitError.
Maybe we should validate the targetUrl first before sending an xhr request?

**Comment by SkeLLLa** [comment] 2017-04-13 06:11
@cqx931 as far as I understood during debugging you're correct and the problem is in `targetUrl`. But I haven't found where is it formed. Checking validity of `targetUrl` is good idea, but I think it would be great to understand why it's malformed.

**Comment by cqx931** [comment] 2017-04-13 06:46
By observing the parser, this is caused by dynamically generated href attribute for a tag.
When AdNauseam catches the ad div, the element looks like below and the href attribute is "http:"
![screen shot 2017-04-13 at 2 28 12 pm](https://cloud.githubusercontent.com/assets/3056154/24992804/e5c47acc-2055-11e7-884e-864726c48ef6.png)
And this is how it looks like after the page fully loaded (with inspect element):
![image](https://cloud.githubusercontent.com/assets/3056154/24992825/fe74af1a-2055-11e7-8e77-fc766bacdca4.png)

To solve this, one way is to update the targetUrl if the a tag that got matched with an ad object has been dynamically changed. But I'm not sure whether this would slow down the page loading.
@dhowe What are your thoughts on this?

**Comment by dhowe** [comment] 2017-04-13 07:57
Lets invalidate ads without a valid URL (check for a minimum of 1 character letter or number not including http(s)+:// , and then check whether our DOM onChanged handled picks up the ad later... If not, we may need to update this function, but at least the problem in this ticket will have been addressed.

**Comment by cqx931** [comment] 2017-04-14 05:41
For [this case](http://nv.ua/ukraine/events/v-napk-nazvali-otvetstvennyh-za-ustranenie-nepoladok-v-rabote-reestra-e-deklarirovanija-881272.html), I don't see the same ad div got parsed again later, after ignoring the ads without a valid URL when it is first processed.
From my testing, I can't see any dom changed activity that changed the ad link of the image... and I'm not sure why.

**Comment by greysonevins** [comment] 2017-07-22 23:20
@dhowe this issue was the reason for the issue with #1099... It causes a pending because the ad is accepted with a problem url of "http://" when you normalize it in parser.js. I have fixed the issue with a regex. I'll commit in a moment.

**Comment by greysonevins** [comment] 2017-07-22 23:25
@SkeLLLa @dhowe @cqx931  my new commit should solve this issue.

**Closed** 2017-08-01 01:59 UTC
Labels: Bug
