### ISSUE TITLE
Ads are not getting blocked - Tweakers.net

### ISSUE THREAD

**Issue by Erfie** [dhowe/AdNauseam#1990] opened 2021-12-17 15:42 UTC
### Describe the issue
Ads on Tweakers.net aren't getting blocked with adnauseam but are with ublock origin.
I'm getting the same result with a new firefox profile.

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/5338222/146569427-435b2a84-f23f-4a54-bc67-68b2a1570e5c.png)
![image](https://user-images.githubusercontent.com/5338222/146569480-ca5db4b5-7277-4ee1-a884-1fcd025b26fa.png)
![image](https://user-images.githubusercontent.com/5338222/146569462-8c951119-8edb-4dd3-96d8-db6b98a3612b.png)

As you can it gets blocked by ublock origin.
![image](https://user-images.githubusercontent.com/5338222/146569881-66567fbd-71be-4338-acf2-e57b77893256.png)

### Your settings

- OS/version: Win 11
- Browser/version: Firefox 95.0.1
- AdNauseam version: 3.11.4
- Other extensions you have installed: None
- AdNauseam settings: All defaults except for I unticked "Don't hide non-tracking Ads"

##### Your filter lists
Default filter lists 

### Your location/country
Denmark

**Comment by mneunomne** [comment] 2021-12-18 20:31
THank you @Erfie for the feedback. Indeed this is happening on v3.11.4. Can you check if Tweakers.net is on "whitelist", this happened on my test and  I believe it's some kind of anti-block script that is going through.

This is not happening on Dev [v3.11.5] though

**Comment by Erfie** [comment] 2021-12-18 22:27
Just the defaults in the whitelist
![image](https://user-images.githubusercontent.com/5338222/146657058-13ec6ad7-37b2-4189-9c8d-2569a531497c.png)

**Comment by mneunomne** [comment] 2021-12-18 22:40
Interesting... I did see it pop up there, but couldn't reproduce it later... This is fixed in the version that we will relase soon, but i'll try to see a way to fix this through the filter list, so you dont have to wait for the next release :)

**Comment by mneunomne** [comment] 2022-01-10 14:02
This can be closed

**Closed by mneunomne** 2022-01-10 14:02 UTC
Labels: Ads Visible
