### ISSUE TITLE
Ads visible on sites

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#381] opened 2016-09-08 13:05 UTC
An ongoing ticket for ads visible in ADN but not in uBlock:

http://hongkong.asiaxpat.com/classifieds/dressers-wardrobes/ [cqx931]
http://documentaryheaven.com/find/?q=food    (note: text-ads)

**Comment by Pacific01** [comment] 2016-09-08 17:19
I have the same problem on some adult sites. I notice that all the ads that AND doesen't block are from exoclick. What can I do?

**Comment by dhowe** [comment] 2016-09-11 02:15
Please add specific URLs for sites with this problem here.

**Comment by cqx931** [comment] 2016-09-12 10:32
Fixed these two
http://hongkong.asiaxpat.com/classifieds/dressers-wardrobes
http://documentaryheaven.com/find/?q=food (note: text-ads)

**Comment by dhowe** [comment] 2016-09-12 16:06
good, closing for now -- will reopen when we have more URLs...

**Comment by dhowe** [comment] 2016-09-16 13:51
Next: http://www.columbiagreenemedia.com/chatham_courier/

**Comment by cqx931** [comment] 2016-09-19 07:30
http://www.columbiagreenemedia.com/chatham_courier/
fixed with https://github.com/dhowe/AdNauseam/pull/415

**Comment by cqx931** [comment] 2016-09-22 06:22
A checklist for main Chinese sites
- [ ] 163.com
- [ ] sohu.com
- [ ] sina.com
- [ ] qq.com
- [ ] zol.com.cn
- [ ] baidu.com

**Comment by cqx931** [comment] 2016-09-22 09:56
-Do you think a rule like ##iframe[src*=‘/ad/'] would be too broad to put into adnauseam.txt? It could save us a lot of time, but will there be some cases when it accidentally block non-ads? I'm not sure about this...

-Shall I put my update of the Chinese sites also to adnauseam.txt? Or do you prefer to have them separate as region specific?

**Comment by dhowe** [comment] 2016-09-22 10:05
I'm skeptical of this, but it might be worth some experimenting...
But yes, adding Chinese rules to adnauseam.txt is fine

**Comment by cqx931** [comment] 2016-09-22 12:52
Please check and I have added the rule: ##iframe[src*=‘/ad/']. If it doesn't work so well, it could be deleted later...
https://github.com/dhowe/AdNauseam/pull/434

**Comment by leoneckert** [comment] 2016-09-22 15:37
http://www.forbes.com/ (two "Sentry" ads in adn, but not in uBlock)

**Comment by leoneckert** [comment] 2016-09-22 15:39
http://www.pcmag.com/ (ad in background, and "Deals of the Day" panel)

**Comment by leoneckert** [comment] 2016-09-22 15:43
http://www.sfgate.com/ ("Today's deals" hidden in uBlock, not in Adn)

**Comment by dhowe** [comment] 2016-09-22 15:53
Good, next step, solve them...

**Comment by leoneckert** [comment] 2016-09-22 15:57
last one for now https://www.facebook.com/ uBlock gets rid of all 'posts' with the 'Sponsored' label

**Comment by leoneckert** [comment] 2016-09-25 00:30
can't figure out how to select the sponsored content on fb. The Divs seem to be identical to the other posts with the only exception of the innerHTML 'Sponsored' in a deeply nested a tag - can this be used as a identifier somehow?
<img width="533" alt="screen shot 2016-09-24 at 20 29 47" src="https://cloud.githubusercontent.com/assets/14130931/18812070/a9fbb266-8295-11e6-84ea-5ccad11bbd0e.png">

**Comment by leoneckert** [comment] 2016-09-25 00:30
- [ ] facebook.com

**Comment by dhowe** [comment] 2016-09-25 09:22
- [ ] http://www.creativebloq.com/graphic-design/gestalt-theory-10134960

**Comment by cqx931** [comment] 2016-09-26 04:16
The above one is solved... but I just found out that on their homepage, they have ad images in their body-background supported by google syndication. Since our current mechanism doesn't collect ads images in the background, shall we block this?
<img width="325" alt="screen shot 2016-09-26 at 12 12 41 pm" src="https://cloud.githubusercontent.com/assets/3056154/18822445/939a47d2-83e2-11e6-97e1-656a571c27da.png">

**Comment by dhowe** [comment] 2016-09-26 06:57
Sounds good

**Comment by dhowe** [comment] 2016-09-26 07:00
Have you and @leoneckert figured out the fb issue?

**Comment by leoneckert** [comment] 2016-09-26 15:06
I will get back to it tonight and try out the suggestions you made in #426

**Comment by leoneckert** [comment] 2016-10-04 23:50
http://www.cnn.com
http://www.foxnews.com
http://www.wsj.com
http://time.com

**Comment by dhowe** [comment] 2016-10-05 04:13
Note: this is always higher priority than #356

**Comment by leoneckert** [comment] 2016-10-19 21:32
[ ] - http://www.usatoday.com

**Comment by dhowe** [comment] 2016-10-20 01:27
oh yeah

**Comment by dhowe** [comment] 2016-10-21 05:13
@cqx931 or @leoneckert please take a look at this

**Comment by cqx931** [comment] 2016-10-21 07:55
just fixed this one: http://www.usatoday.com/ 
please check https://github.com/dhowe/uAssets/pull/7/commits/c960500b693f22d6ad1461b24d5b89bb430b9599

@leoneckert 
For the right one I used this to block the ad: usatoday.com##DIV#module-position-8
since all the content inside are dynamically generated, and it seems like ublock is having trouble to detect the dom changes when there are several layers of iframes, this is the only selector that exist already without any single ad generated(you can try open the page with uBlock and inspect element). The collecting issue of this ad shall be related to this ticket, https://github.com/dhowe/AdNauseam/issues/523

**Comment by leoneckert** [comment] 2016-10-21 22:34
the ad was still showing for me, but adding the additional line applying to a section tag rather than a div, it solved it for me. made pr on uAsstets
<img width="293" alt="screen shot 2016-10-21 at 18 25 25" src="https://cloud.githubusercontent.com/assets/14130931/19613787/e526b872-97bc-11e6-8855-da5b60a6197b.png">
<img width="438" alt="screen shot 2016-10-21 at 18 30 30" src="https://cloud.githubusercontent.com/assets/14130931/19613789/e76aea04-97bc-11e6-8835-bfd2b4a022a9.png">

**Comment by dhowe** [comment] 2016-10-22 06:31
👍

**Comment by leoneckert** [comment] 2016-11-02 23:08
having a tough time with fulscreen popup ad (after clearing cookies) on http://www.pcmag.com/ , do you get it, too? 
<img width="659" alt="screen shot 2016-11-02 at 19 04 15" src="https://cloud.githubusercontent.com/assets/14130931/19950647/2ff486a6-a12f-11e6-9f95-faca2bcca30b.png">

I can hide it, but the problem is that a script seems to disable any scrolling in the beginning for the duration of the ad. Then when hiding the ad, this stays disabled. There are a few suspect scripts that are not blocked, but whatever I tried (different blocking rules, and with all other lists disabled), I did not get to block them to see if that helps. 
Any ideas? 

<img width="378" alt="screen shot 2016-11-02 at 18 19 38" src="https://cloud.githubusercontent.com/assets/14130931/19950568/abfddd34-a12e-11e6-8091-a863d6a5af2d.png">

**Comment by dhowe** [comment] 2016-11-03 07:45
I don't see that one -- though I do see a big blank space at top of page:

![screen shot 2016-11-03 at 3 44 10 pm](https://cloud.githubusercontent.com/assets/737638/19958724/72c600ec-a1dc-11e6-8bb2-73c73539e7ba.png)

**Comment by dhowe** [comment] 2016-11-03 07:47
It could be a location-based ad (not serving in HK for example), but also make sure that you have erased cookies and are not logged into any services...

**Comment by leoneckert** [comment] 2016-11-04 23:36
the overlay ad  and overflow:hidden script I found are fixed in last PR. hopefully also the white box you saw (it's fixed for me, too)

**Comment by dhowe** [comment] 2016-11-18 22:42
Visible on ADN, not on uB:

![screen shot 2016-11-19 at 6 40 13 am](https://cloud.githubusercontent.com/assets/737638/20449274/48caf114-ae23-11e6-8853-7218c109e1e9.png)

**Comment by leoneckert** [comment] 2016-11-18 23:09
PR hides batmanstream.com ad. 

However I am a little confused right now, the iframe and visual banner is hidden (GREEN in screenshot), but the requests to scripts outside of it (RED are still made....should that be? I might be mixing things up here..

![batman](https://cloud.githubusercontent.com/assets/14130931/20449854/f3b8250c-adb9-11e6-8687-aefb7f00775c.jpg)

**Comment by dhowe** [comment] 2016-11-18 23:27
My guess is that the script generates the ad, thus the script-request must be made for the ad to be received and then collected/hidden, but I would have to verify this...

**Comment by dhowe** [comment] 2016-11-22 21:42
Ad visible here: http://hyperallergic.com/339315/mississippi-governor-decries-billboard-by-artist-led-super-pac/, hidden on uBlock:

![screen shot 2016-11-23 at 5 40 14 am](https://cloud.githubusercontent.com/assets/737638/20543085/9798fbc8-b13f-11e6-96a6-ccd75a8e6519.png)

**Comment by leoneckert** [comment] 2016-12-01 19:07
I re-submit the batmantennis.com filter because I forgot to update the checksum. The ad on hyperallergic.com does not show up for me. Today I'll go over some popular sites again checking for visible ads.

**Comment by dhowe** [comment] 2016-12-13 10:06
Another (video, no less): http://www.pcworld.com/article/3149055/windows/popular-ublock-origin-ad-blocker-appears-in-edges-walled-extension-garden.html

**Comment by leoneckert** [comment] 2016-12-14 21:13
don't see a/this video ad on there, but a different one. Will get rid of this:
<img width="757" alt="screen shot 2016-12-14 at 16 12 18" src="https://cloud.githubusercontent.com/assets/14130931/21201245/3361d7b2-c218-11e6-876b-b143237bc44d.png">

**Comment by leoneckert** [comment] 2016-12-14 22:21
fixed above ad I posted as well as some left over "You Might Like" and "Shop Tech Product At Amazon" headlines the ads below which were already hidden in the first place. 

I was weirdly unsure whether to consider this below an ad, is it? 

<img width="1072" alt="screen shot 2016-12-14 at 16 57 53" src="https://cloud.githubusercontent.com/assets/14130931/21202936/82356bdc-c21e-11e6-94ea-17eb052896c5.png">

**Comment by dhowe** [comment] 2016-12-15 03:19
Treat it as uBlock does...

**Comment by dhowe** [comment] 2016-12-19 15:18
New one (anti-adblock): http://adage.com/article/digital/virtual-reality-advertising-s-big-thing/294328/

![screen shot 2016-12-19 at 11 13 03 pm](https://cloud.githubusercontent.com/assets/737638/21317747/684dd03e-c641-11e6-8441-2ca0ad352c09.png)

**Comment by cqx931** [comment] 2016-12-22 01:59
fixed https://github.com/dhowe/uAssets/pull/18

**Closed** 2018-07-12 07:50 UTC
Labels: Bug, Ongoing, PRIORITY: High
