### ISSUE TITLE
youtube.com not loading all images for videos when enabling uBlock filters – Annoyances

### ISSUE THREAD

**Issue by romulasry** [dhowe/AdNauseam#2264] opened 2023-01-27 18:50 UTC
### Describe the issue

Youtube does not load images on all pages when enabling the ublock annoyances adblock filter.

### Screenshot in which the issue can be seen
![Screenshot from 2023-01-26 22-46-28](https://user-images.githubusercontent.com/19944656/215169562-63635dc8-1d0d-482d-bfd2-08a4515f8d84.png)

### Steps for anyone to reproduce the issue
Go to youtube.com
Load page
Video images don't always load.

### Your settings

- OS/version: Linux Fedora Rawhide
- Browser/version: Firefox 109.0
- AdNauseam version: 3.16.0
- Other extensions you have installed: Dark Reader
- AdNauseam settings: Default + uBlock filters – Annoyances

##### Your filter lists
Default + uBlock filters – Annoyances

### Your location/country
USA, Southern California

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1405969086

**Comment by mneunomne** [comment] 2023-01-27 19:55
Couldn't reproduce with these settings, could you provide a screenshot? Or perhaps some error logs if there are any in the console.

**Comment by romulasry** [comment] 2023-01-27 20:02
https://user-images.githubusercontent.com/19944656/215169562-63635dc8-1d0d-482d-bfd2-08a4515f8d84.png

**Comment by romulasry** [comment] 2023-01-27 22:28
![Screenshot from 2023-01-27 14-28-27](https://user-images.githubusercontent.com/19944656/215218338-5dcf54e7-e08f-4a75-90dc-0d83fa84d674.png)

**Comment by romulasry** [comment] 2023-02-11 04:29
Here is the code:

!#if env_firefox
youtube.com##.no-scroll #page-manager:style(margin-top: 0px !important)
!#endif
! https://github.com/uBlockOrigin/uAssets/issues/5911
youtube.com##ytd-popup-container > .ytd-popup-container > #contentWrapper > .ytd-popup-container[position-type="OPEN_POPUP_POSITION_BOTTOMLEFT"]
m.youtube.com###mealbar\:3 > ytm-mealbar.mealbar-promo-renderer

moz-extension://a39a8807-b017-4211-b5f1-7fdaa225fa7d/asset-viewer.html?url=ublock-annoyances

**Comment by romulasry** [comment] 2023-02-12 03:12
It is thinking some of the youtube video images are ads. See below:

![Screenshot from 2023-02-11 18-32-38](https://user-images.githubusercontent.com/19944656/218290832-c612ef12-e444-4384-aeac-ece087cc03f5.png)

**Comment by romulasry** [comment] 2023-02-13 03:39
https://github.com/dhowe/AdNauseam/issues/2269

**Comment by mneunomne** [comment] 2023-02-17 14:43
Currently fixed on master, closing

**Closed by mneunomne** 2023-02-17 14:43 UTC
Labels: Cannot Reproduce
