### ISSUE TITLE
Warning and three errors in Google Chrome 102.0.5005.63 64 bit for version AdNauseam 3.12.2

### ISSUE THREAD

**Issue by AlexFish2013** [dhowe/AdNauseam#2107] opened 2022-06-05 14:26 UTC
### Screenshot in which the issue can be seen
1. https://i.imgur.com/UhtEIW3.png - warning.
2. https://i.imgur.com/rwIKK3X.png - error 1.
Translate text on screenshot 2:
Context
menu.html
Stack tracing
js/udom.js:567 (anonymous functions)
3. https://i.imgur.com/pywyEja.png - error 2.
Translate text on screenshot 3:
Context
background.html
Stack trace
js/messaging.js:187 (Object.onMessage [as defaultHandler])
js/vapi-background.js:1064 (Object.onPortMessage)
js/vapi-background.js:845 (anonymous functions)
4. https://i.imgur.com/M3tDzpH.png - error 3.
Translate text on screenshot 4:
Context
background.html
Stack trace.
No alerts.

### Steps for anyone to reproduce the issue
Standard plugin installation in google chrome, for example: https://i.imgur.com/jzz0uBN.png

### Your settings
- OS/version: Windows 10 EE 21H2 x64 Rus 19044.1741
- Browser/version: Google Chrome 102.0.5005.63 64 bit
- AdNauseam version: 3.12.2 (adnauseam.chromium.zip, manual installed)
- Other extensions you have installed: No dependencies!
- AdNauseam settings: All checkboxes are checked except javascript.

**Comment by mneunomne** [comment] 2022-06-06 20:54
@AlexFish2013 thank you for the feedback. Could you perhaps check if the same error occurs in the lastest version [3.13.1](https://github.com/dhowe/AdNauseam/releases/tag/v3.13.1) ?

**Comment by AlexFish2013** [comment] 2022-06-07 19:50
Hi, Dudes! )

The last release refused to work at all after installation (3.13.1).
I installed it the known way in developer mode manually.
There were some errors and warnings there, too.

After activating the plugin on the page, nothing happens, ad banners are
not cut.
So I rolled back to the previous stable release (3.12.2).

I can install the latest 3.13.1 release and record all errors and
warnings. It will be a little later.

WBR, Alex Fish





пн, 6 июн. 2022 г. в 23:54, Alberto Harres ***@***.***>:

**Comment by AlexFish2013** [comment] 2022-06-07 20:10
Hi, there!

About version 3.13.1 - all ads remain on the page after the plugin is
activated.
I conclude that it does not work at all.

1. Warning - https://i.imgur.com/DsUkDDl.png
2. Error - https://i.imgur.com/oVN2iux.png
Error text:
Error in event handler: TypeError: Error in invocation of
webRequestInternal.eventHandled(string eventName,
string subEventName, string requestId, integer webViewInstanceId, optional
webRequest.
BlockingResponse response): Error at parameter 'response': Error at
property 'responseHeaders': Invalid type: expected webRequest.HttpHeaders,
found object.

Translate
Context
background.html
Stack trace.
No alerts.

I hope I did what you asked.

I'm rolling back to version 3.12.2 again.
At least it removes the ad banners, although it does give warnings and
errors.

WBR, Alex Fish


вт, 7 июн. 2022 г. в 22:50, Alex Fish ***@***.***>:

**Comment by mneunomne** [comment] 2022-06-07 20:50
That is indeed strange. Could you perhaps try to repeat this on a clean chrome Profile? I couldn't reproduce these errors that you are mentioning on v3.13.1.

**Comment by AlexFish2013** [comment] 2022-06-09 12:27
Hi, again.

Well, I installed the latest 3.13.1 release on a blank profile using the
portable version of the browser.
Details below...

*Screenshots made with ShareX 13.7!*

*Before!*
*https://i.imgur.com/qsJmCE5.png <https://i.imgur.com/qsJmCE5.png> - this
is Google Chrome 102.0.5005.63 (official) 64-bit Portable from
https://portableapps.com/apps/internet/google-chrome-portable-64
<https://portableapps.com/apps/internet/google-chrome-portable-64>*
*Ignore the error, the portable browser cannot update in principle!*

Empty profile: https://i.imgur.com/AaU4tlm.png

Next install 3.13.1

*After!*
AdNauseam v3.13.1 uBlock Origin v1.40.4

*Settings: AdNauseam_Settings_Export_09.06.2022.14.49.31.json  ->  file
attached !*

*Warning - https://i.imgur.com/xnYTDiN.png
<https://i.imgur.com/xnYTDiN.png>*
Manifest version 2 is deprecated, and support will be removed in 2023. See
https://developer.chrome.com/blog/mv2-transition/ for more details.
{
  "author": "Daniel C. Howe",
  "background": {
    "page": "background.html",
    "persistent": true
  },
  "browser_action": {
    "default_icon": {
      "16": "img/icon_16.png",
      "32": "img/icon-32.png"
    },
    "default_popup": "menu.html",
    "default_title": "AdNauseam"
  },
  "commands": {
    "launch-element-picker": {
      "description": "__MSG_popupTipPicker__"
    },
    "launch-element-zapper": {
      "description": "__MSG_popupTipZapper__"
    },
    "launch-logger": {
      "description": "__MSG_popupTipLog__"
    },
    "relax-blocking-mode": {
      "description": "__MSG_relaxBlockingMode__"
    }
  },
  "content_scripts": [
    {
      "all_frames": true,
      "js": [
        "js/vapi.js",
        "js/vapi-client.js",
        "js/adn/textads.js",
        "js/adn/parser.js",
        "js/contentscript.js"
      ],
      "match_about_blank": true,
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "run_at": "document_start"
    },
    {
      "all_frames": false,
      "js": [
        "js/scriptlets/subscriber.js"
      ],
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "run_at": "document_idle"
    }
  ],
  "content_security_policy": "script-src 'self'; object-src 'self'",
  "default_locale": "en",
  "description": "__MSG_extShortDesc__",
  "icons": {
    "128": "img/icon_128.png",
    "16": "img/icon_16.png"
  },
  "incognito": "spanning",
  "manifest_version": 2,
  "minimum_chrome_version": "51.0",
  "name": "AdNauseam",
  "options_ui": {
    "open_in_tab": true,
    "page": "options.html"

*Error 1 - https://i.imgur.com/26tsxOu.png
<https://i.imgur.com/26tsxOu.png>*
Text and translate:
Error in event handler: TypeError: Cannot read properties of undefined
(reading 'forceUpdate')
Context
background.html
Stack trace
js/messaging.js:183 (Object.onMessage [as defaultHandler])
js/vapi-background.js:1070 (Object.onPortMessage)
js/vapi-background.js:851 (anonymous functions)
/*******************************************************************************

    uBlock Origin - a browser extension to block requests.
    Copyright (C) 2014-present Raymond Hill

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see {http://www.gnu.org/licenses/}.

    Home: https://github.com/gorhill/uBlock
*/

'use strict';

/******************************************************************************/

import publicSuffixList from '../lib/publicsuffixlist/publicsuffixlist.js';
import punycode from '../lib/punycode.js';

import cacheStorage from './cachestorage.js';
import cosmeticFilteringEngine from './cosmetic-filtering.js';
import htmlFilteringEngine from './html-filtering.js';
import logger from './logger.js';
import lz4Codec from './lz4.js';
import io from './assets.js';
import scriptletFilteringEngine from './scriptlet-filtering.js';
import staticExtFilteringEngine from './static-ext-filtering.js';
import staticFilteringReverseLookup from './reverselookup.js';
import staticNetFilteringEngine from './static-net-filtering.js';
import µb from './background.js';
import webRequest from './traffic.js';
import { denseBase64 } from './base64-custom.js';
import { redirectEngine } from './redirect-engine.js';
import { StaticFilteringParser } from './static-filtering-parser.js';

import {
    permanentFirewall,
    sessionFirewall,
    permanentSwitches,
    sessionSwitches,
    permanentURLFiltering,
    sessionURLFiltering,
} from './filtering-engines.js';

import {
    domainFromHostname,
    domainFromURI,
    entityFromDomain,
    hostnameFromURI,
    isNetworkURI,
} from './uri-utils.js';

import './benchmarks.js';

import adnauseam from './adn/core.js';
import dnt from './adn/dnt.js'

/******************************************************************************/

// https://github.com/uBlockOrigin/uBlock-issues/issues/710
//   Listeners have a name and a "privileged" status.
//   The nameless default handler is always deemed "privileged".
//   Messages from privileged ports must never relayed to listeners
//   which are not privileged.

/******************************************************************************/
/******************************************************************************/

{
// >>>>> start of local scope

const clickToLoad = function(request, sender) {
    const { tabId, frameId } = sender;
    if ( tabId === undefined || frameId === undefined ) { return false; }
    const pageStore = µb.pageStoreFromTabId(tabId);
    if ( pageStore === null ) { return false; }
    pageStore.clickToLoad(frameId, request.frameURL);
    return true;
};

const getDomainNames = function(targets) {
    return targets.map(target => {
        if ( typeof target !== 'string' ) { return ''; }
        return target.indexOf('/') !== -1
            ? domainFromURI(target) || ''
            : domainFromHostname(target) || target;
    });
};

const onMessage = function(request, sender, callback) {
    // Async
    switch ( request.what ) {
    case 'getAssetContent':
        // https://github.com/chrisaljoudi/uBlock/issues/417
        io.get(request.url, {
            dontCache: true,
            needSourceURL: true,
        }).then(result => {
            callback(result);
        });
        return;

    case 'listsFromNetFilter':
        staticFilteringReverseLookup.fromNetFilter(
            request.rawFilter
        ).then(response => {
            callback(response);
        });
        return;

    case 'listsFromCosmeticFilter':
        staticFilteringReverseLookup.fromCosmeticFilter(
            request
        ).then(response => {
            callback(response);
        });
        return;

    case 'reloadAllFilters':
        µb.loadFilterLists().then(( ) => { callback(); });
        return;

    case 'scriptlet':
        vAPI.tabs.executeScript(request.tabId, {
            file: `/js/scriptlets/${request.scriptlet}.js`
        }).then(result => {
            callback(result);
        });
        return;

    case 'snfeBenchmark':
        µb.benchmarkStaticNetFiltering({ redirectEngine }).then(result => {
            callback(result);
        });
        return;

    default:
        break;
    }

    // Sync
    let response;

    switch ( request.what ) {
    case 'applyFilterListSelection':
        response = µb.applyFilterListSelection(request);
        break;

    case 'clickToLoad':
        response = clickToLoad(request, sender);
        break;

    case 'createUserFilter':
        µb.createUserFilters(request);
        break;

    /*case 'domainIsDNT':
        response = dnt.isDoNotTrackRule(request.rule);
        break;*/

    case 'isDNTVisible':
        response = µb.userSettings.dntDomains.indexOf(request.domain) > -1
           && µb.userSettings.disableHidingForDNT;
        break;

    case 'forceUpdateAssets':
        µb.scheduleAssetUpdater(0);
        io.updateStart({
            delay: µb.hiddenSettings.manualUpdateAssetFetchPeriod
        });
        break;

    case 'forceUpdateAdnauseam':
        µb.assets.forceUpdate("Adnauseam");
        break;

    case 'forceUpdateEff':
        µb.assets.forceUpdate("Eff");

*Error 2 - https://i.imgur.com/rYKLWGQ.png
<https://i.imgur.com/rYKLWGQ.png>*
Text and translate:
Uncaught TypeError: Cannot read properties of undefined (reading
'domFilterer')
Context
https://cryptomininggame.com/
Stack trace
js/contentscript.js:1280 (anonymous functions)

Well, this error is site-specific, but it exists! о_О

*Error 3 - https://i.imgur.com/OQyWOrn.png
<https://i.imgur.com/OQyWOrn.png>*
Text and translate:
Error in event handler: TypeError: Error in invocation of
webRequestInternal.eventHandled(string eventName, string subEventName,
string requestId, integer webViewInstanceId,
optional webRequest.BlockingResponse response): Error at parameter
'response': Error at property 'responseHeaders': Invalid type: expected
webRequest.HttpHeaders, found object.
Context
background.html
Stack trace.
No alerts.

Ugh-Ugh... )))
I hope this helps you get to the bottom of this!

WBR, Alex Fish

вт, 7 июн. 2022 г. в 23:50, Alberto Harres ***@***.***>:

**Comment by mneunomne** [comment] 2023-02-21 01:07
This issue seems to be outdated now. I can't detect the bug report above in relation to the current version. Closing for now.

**Closed by mneunomne** 2023-02-21 01:07 UTC
