### ISSUE TITLE
Google ads visible on spiegel

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1491] opened 2019-05-14 19:37 UTC
All articles, an example:

https://www.spiegel.de/international/germany/german-failure-on-the-road-to-a-renewable-future-a-1266586.html

![image](https://user-images.githubusercontent.com/737638/57726884-1f8f5000-765e-11e9-8b0d-9850cd10042c.png)

**Comment by cqx931** [comment] 2019-05-15 18:32
Could we think out a better strategy to deal with "generichide"? 
As more and more sites are trying to detect adblockers, it's not very effective to write hiding rules one by one to all of these sites. Something like adding basic generic hiding rules to that specific domain if a generichide filter is detected?

For spiegel.de for example, we need a site specific google ads rule such as`spiegel.de##[id^="google_ads_iframe_"]` to hide most of the google ads. 

Similar cases we have solved in the past:
https://github.com/dhowe/AdNauseam/issues/1476
https://github.com/dhowe/AdNauseam/issues/1480

**Comment by metapea** [comment] 2019-05-22 03:18
also so with the basic filters (version 3.8.101) in places like chan.sankakucomplex.com (nsfw) and booru.org (with ads2.contentabc.com poping up now) being unblocked, and are now showing ads unlike the last version were everything was fine in those sites.

**Comment by cqx931** [comment] 2019-05-25 15:13
@metapea could you please create separate tickets for the issues you mentioned above? Please also try to fill in as much as possible in the ticket template(especially the url and the browser you are using), so that it will be easier for us to reproduce the issue.
I have tried the three sites you mentioned on chrome with version 3.8.101 and I can't reproduce the ads. 
Thanks!

**Comment by dhowe** [comment] 2021-02-16 15:51
Also cannot reproduce on Spiegel. Please check the others mentioned:

- [ ] cultistsimulator.gamepedia.com
- [ ] chan.sankakucomplex.com (nsfw)
- [ ] booru.org (with ads2.contentabc.com poping up now)

**Comment by metapea** [comment] 2021-02-22 23:06
cultistsimulator.gamepedia.com seems to be fine now
chan.sankakucomplex.com & booru.org, i'm not sure with the default filters since i'm already used block element and other filters 

gelbooru & others sites does a problem with ''exo_wrapper" which is a semi-popup ad and you can't use block element to remove it. the latest version uBlock does block it at least.

**Comment by dhowe** [comment] 2021-02-23 04:18
> i'm not sure with the default filters since i'm already using block element and custom filters
we need to use the default filters for testing -- I suggest keeping a separate FF and/or Chrome profile for this

>gelbooru & others sites does a problem with ''exo_wrapper" which is a semi-popup ad and you can't use block element to remove it. The latest version of uBlock does block it at least.
what rules fires in ublock to block these?

**Comment by metapea** [comment] 2021-02-24 02:55
> what rules fires in ublock to block these?

What i mean is, uBlock blocks it by the default filters unlike nauseam. I haven't been looking into it, just something i notice when i used the latest version of uBlock.

> we need to use the default filters for testing

Alright i already know, just letting you know about the block element and custom filters since it's has been close to 2 years when i posted that

**Comment by dhowe** [comment] 2021-02-24 06:18
thanks @metapea!

**Comment by mneunomne** [comment] 2023-04-19 10:15
Seems like this issue is now outdated, ads are being correctly hidden on Spiegel. Closing for now.

**Closed by mneunomne** 2023-04-19 10:15 UTC
Labels: Needs-test-case, Needs-verification, PRIORITY: Medium, Ads Visible
