### ISSUE TITLE
Ad hiding/parsing fails after running for a few minutes [Firefox/Opera]

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#793] opened 2017-01-22 17:25 UTC
Found in  merges of [1.9.16] and [1.10.0]

This strange performance is not totally gone... I'm not sure whether this could also happen to other platforms, but for this time, I am sure that it is happening for [1.9.16] and on firefox.

blocking seems to work fine. I can see some error messages but none of them is from file in adnauseam.
![image](https://cloud.githubusercontent.com/assets/3056154/22184439/7ae31958-e10c-11e6-9fbc-b6d8f2406b09.png)

![image](https://cloud.githubusercontent.com/assets/3056154/22188028/6fc5bac8-e14b-11e6-8b68-86de54dd1a9b.png)

**Comment by dhowe** [comment] 2017-01-23 02:35
Can you compare this to master?

**Comment by cqx931** [comment] 2017-01-23 02:53
let me check.

**Comment by cqx931** [comment] 2017-01-23 03:59
So far I still can't reproduce it on master branch again...

**Comment by dhowe** [comment] 2017-01-23 06:00
but you can reproduce it on merged-1.9.16 ?

**Comment by cqx931** [comment] 2017-01-23 06:06
I can't really reproduce this issue constantly because I don't know what exactly triggers this, but it did happened once with master branch on opera, once with merged-1.9.16 on opera. And as it happens twice, I do think there is something wrong going on... It shouldn't happen on chrome, as I use it constantly and I never see that happening.

**Comment by dhowe** [comment] 2017-01-23 06:11
and on firefox?

**Comment by cqx931** [comment] 2017-01-23 06:12
Sorry, typo, "once with merged-1.9.16 on firefox"

**Comment by cqx931** [comment] 2017-01-24 07:50
Just had another case when testing in Opera.
This time it is even more confusing.
When I try to test textad on google, the ad parsing and hiding stops to work.
I went to check nytimes.com and the ad parsing and hiding are also not working there.
After checking another few more sites I am back to nytimes, and retried, the parsing and hiding suddenly worked again.
I checked another few websites(both image and text ads), they all worked except google search.
During the whole process, no error message in the console. blocking messages look fine in background, nothing from the parser is logged.

If I delete adnauseam and reload again, text ads from google could be parsed again. Simply reloading the extension doesn't help with this issue.

**Comment by dhowe** [comment] 2017-01-24 10:24
quite strange... we've only seen this on opera and firefox?

**Comment by cqx931** [comment] 2017-01-24 11:11
yes, so far only on opera and firefox

**Comment by dhowe** [comment] 2017-01-24 12:36
Have you checked auto-update on 1.10.0?

**Comment by cqx931** [comment] 2017-02-07 06:32
After adding auto update testing, it is confirmed that this issue is not related to auto update.

However, this time it happens once in chrome as well. 
In Opera and Chrome, if I refresh the console of background.html, everything works again.
In Firefox, as there is no background.html and you can only delete the previous console message instead of refreshing, I didn't figure out a way to get adnauseam work again from this strange status.

**Comment by dhowe** [comment] 2017-02-07 08:28
This happened during testing on which platforms?

**Comment by dhowe** [comment] 2017-02-07 12:29
We need to isolate the cause of this one...

**Comment by cqx931** [comment] 2017-02-07 14:08
Create a new ticket for this issue: https://github.com/dhowe/AdNauseam/issues/850

**Closed** 2017-02-08 08:41 UTC
Labels: Firefox, Opera, PRIORITY: High
