### ISSUE TITLE
Some picture tweets on Twitter are blocked when AdNauseam is on

### ISSUE THREAD

**Issue by Retia-Adolf** [dhowe/AdNauseam#2341] opened 2023-06-20 18:37 UTC
### Describe the issue

*NOTE: if you are having a problem where ads are not collected, please FIRST TRY to create a new new Firefox profile as described [here](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile). A corrupt Firefox profile is the most common cause of this issue.*

### Screenshot in which the issue can be seen

![Screenshot 2023-06-20 at 17-42-04 Aesthetica on Twitter](https://github.com/dhowe/AdNauseam/assets/34053927/9eadff1f-6d00-46e5-b635-ac70c7de5a18)

Also I can't see any relevant blocked request in the logger.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

Example URL: https://twitter.com/Anc_Aesthetics/status/1670948335442698240

### Your settings

- OS/version: Ubuntu 22.04.2 LTS
- Browser/version: Mercury Nightly 110.0a1 (2023-01-09) (64-bit)
- AdNauseam version: 3.16.2b0
- Other extensions you have installed: Many. But If I disable AdNauseam or temporarily unblock the site, the problem would be gone.
- AdNauseam settings: 
- ```
   "userSettings": {
    "dntDomains": [],
    "firstInstall": false,
    "hidingAds": true,
    "clickingAds": true,
    "blockingMalware": true,
    "disableHidingForDNT": true,
    "disableClickingForDNT": true,
    "hiddenSettings": {
      "userResourcesLocation": "https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt"
    }

##### Your filter lists

```
My filters
Essentials (9/9)
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
  AdNauseam filters
  EasyList
  uBlock filters
  uBlock filters – Badware risks
  uBlock filters – Privacy
  uBlock filters – Quick fixes
  uBlock filters – Resource abuse
  uBlock filters – Unbreak
Privacy (4/4)
  AdGuard Tracking Protection
  AdGuard URL Tracking Protection
  Block Outsider Intrusion into LAN
  EasyPrivacy
Malware (3/3)
  Online Malicious URL Blocklist
  Phishing URL Blocklist
  PUP Domains Blocklist
Annoyances (5/7)
  AdGuard Annoyances
  Anti-Facebook
  EasyList Cookie
  Fanboy’s Annoyance
  uBlock filters – Annoyances
Other
  AdGuard Base
  AdGuard Mobile Ads
  Dan Pollock’s hosts file
  Fanboy+Easylist-Merged Ultimate List
Languages (17/34)
  BGR: Bulgarian Adblock list
  CHN: AdGuard Chinese (中文)
  DEU: EasyList Germany
  FIN: Adblock List for Finland
  FRA: AdGuard Français
  GRC: Greek AdBlock Filter
  ISL: Icelandic ABP List
  ISR: EasyList Hebrew
  ITA: EasyList Italy
  JPN: AdGuard Japanese
  NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
  POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
  ROU: Romanian Ad (ROad) Block List Light
  RUS: RU AdList
  spa, por: AdGuard Spanish/Portuguese
  spa: EasyList Spanish
  TUR: AdGuard Turkish
Custom (10/13)
    "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt",
    "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt",
    "https://easylist-downloads.adblockplus.org/easylistchina.txt",
    "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt",
    "https://www.fanboy.co.nz/enhancedstats.txt",
    "https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt",
    "https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt",
    "https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt",
    "https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt",
    "https://filters.adtidy.org/extension/ublock/filters/220.txt"
```

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment] 2023-07-02 10:02
Can't reproduce with the normal filter lists. My guess this problem is being caused by the combination of one of the many custom filters + other + languages. It's a bit hard for me to test them all and see what exactly is causing it. Maybe first test if with default settings the same issue is happening?

**Comment by mneunomne** [comment] 2023-10-06 13:28
Can't reproduce, no updates, closing.

**Closed by mneunomne** 2023-10-06 13:28 UTC
Labels: Needs-verification
