### ISSUE TITLE
bitsearch.to

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2265] opened 2023-01-28 10:29 UTC
### Describe the issue

ad on https://bitsearch.to/

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/76880977/215261750-e36f00dd-ac57-404e-848d-4944a79ee087.png)

### Steps for anyone to reproduce the issue
1. go to site
2. see ad

### Your settings

- OS/version:

Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎05-‎07-‎2022
OS build	22000.1219
Experience	Windows Feature Experience Pack 1000.22000.1219.0

- Browser/version: 
![image](https://user-images.githubusercontent.com/76880977/215261644-7bc2a962-2431-4a80-a741-1a44178d5b8c.png)

- AdNauseam version: 
![image](https://user-images.githubusercontent.com/76880977/215261634-a76f1799-dba9-4cdd-8985-d31ef7b6d5f2.png)

- Other extensions you have installed: no
- AdNauseam settings: default

##### Your filter lists
 "Default filter lists"

### Your location/country
India

**Comment by mneunomne** [comment] 2023-02-10 14:05
For some reason this ad is visible on 3.16.0 but not on current dev  3.16.1b1. Need to check why. But in theory this should be fixed as soon as I make the release.

**Comment by chirag127** [comment] 2023-02-10 14:10
> For some reason this ad is visible on 3.16.0 but not on current dev 3.16.1b1. Need to check why. But in theory this should be fixed as soon as I make the release.

I had mentioned the version. So, bad you didn't try that (I'm just joking)

**Comment by mneunomne** [comment] 2023-02-10 14:17
> I had mentioned the version. So, bad you didn't try that (I'm just joking)

I tried both, therefore my comment.

**Comment by chirag127** [comment] 2023-02-10 14:19
> > I had mentioned the version. So, bad you didn't try that (I'm just joking)
> 
> I tried both, therefore my comment.

Oh, i confused with my previous issue.

**Comment by mneunomne** [comment] 2023-02-15 12:51
Added a specific filter https://github.com/dhowe/AdNauseam/commit/67a9ea600e8c8395f32cc60ce668406acc5ba054

Since I was now also able to reproduce it on current dev as well.

**Comment by mneunomne** [comment] 2023-02-21 00:57
Fixed, closing.

**Closed by mneunomne** 2023-02-21 00:57 UTC
Labels: Ads Visible
