### ISSUE TITLE
linguee.com shows blank pages when not whitelisted

### ISSUE THREAD

**Issue by usharf** [dhowe/AdNauseam#824] opened 2017-02-01 18:00 UTC
linguee.com will not load (blank page) unless white listed. 

I only have AdNauseam installed as a blocker in Firefox Nightly - 54.0a1 (2017-02-01) (64-bit), on macOS 10.12.1 (16B2555).

```
18:57:39		##DIV[class^="ad_"]	--	dom	http://www.linguee.com/
18:57:39		##.verticalAdText	--	dom	http://www.linguee.com/
18:57:39		##.horizontalAdText	--	dom	http://www.linguee.com/
18:57:39		###wide_banner_right	--	dom	http://www.linguee.com/
18:57:39		###banner_top	--	dom	http://www.linguee.com/
18:57:38		||linguee.com*/white_pixel.gif?	--	image	http://www.linguee.com/white_pixel.gif?number=333954101
18:57:38				image	http://static.linguee.com/img5/about/chapter3p.jpg
18:57:38				image	http://static.linguee.com/img5/about/chapter2p.jpg
18:57:38				image	http://static.linguee.com/img5/about/chapter1p.jpg
18:57:38				image	http://static.linguee.com/img5/about/EN-DE/laptop.png
18:57:38				image	http://static.linguee.com/img5/about/EN-DE/android-1.png
18:57:38				image	http://static.linguee.com/img5/about/android.png
18:57:38				image	http://static.linguee.com/img5/about/EN-DE/iPhone.png
18:57:38				image	http://static.linguee.com/img5/sprites15.png
18:57:38				image	http://static.linguee.com/img5/logo_big.png
18:57:38		||linguee.com*/white_pixel.gif?	--	image	http://www.linguee.com/white_pixel.gif?number=333954101
18:57:38				script	http://static.linguee.com/28391/javascript/about.min.js.g
18:57:38				script	http://static.linguee.com/28391/javascript/linguee4-all-late.min.js.g
18:57:38				script	http://static.linguee.com/28391/javascript/linguee4-early.min.js.g
18:57:38				css	http://static.linguee.com/28391/css3/about.min.css.g
18:57:38				css	http://static.linguee.com/28391/css3/style4-early-late.min.css.g
18:57:38				inline-script	http://www.linguee.com/
18:57:37				doc	http://www.linguee.com/
```

**Comment by cqx931** [comment] 2017-02-03 17:47
Thanks for reporting the issue, the problem should be fixed now.
Please update adnauseam.txt with the following steps and see if the problem is solved for you.

1.Go to AdNauseam Settings page (from Menu), then open the 3rd-party-filters panel
2.Click 'purge-all-caches' - 'apply changes' - 'update now'
3.Reload the page on which you saw the problem

**Closed** 2017-02-27 03:38 UTC
Labels: Needs-verification

**Comment by dhowe** [comment] 2019-01-23 11:34
Please re-open this one and include OS and Firefox versions
