### ISSUE TITLE
Mid-video ads playing on youtube

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#298] opened 2016-07-22 01:58 UTC
Example: https://www.youtube.com/watch?v=SbCt-iXIXlQ

Issue: ad is obnoxiously injected into the middle of an already playing video (in this case after 5 min or so); the video stops, the ad plays, then the video resumes
- First verify the issue on ADN
- Then test if it can be recreated on current uBlock... 
- If the problem exists on uBlock, file an issue there and close this ticket for now
- If the problem does not exist on uBlock, then we need to find the rules that are firing on uBlock, but not on ADN (use the logger to figure this out)
- Then enable these rules in ADN and retest to verify it solves the problem

v2.3.1 / Chrome / OS X

**Comment by CyrusSUEN** [comment] 2016-07-22 12:22
> ad is obnoxiously injected into the middle of an already playing video

How obnoxious is it? Is it the already playing video got paused and forced to listen to an ad (assuming the video tab is in the background)?

I've been listening the track for 20+ mins and no problem has been found so far on ADN version 2.3.1 from the Release page on Chrome 52. Are there other links for the test? I will work on other tickets while having the video and logger page in the background.

> Then test if it can be recreated on current uBlock...

I think it's safe to assume ublock is not affected because YouTube is just too popular too be ignored if it was bugged.

**Comment by dhowe** [comment] 2016-07-22 19:08
> How obnoxious is it? Is it the already playing video got paused and forced to listen to an ad ?>(assuming the video tab is in the background)?

Extremely. The playing video is stopped and disappears, the ad plays until completion, then the video reappears and continues.

**Comment by CyrusSUEN** [comment] 2016-07-23 08:18
> use the published version from the chrome, ff, or opera store

OK. Switched to this. But I cannot reproduce the problem.

Now I use a [VPN Chrome extension](https://chrome.google.com/webstore/detail/unlimited-free-vpn-hola/gkojfkhlekighikafcpjkiklfbnlmeio) and route the video through US servers and see if there will be ads.

**Comment by CyrusSUEN** [comment] 2016-07-23 12:37
With a default ADN settings from Chrome store and using a USA VPN I still cannot reproduce the problem.

**Comment by dhowe** [comment] 2016-07-23 12:43
The only thing I can suggest is to wait for a longer time -- this happened to me after at least 15 minutes of listening to the track above. Perhaps just select a full album of music (~ 1 hour), and leave it to play while working on other issues....

But otherwise we can put this on hold until/unless it happens again

**Comment by mneunomne** [comment] 2021-06-22 14:28
Outdated issue. Closing

**Closed by mneunomne** 2021-06-22 14:28 UTC
Labels: Chrome, On-hold
