### ISSUE TITLE
Update DNT-list appearance on 'whitelists' page to match 3p-filters page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#917] opened 2017-03-07 18:33 UTC
Currently invisible, not sure why...

![screen shot 2017-03-08 at 2 31 37 am](https://cloud.githubusercontent.com/assets/737638/23671813/8bd2faa4-03a7-11e7-82c6-53c7e0f5536a.png)

Also pls verify that it updates state (checked or not checked) when DNT settings are changed, but remains non-editable by user

**Comment by cqx931** [comment] 2017-03-09 02:50
This should be caused by another fix to 3p-filters. Fixed now and close:
https://github.com/dhowe/AdNauseam/pull/918/commits/0352011fdcdb2f57dc229a9e067047f1d43628b9

**Closed by cqx931** 2017-03-09 02:50 UTC
Labels: PRIORITY: Medium
