### ISSUE TITLE
Empty frame, dynamic filtering issue

### ISSUE THREAD

**Issue by Snaxeko** [dhowe/AdNauseam#1852] opened 2021-05-30 17:33 UTC
### Describe the issue

_Tested in a new Firefox profile._ After clicking on µ/more/more, there should be this window every time I open the extension UI & click on "µ".
![image](https://user-images.githubusercontent.com/20836655/120113446-caf29b00-c17a-11eb-9627-fe562fae2779.png)

It works only 1 time.

No issue for µ/more/more/less (if I close the dynamic filtering setting)

### Screenshot in which the issue can be seen

After that there's an empty frame (after clicking on "µ").
![image](https://user-images.githubusercontent.com/20836655/120113545-418f9880-c17b-11eb-84bf-78ad305fe0f9.png)

### Steps for anyone to reproduce the issue

1. Install Adnauseam
2. Go to µ/more/more(/more eventually, same issue as long as there's the table)
3. Close the Adnauseam window
4. Go to "µ" again, observe an empty frame

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 88.0.1
- AdNauseam version: 3.10.4
- Other extensions you have installed: No
- AdNauseam settings: default settings, custom settings, I also tried to enable the 3 boxes.

##### Your filter lists
Default.

### Your location/country
France

**Comment by HXAPEWiZZ** [comment] 2021-06-07 23:24
This happens on Librewolf after uninstalling uBlock Origin, Librewolf is essentially the same as firefox but with a bunch of settings changed for privacy.

**Comment by HXAPEWiZZ** [comment] 2021-06-08 00:08
I found a shitty temporary fix: everytime you need that menu, if you just used it on the regular toolbar, put the AdNauseam icon in he overflow menu and use it from there, and vice versa.

**Comment by dhowe** [comment] 2021-06-08 17:42
@mneunomne progress on this issue?

**Comment by mneunomne** [comment] 2021-06-09 09:17
@dhowe I can confirm this issue is happening on firefox with Adn 3.10.4. But it seems to be related to this issue https://github.com/dhowe/AdNauseam/issues/1847 , I tested and it not happening anymore with merge 1.34.0.

**Comment by dhowe** [comment] 2021-06-10 06:16
So this will be fixed in the next release, which should be in the next few days...

**Comment by mneunomne** [comment] 2021-06-10 11:34
Yes, I still should run more tests related to this though.

**Comment by mneunomne** [comment] 2021-06-27 19:17
Tested, it seems to be working as expected now.

**Closed by mneunomne** 2021-06-27 19:17 UTC
Labels: Bug
