### ISSUE TITLE
Possible Memory Leak on Firefox/Linux

### ISSUE THREAD

**Issue by jadenPete** [dhowe/AdNauseam#1267] opened 2017-10-28 17:02 UTC
### Describe the issue
This doesn't happen when I disable AdNauseam, but sometimes the memory usage of Firefox will rise above the amount I have in a matter of seconds (about a 4GB increase). This causes my system to freeze for a minute as it falls back onto swap. Then, it goes back to normal.

### One or more specific URLs where the issue occurs
I haven't recorded any specific URLs, there never seems to be a pattern. I'll do that from now on.

### Screenshot in which the issue can be seen
Screenshots aren't really applicable for this issue.

### Steps for anyone to reproduce the issue
Regularly use AdNauseam on various websites.

### Your settings

- OS/version: Arch Linux
- Browser/version: Firefox Nightly
- AdNauseam version: v3.4.205, though v3.4.2 had the same issue
- Other extensions you have installed: Gnome Shell Integration, [Google Translate This Page](https://github.com/andreicristianpetcu/google_translate_this) (Unlisted), New Tab Override, Open image in new tab, Reddit Enhancement Suite, Skip Redirect, Smart HTTPS

**Comment by jadenPete** [comment] 2017-10-28 17:09
I'd also like to add that the memory usage fluctuates a lot too.

**Comment by dhowe** [comment] 2017-10-28 17:42
Thanks for this report, @jadenPete ... also would be great if you had some specific URLs we could use to try and recreate

**Comment by jadenPete** [comment] 2017-10-28 17:56
I was able to find this in about:memory:
![screenshot from 2017-10-28 10-55-17](https://user-images.githubusercontent.com/13180372/32137115-a3103e86-bbce-11e7-8f88-e13a2a43e5b6.png)
![screenshot from 2017-10-28 10-55-39](https://user-images.githubusercontent.com/13180372/32137116-a32e331e-bbce-11e7-8b2d-666439e5f738.png)

**Comment by jadenPete** [comment] 2017-10-28 17:59
The top screenshot is when the memory usage got a little out-of-hand. I noticed that my NoCoin filter shows up on the top, I'll try disabling that.

**Comment by jadenPete** [comment] 2017-10-28 18:02
Holy moly, just found this as well. I'm just browsing Reddit
![screenshot from 2017-10-28 11-01-26](https://user-images.githubusercontent.com/13180372/32137171-6ee740f4-bbcf-11e7-88ad-0c862e859f10.png)
:

**Comment by jadenPete** [comment] 2017-10-28 18:23
It's always the NoCoin, then the DNT Whitelist if disabled.

**Comment by dhowe** [comment] 2017-10-29 04:12
Correct me if I'm wrong here, but I think the message may simply be noting a particularly long string, which is the list of currently selected lists for the user ('selectedFilterLists'). The NoCoin list just happens to show up as the first item in this list, and when disabled, the eff-dnt-whitelist is first. So I don't think we can interpret it as any particular list causing the issue. 

Also, I see that even when the memory problem is occurring, AdNauseam is using only ~5% of Firefox memory, which makes me think something else may be contributing to the problem (or that the dev tools are not correctly separating the memory allocation; suspicious as well that the strings don't show up under the addon, but under the dom category)

**Comment by dhowe** [comment] 2017-10-29 04:28
Also, the nocoin list is largely a duplicate of ublock's included resource-abuse list: https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt

**Comment by jadenPete** [comment] 2017-10-29 04:48
Was not aware that it is included, thanks. I know it sounds crazy, but this doesn't occur when I disable AdNauseam. Is there anything I can do to help?

**Comment by markasoftware** [comment] 2017-10-31 03:22
I can also confirm that I have this issue. It usually occurs on "heavy" websites such as news websites, ad-bloated review sites, etc. But it's still enough to make me switch to something else (just uBlock?) until this is resolved.

**Comment by dhowe** [comment] 2017-10-31 04:46
Would be great to have a few websites on which we can reliably recreate this behavior...

Also @markasoftware, can you include your version info as well (OS, browser, AdNauseam) ?

**Comment by markasoftware** [comment] 2017-10-31 05:19
@dhowe Arch Linux (on multiple machines), Firefox 57 Beta, and whatever the latest version of AdNauseam on the firefox add on store today is.

**Comment by jadenPete** [comment] 2017-10-31 05:49
Yes it definitely occurs on news websites.

**Comment by dhowe** [comment] 2017-10-31 09:38
Seems this maybe be specific to linux/firefox... I can investigate later in the week
But one question -- did either of you have the advault open when the problem was occurring (perhaps in a non-active tab) ?

**Comment by markasoftware** [comment] 2017-10-31 13:58
@dhowe nope, it works without any ad vault open. It can happen with only one tab open.

**Comment by jadenPete** [comment] 2017-10-31 14:08
Nope, no advault open. It works with multiple tabs for me.

**Comment by xsduan** [comment] 2017-12-05 00:42
I'm having this same issue, but on macOS 10.13, so I thought I might as well drop this here.

```
OS: macOS 10.13.1 on MBP Retina mid-2015
RAM: 16GB 1600 MHz DDR3
Version: Firefox Quantum 57.0.1 (64-bit)
```

Add-ons:
- AdNauseam
- RES

Tabs open:  
- Instructure Canvas (x3)
- https://www.rottentomatoes.com/
- http://www.indiewire.com/2017/11/daddys-home-2-review-mel-gibson-mark-wahlberg-will-ferrell-1201896228/
- https://www.independent.ie/entertainment/movies/movie-reviews/cinema-suburbicon-the-arch-humour-of-the-coens-is-channelled-well-by-clooney-36350927.html
- https://www.newstatesman.com/culture/film/2017/11/what-daddy-s-home-2-tells-us-about-career-ruining-hollywood-scandals
- https://wordcounter.net/

It pretty consistently causes a memory leak (up to 40GB uncompresssed + a few gigs of swap at one point) and it only started when I switched to FF57.

It leaks at a smaller rate (5MB/min) if I only have a few ad-light websites open but it's still noticeable.

Adblock Plus doesn't have this problem so it seems like it must be the hidden-clicks.

**Comment by dhowe** [comment] 2017-12-07 06:34
Would you mind testing if this happens with [ublock origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)?

**Comment by xsduan** [comment] 2017-12-07 08:10
Memory usage with uBlock and RES, with AdNauseam and AdBlock Pro disabled, with listed tabs open after a few minutes:
<img width="800" alt="activity monitor" src="https://user-images.githubusercontent.com/9505910/33704386-24f6c07e-dae1-11e7-89e7-4cf8c4d16510.png">

With AdNauseam (but only about 30-60s):
<img width="800" alt="activity monitor" src="https://user-images.githubusercontent.com/9505910/33704826-d54b4c46-dae2-11e7-8c4f-bdd936142086.png">

Memory usage with same parameters but with only this page, [reddit](https://www.reddit.com/) and [xkcd](https://xkcd.com/) open:
<img width="800" alt="activity monitor control" src="https://user-images.githubusercontent.com/9505910/33704482-84f4690e-dae1-11e7-90a0-73898c915806.png">

With AdNauseam:
<img width="800" alt="activity monitor control" src="https://user-images.githubusercontent.com/9505910/33704824-d3335818-dae2-11e7-888b-489fc25104e1.png">

uBlock and ABP seem to grow in memory usage in the short-term but not as dramatically as I've seen with AdNauseam.

Ad-light pages seem to also not cause many issues.

**Comment by markasoftware** [comment] 2017-12-07 15:56
@dhowe I have been using uBlock origin with the latest version of
Firefox Beta since I stopped using AdNauseam, and never had any memory-
related issues since then.

**Comment by dhowe** [comment] 2017-12-07 15:56
Interesting, thanks. Question: how many ads do you have in your advault? And do you have the same result after clearing it?

**Comment by markasoftware** [comment] 2017-12-07 16:13
@dhowe I haven't been using AdNauseam for a couple months because of this, but I had only been using it for under a week when this started happening. This occured with under 1000 ads in the advault, I think. I don't believe it's related to number of ads in the vault. I might check this later.

**Comment by jadenPete** [comment] 2017-12-10 07:42
For me it was around 8000 ads in the vault. Haven't used AdNauseam in a month as well due to this.

**Comment by dhowe** [comment] 2017-12-27 11:52
This may well be resolved in version 3.5 -- can someone give it a test? thanks

**Comment by markasoftware** [comment] 2017-12-27 18:25
Trying version 3.5. I will report on how it goes in a couple days or sooner.

**Comment by jadenPete** [comment] 2017-12-28 03:06
Will do. I'll report back soon.

**Comment by markasoftware** [comment] 2017-12-28 03:16
So far, with a lot of use today, no problems. It seems to be fixed but I'll need to give it more days before I can be sure.

**Comment by dhowe** [comment] 2017-12-28 03:47
Thanks -- please report back with any further findings...

**Comment by PyrionCelendil** [comment] 2018-04-22 11:06
I realize there hasn't been any activity on this for a while, but I'm having the same issue in Firefox on Windows 10 with v. 3.5.101, and have figured out how to reliably reproduce it on my end:

1. Load the Ad Vault in a separate tab.
2. Load a site in another tab that attempts to load a lot of ads (ex: CNN, the Daily Mail).

Within a few seconds of page load, RAM usage will spike and oftentimes keep going until it hits the limit (12GB on my system) and starts paging out.

Clearing the Ad Vault fixes it (I could load both of the troublesome sites with memory usage only increasing by a couple hundred megabytes), and I estimate I had around 8000 ads in it as well.

**Comment by eiglow** [comment] 2019-10-16 09:16
Sometimes [this site](https://www.phoronix.com/) seems to cause a memory leak or other strange memory usage for me.

**Comment by dhowe** [comment] 2019-10-16 10:49
@cqx931  can you [test this](https://github.com/dhowe/AdNauseam/issues/1267#issuecomment-383373460)

**Comment by cqx931** [comment] 2019-10-16 18:55
For the one back in 2018, AdNauseam does slow down the computer a lot when I tried to load CNN/Daily mail with Ad Vault open(with approx. 6k ads in it) on a windows machine. The memory usage can goes up to 2-3k MB for Firefox when only two tabs are open. I also got warning from Firefox that some tab is slowing down the computer, it never hits the limit though. Taking into account that ad vault automatically updates itself when new ad is found, this makes sense, although back in 2018 this shouldn't be the reason for this issue. 

For https://www.phoronix.com/,  there are many ads on a single page. Just browsing the website itself will cause high CPU/Memory/Slow browser for a few seconds, but it goes away once all ads are parsed for me.

**Comment by dhowe** [comment] 2019-10-18 03:24
> For the one back in 2018, AdNauseam does slow down the computer a lot when I tried to load CNN/Daily mail with Ad Vault open(with approx. 6k ads in it) on a windows machine. The memory usage can goes up to 2-3k MB for Firefox when only two tabs are open. I also got warning from Firefox that some tab is slowing down the computer, it never hits the limit though. Taking into account that ad vault automatically updates itself when new ad is found, this makes sense, although back in 2018 this shouldn't be the reason for this issue.

Does this no longer happen in the current version?

**Closed** 2021-06-22 16:38 UTC
Labels: Firefox, Linux, Needs-test-case, PRIORITY: High
