### ISSUE TITLE
Ads not collected in some sites

### ISSUE THREAD

**Issue by DamjanMenton** [dhowe/AdNauseam#1415] opened 2018-10-18 17:01 UTC
### Describe the issue
Hello everyone,
I noticed that some ads were blocked, but not collected on multiple websites.

### An exemple : 
On e-hentai.org there are two ad banner on the top of the page. With the normal lists, they are displayed (on ublock, they are blocked). When I had the AdGuard Base filters, the ads are blocked, but they don't show in the Adnauseam icon.

### Screenshot in which the issue can be seen
![000009-window](https://user-images.githubusercontent.com/11681782/47170970-d4030680-d307-11e8-9dbf-d6b25d20d426.png)
You can see in the top right corner that Adnauseam doesn't click nor collect ad.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Use the default filter settings
2. Go on the website
3. The ad is visible
4. Add the Adguard Base filters
5. Reload page
6. The ads are not visible and not collected

### Your settings

- OS/version: Windows 10 (1803)
- Browser/version: Firefox Nightly 64.0a1
- AdNauseam version: 3.7.802
- Other extensions you have installed: No other extensions 

##### Your filter lists
Default lists + Adguard Base

### Your location/country
Not country related

**Comment by DamjanMenton** [comment] 2018-10-28 14:50
Some more informations : 
I tested with the latest Firefox (stable, not nightly) in a new virtual machine, the issue is still here.
There are lots of other sites of the same type that has this collecting problem.

Thanks,

**Comment by dhowe** [comment] 2018-10-29 06:18
I notice 3 problems on this site:
1. Ads are visible with default lists (blocked in ublock)
2. Ads are not collected when hidden/blocked via 'Adguard Base' list
3. Right-click 'block element' menu doesn't work
@cqx931 can you take a look (post-exhibit) ?

**Comment by DamjanMenton** [comment] 2018-10-29 18:31
Of course ! There is a lot of websites that still has ads visible (with the same problem).
Here are some exemples : 
- torrentfunk2.com (top of main page and in most pages)
- hentaimama.com (top right of the main page and in some pages)
- pornhub.com (when searching a video or on the side of the player)
- youporn.com (main page)
- xvideos.com (This one has a subtility : the ads show for 1 sec and then disappears, but don't get clicked or collected. Video ads in the player still plays)
- and a lot more, most of them are NSFW.

Sorry, I did not put direct link due to the nature of most of theses websites, but I think you'll understand.

Most of these ads seems to have trafficjunky and juicyads as ad provider.
I also have a lot of ad popup for games or malwares (fake download, etc.)
Exemple below : 
![000010-window](https://user-images.githubusercontent.com/11681782/47671450-cc691a80-dbaf-11e8-94fe-c938e880b50c.png)

**Comment by dhowe** [comment] 2018-10-30 04:16
Thanks for this. What would be great for us to know is which of these have ads visible with uBlock Origin (and not AdNauseam) enabled?

**Comment by DamjanMenton** [comment] 2018-10-30 08:55
uBlock Origin seems to block all of them. I can't say precisely, my second computer that I use for tests like this has special network rules, it might be this who blocks the ads. 
However, I'm looking at the filters list of uBlock and it seems that these ads are listed in the main uBlock list.

**Comment by dhowe** [comment] 2018-10-30 14:05
The Adnauseam counter works a bit differently than the uBlock one does: our counter is only for ads that are actually collected, not those that are blocked or hidden (as is the case with uBlock). So AdNauseam may well be blocking/hiding ads on those pages, but the counter would still read 0 until one is successfully collected. The ideal way to test such things is to install AdNauseam and uBlock on the same computer (this doesn't cause any problems), then just enable one at a time and compare (though of course we understand if you don't have the time)

**Comment by DamjanMenton** [comment] 2018-10-30 17:08
I doubted that the counter worked differently as it sometimes hide ads but don't shows as many numbers as uBlock. Thanks for the explanation.

So I installed uBlock Origin on the same computer and deactivated Adnauseam : all the sites I listed above don't show ANY ads anymore, uBlock is correctly blocking them.

**Comment by dhowe** [comment] 2018-10-31 02:44
Thanks, we will look into these. Please keep adding to the list above if you find any other sites with visible ads (that are correctly blocked by uBlock)

**Comment by Dyras** [comment] 2019-02-11 15:05
Flashback has ads that are successfully blocked with AdNauseam, but they aren't collected or clicked. Every ad on the site starts with flashback.org/ads/ so it should be easy to fix... Probably.

https://www.flashback.org/

Here are some pics of the ads:
![image](https://user-images.githubusercontent.com/12563436/52571791-95dda580-2e16-11e9-9199-46f9950df7fc.png)
![image](https://user-images.githubusercontent.com/12563436/52571812-a130d100-2e16-11e9-8bae-c92669d8cbc0.png)

**Comment by cqx931** [comment] 2019-02-22 14:28
@KenLiHK, could you please check https://www.flashback.org/? Thanks!

**Comment by KenLiHK** [comment] 2019-02-23 08:53
2 yellow log message found
##.adcontainer
##.ad-disclaimer

##.ad-disclaimer is found in the "EasyList" -- "General advert blocking filters". 
When ads is blocked, ADN cannot collect it.

![image](https://user-images.githubusercontent.com/24424527/53284154-0aa3ce80-378b-11e9-9a5f-ec9d3f3fa936.png)



### Your settings
* OS/version: Windows 10 Enterprise
* Browser/version:
  
  1. Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  2. Firefox 63.0.3 (64-bit)
* AdNauseam version: AdNauseam3.7.802
* Other extensions you have installed: N/A

##### Your filter lists
AdNauseam filters​​​​
EasyList​​​​​
EasyPrivacy​​​​​
uBlock filters​​​​​

uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
My filters​​​​​

Malware Domain List​​​​​
Malware domains

### Your location/country
Hong Kong

**Comment by metapea** [comment] 2019-03-14 11:01
There another adult site called _hitomi .la_ that still show ads and give you pop-up ad if you click anywhere in the site, these are the site that they to redirect to:
- byxlivaqzo.com
- s24hc8xzag.com
- pxthyfgzm.com
- dpnahzfbb.com
- ie8eamus.com
- ie8eamus.com/sfp.js
- ads.exosrv.com
- ads.exosrv.com/ads.js
be careful, the site's pop-up ads slowed down my browser with it freezing afterword multiple of times now.

also uploading sites like 1fichier.com is still showing ads and it's not letting me download unlike before, mediafire is still showing ads from adchoices, zippyshare is sometimes giving me pop-up ads when i click download, and with youtube/soundcloud downloaders like vubey.yt and flvto.biz/mp3-320kbps there usually pop-up ads when you click the download/save as button when you first click or when you click on convert like ytmp3.eu

**Comment by dhowe** [comment] 2019-03-14 12:24
Thank you for the report. Have you checked that these ads are hidden using uBlock?

**Comment by metapea** [comment] 2019-03-14 13:01
I'm just testing this with the AdNauseam alone, these pop up when using the latest version.

**Comment by dhowe** [comment] 2019-07-23 11:12
on-hold pending further research

**Comment by mneunomne** [comment] 2022-08-03 09:07
@dhowe should we perhaps close this? There are multiple cases documented here which is useful, but also outdated at the moment.

**Comment by Dyras** [comment] 2022-08-03 13:32
I'd say this is is still an issue with a lot of sites.
For example, three major Swedish news sites all have this problem:
https://www.aftonbladet.se/
https://www.dn.se/
https://www.expressen.se/

Left is Firefox with AdNauseam, right is Chrome in Guest Mode without any extensions
![grafik](https://user-images.githubusercontent.com/12563436/182620313-838e600d-0076-4c8b-877d-7a93ad5552ee.png)
![grafik](https://user-images.githubusercontent.com/12563436/182620335-b859998b-d526-4c2e-8cf8-38e7ccefbd95.png)
![grafik](https://user-images.githubusercontent.com/12563436/182620366-9e85b7c1-cc57-4b31-969c-68368620e532.png)

**Comment by DamjanMenton** [comment] 2022-08-03 13:50
I can confirm that there are still a lot of websites were ads are not blocked/collected. I stopped using AdNauseam since last week to use uBlock Origin instead, that is lot more efficient against ads.

**Comment by Dyras** [comment] 2022-08-03 13:54
I've never had any real issues with ads not being blocked. They are rarely collected and clicked though. Which is a pity, as that's the entire point of the addon.

Personally, I still have fate that they will sort this out. I think it's an amazing idea and I hope one day that they will make it work as intended :)

**Comment by mneunomne** [comment] 2022-08-03 14:37
Thank you for the feedback, we try to keep the balance between ad collection and ad blocking, unfortunately there is no universal solution for what we propose to do, and as your comments themselves show, is that there is also significant differences of behaviour depending on your location and types of website you may visit.

-----------------------

> https://www.aftonbladet.se/
> https://www.dn.se/
> https://www.expressen.se/

Thank you @Dyras, I will take a look on these cases specifically.

**Comment by mneunomne** [comment] 2022-10-18 03:24
Addressed the remaining websites I mentioned above. Closing

**Closed by mneunomne** 2022-10-18 03:24 UTC
Labels: Ads Visible, Ads Not Collected
