### ISSUE TITLE
domain mail.Yandex.ru advertising is not blocked

### ISSUE THREAD

**Issue by f1h0** [dhowe/AdNauseam#1731] opened 2020-09-09 09:13 UTC
downloaded the latest version of AdNauseam
decided to check how it will work.
but does not want to block ad units in the Yandex domain

![image](https://user-images.githubusercontent.com/1436880/92579408-d40ea580-f295-11ea-97a3-224313ac99c5.png)

**Comment by mneunomne** [comment] 2021-02-16 15:03
I created an Yandex email specifically for this issue, but perhaps will be hard to reproduce since probably the ads come sporadically. I'll check a few more times before labelling as "can't reproduce"

**Comment by f1h0** [comment] 2021-02-19 13:02
> I created an Yandex email specifically for this issue, but perhaps will be hard to reproduce since probably the ads come sporadically. I'll check a few more times before labelling as "can't reproduce"

You need a browser with the RU language and walk around the sites, after 1-2 hours an advertisement will appear)

**Comment by mneunomne** [comment] 2021-02-28 14:10
After a lot of tries, the ads finally started to show up immediately.

Fixed with https://github.com/dhowe/AdNauseam/pull/1758.

**Closed** 2021-02-28 16:13 UTC
Labels: Ads Visible
