### ISSUE TITLE
youtube subscriptions not loading

### ISSUE THREAD

**Issue by undifined5** [dhowe/AdNauseam#2211] opened 2022-11-08 19:08 UTC
### Describe the issue

When i visit my subscriptions they keep loading but nothing will appear. i didnt make any recent changes to adnauseam and a couple of days ago it did work and it does load when i disable adnauseam and when i then click on a video and start adnauseam again then adnauseam will block the adds and the video will load. this issue doesn't really bother me but google said they where cracking down on addblockers and i do believe that this is one of the changes they made and therefor i thought i would still report this.

URL: https://www.youtube.com/feed/subscriptions

### Screenshot in which the issue can be seen
![adnauseam](https://user-images.githubusercontent.com/117756818/200648401-8cd1b5a3-d353-496c-be80-4f17540bddbf.JPG)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

have a youtube account and subscribe to some youtubers then go to your subscriptions while having adnauseam on.

### Your settings

- OS/version: windows 10 (the latest because windows sadly updates automatically and this is on both)
- i also did a virusscan just to be sure and nothing was found on both pc's
- Browser/version: firefox 106.0.1 and firefox 106.0.3 (2 seperate pc's)
- AdNauseam version: 3.15.1 and 3.14.5 (2 seperate pc's)
- Other extensions you have installed: only the theme: Autumn in Japan theme by MaDonna (on both pc's)
- AdNauseam settings: 

![adnauseam settings 1](https://user-images.githubusercontent.com/117756818/200651832-b5a948ba-d8c2-472e-a18d-3b3a17474b0d.JPG)
![adnauseam settings 2](https://user-images.githubusercontent.com/117756818/200651854-1048f443-53dd-4fbb-969b-7e8b8416f401.JPG)
![adnauseam settings 3](https://user-images.githubusercontent.com/117756818/200651874-3c0d4dcf-dbb7-4009-bc6e-c1784440631e.JPG)

its almost the same in both pc's except one of them uses more personal filters, but it doesnt have the languages pack or the EFF DNT Policy Allowlist.

##### Your filter lists

see pictures

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

the netherlands

** For adult or potentially offensive sites/ads, please add a [Content-Warning] tag in the title to warn developers the ticket may contain such material.

**Comment by mneunomne** [comment] 2022-11-09 13:20
Thank you for submitting this issue. Can you copy the information found in support/troubleshooting so we can have more information? It can be found here:

<img width="927" alt="Screenshot 2022-11-09 at 14 19 48" src="https://user-images.githubusercontent.com/4967860/200840967-4ffa2c9d-54cd-4917-99cd-f742d7fcf3dd.png">

(Weird that "AdNauseam filters" is in the category of "customs" in your interface, instead of "Essentials", need to check that)

**Comment by undifined5** [comment] 2022-11-18 14:37
thanks for the very quick responce!
uhm how can i give these 6379 pages 0_0 without giving my browser history? i ask this because i keep seeing urls in this from years ago, some even from idk 5 years ago or so.

**Comment by mneunomne** [comment] 2023-02-17 14:53
Actually this is a good point, troubleshoot should not include information of collected ads.

**Comment by mneunomne** [comment] 2023-02-21 01:04
@undifined5 we addressed the issue of the collected ads appearing in the troubleshoot, should be in the next official release in the next couple of days.

Regarding the bug itself, did you try to force update the third party filter lists?

**Comment by mneunomne** [comment] 2023-03-03 15:11
Can't reproduce this issue on my end, I imagine this is fixed now in new version. @undifined5 can you confirm that please?

**Comment by dhowe** [comment] 2023-03-05 09:52
closing for now (reopen if there is more info)

**Closed by dhowe** 2023-03-05 09:52 UTC
Labels: Cannot Reproduce
