### ISSUE TITLE
AdNauseam peaks CPU usage with large ad set

### ISSUE THREAD

**Issue by satonakamo** [dhowe/AdNauseam#1657] opened 2020-05-01 13:52 UTC
I have this issue since a few months now. I was able to pin it down to AdNauseam.
When I monitor the tabs from the Firefox task manager AdNauseam is constantly hitting high CPU usage and it does it so frequently that overall the CPU is always maxed out at about %90.
As soon as I disable it from the Firefox extension menu the CPU calms down.
After I turn AdNauseam on it doesn't kick in immediately but after a while.
The laptop is constantly running on full fan speed and it is very noisy.
My current setting for clicking on adds is set to sometimes.

![adnauseam](https://user-images.githubusercontent.com/47419364/80810146-7b325080-8bc3-11ea-93fb-078405c0078b.png)

### Your settings

- OS/version: Windows 
Version	10.0.18362 Build 18362
- Browser/version: 75.0 (64-bit)
- AdNauseam version: 3.9.104
- Other extensions you have installed:
To Google Translate 4.0.6

##### Your filter lists
I am using the default settings.

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

**Comment by satonakamo** [comment] 2020-05-13 20:02
I am still having this issue. I decided to investigate the logger output and I notice that i have many triggers with the following message

`Static filter ##.adsbygoogle, ins[id*="aswift"] > iframe, iframe[id^="google_ads_frame"], #google_image_div, #mys-content:style(height:0px!important;) could not be found in any of the currently enabled filter lists`

Is it normal that the filter is not found? Also what exactly does it mean if a filter is not found in the enabled filter lists, then where is this filter specified to begin with?

**Comment by cqx931** [comment] 2020-05-14 20:38
Hi @satonakamo 
Thank you for helping to narrow this issue down, that's a filter AdNauseam added to by-pass certain dom elements in google's ad system. It's not in the adnauseam.txt filter list so that's why the logger couldn't find it. 

It seems like it's the Gmail tab that's causing the trouble here from your screenshot. Do you also experience it with other web pages?

**Comment by satonakamo** [comment] 2020-05-14 21:10
Hi @cqx931 
I also experience it on other web pages. For instance yesterday it was ebay that was triggering %100 CPU usage. I was searching online and ended up resetting AdNauseam to default settings. Until now, that seems to have solved the issue. 
Could it be that my ad vault was getting to big? I exported before resetting and I had 43K~ collected ads (counting the occurance of the string "targetUrl") Maybe the database was getting too heavy ?

**Comment by cqx931** [comment] 2020-05-14 21:34
@satonakamo Yes, that's definitely a very large vault. But as long as you don't have your vault opened all the time that shouldn't be an issue. If you have advault open, Adnauseam does automatically update it live when it finds more ads. 

Could you try to re-import the ads and see whether that brings back the issue?

**Comment by satonakamo** [comment] 2020-05-14 22:34
@cqx931 Ok i did that now. It imported around 23K ads, and then the energy impact of AdNauseam in the task manager started hitting high values ~1500 periodically, when I reloaded the youtube and ebay tabs. I then reset to default setting and did the reload test again and the energy impact was at medium values ~3. The advault was not open during the tests.

**Comment by cqx931** [comment] 2020-05-14 22:46
@satonakamo Thanks! High energy impact during import is expected because that's a lot of data to parse and AdNauseam needs to redownload tons of images. 

Let me know if you could see high AdNauseam energy impact again while browsing.

**Comment by satonakamo** [comment] 2020-05-14 23:02
@cqx931 I think you misunderstood me. I was reporting the energy impact after the import was completed and during reloading the tabs. So indeed my result is that normal browsing while the advault is full has higher energy impact. When I reset to default settings, effectively emptying the vault, everything goes back to normal with low energy impacts.

**Comment by cqx931** [comment] 2020-05-14 23:50
@satonakamo I see! I don't think I have a sample ad file as big as that...The largest sample on my side is 1k. When I test with that file, the energy impact ranges from low to medium, but not on high. Do you mind sharing your exported ad file only for testing purposes? You can either send it to us by email(adnauseam@rednoise.org) or through any other way you trust.

**Comment by satonakamo** [comment] 2020-05-15 00:07
@cqx931 I sent the file by e-mail. Thanks for looking into this.

**Comment by cqx931** [comment] 2020-05-16 01:15
Thank you, the file is well received. I can now reproduce the issue on my end.

There might be multiple reasons that this issue is caused by a huge ad set, but the main reason should be related to AdNauseam's [pollQueue()](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L261) function in the core.js

Every time pollQueue() is triggered regularly, [pengindAds()](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L308) will call [adlist()](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L1775)without a pageUrl parameter that will cause adlist() to return all the ads from the vault.

When the ad set is huge(the one in the example has over 24k ads), that will consume a lot of memory and CPU on a regular basis. When I comment out [line 298](https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/core.js#L298), that helps to prevent AdNauseam hitting insanely high energy impact. 

@dhowe 
I see pollQueue() is called on every interval even if the clicking function is disabled. But shouldn't we stop calling pollQueue() if ad clicking is disabled and only do setTimeout() when clicking is enabled?

If we do want to fix this for a large ad set, I think we need an alternative method for pendingAds(), so that we don't need to loop through the whole adset every time when we want to find one pending ad.

**Comment by dhowe** [comment] 2020-05-17 08:16
![image](https://user-images.githubusercontent.com/737638/82139331-935bce00-9859-11ea-85c2-5c05a9de4808.png)

**Comment by dhowe** [comment] 2020-05-17 08:17
![image](https://user-images.githubusercontent.com/737638/82139364-d9b12d00-9859-11ea-8e8f-9e7510e36765.png)

**Comment by dhowe** [comment] 2020-05-17 08:21
See https://github.com/dhowe/AdNauseam/pull/1660

Statistics look good! Perhaps only show root domain (facebook.com, rather than l.facebook.com) ?

**Comment by cqx931** [comment] 2020-05-17 19:33
The performance is much better now! 

I added another commit to further improve this by avoiding sending all the ad data to the menu. Please check: b61ea780e467c5d647dc9a7ce065703eb118b1e1
Before the change, the computer froze every time on menu open for this >20k adset. 
Now the core will only send ads from the current page or the most recent ads to the menu plus the number of total ads.
For home pages with feeds(reddit, facebook...etc), the total number of ads on the current page could be over hundreds for long term users. So I also restricted that size to the top 6. Let me know if this might bring up other issues.

After these two changes, I don't see Adnauseam hitting high anymore for this >29k adset.
The energy impact will increase to 40-50 every time when a click is performed, but that should be okay?

**Comment by dhowe** [comment] 2020-05-18 15:10
Looks good to me (though should test before release).

While does sending a click cause so much CPU ?

**Comment by HumanG33k** [comment] 2020-05-19 17:57
Probably you not release, but same issue when i try to test the addon on FF nightly 78.0a1 (2020-05-19) (64 bits) on linux computer. On my computer it consume all cpu at FF start. I post for the feedback.

**Comment by cqx931** [comment] 2020-05-20 13:25
@HumanG33k Thank you! Yes, we haven't released the changes yet. May I ask how many ads you have in your AdVault?

**Comment by HumanG33k** [comment] 2020-06-02 00:25
not sure about how check it. But my issue may not be only related with the plugin but also with some Firefox bugs.

**Comment by metapea** [comment] 2020-06-16 01:47
Also since i keep forgetting to make an issue, i need to tell you a similar thing is happening to chrome, but instead of CPU, it's ram and it's not coming from AdNauseam when look at chrome's taskmaster, it's from the main browser. At least in the past, the ram would always spike up when i want to random sites and it go all the way up to [3gb-5gb](https://i.imgur.com/hYPMtqt.png). And i know it's from AdNauseam since when the browser goes up to 2gb of ram the [extension's menu](https://i.imgur.com/HQAqOtS.png) starts to not work at all, incognito works fine on those websites without ram peaks, and those peaks from it only stopped when i updated AdNauseam and the custom filter lists were somehow gone, the browser was working normally for a short time

**Comment by ice-fly** [comment] 2020-06-21 07:40
Cpu spikes confirmed on chrome
_Google Chrome | 83.0.4103.106 (Official Build) (64-bit) (cohort: Stable)_
_OS | Windows 10 OS Version 1909 (Build 18363.900)_
_Intel i5-7300U @2.71Ghz_
![image](https://user-images.githubusercontent.com/11548922/85219258-56ab5700-b370-11ea-89af-7fe10548e80b.png)
I will try saving my ads & clearing them to see if I get improvement.

**Comment by cqx931** [comment] 2020-07-03 20:12
Can anyone help to test the latest AdNauseam with large ad set? Our fix for this issue should now be released to all browsers, it would be helpful if we can receive some update on this! Thanks!

**Comment by ice-fly** [comment] 2020-07-08 02:26
Seems to be working with large ad set...
![image](https://user-images.githubusercontent.com/11548922/86865673-74312e00-c09d-11ea-865b-85236f13441b.png)

**Comment by ice-fly** [comment] 2020-07-08 21:06
Still seeing spikes... ![image](https://user-images.githubusercontent.com/11548922/86970426-5ddaaf00-c13d-11ea-84dc-6ca35b2f41ac.png)

**Comment by cqx931** [comment] 2020-07-09 20:29
When I have over 20k ads in the vault, I will see a over 100 CPU usage when:
 
1. I open the settings page in the dashboard(it takes 1-2 seconds for that page to load)
2. An ad is clicked.

On other occasions AdNauseam seems to be doing fine with a large ad set, @ice-fly do you still see other scenarios for high CPU usage?

**Comment by ice-fly** [comment] 2020-07-10 23:01
It seemed good when I initially loaded the ads, but then became worse over time with "normal browser usage". 
I noticed it would come in bursts. Oscillating between ~10% usage to 100%. It was noticeable when loading new pages as the page loads would be slow. 
I suspect it has to do with appending the ads to the file but that's just a hunch. It would also explain why @cqx931 is seeing settings page lag because I believe both are stored in file/mem.

_I've been using adnauseum for 2+ years and it may just be the legacy ad collection._

**Comment by cqx931** [comment] 2020-08-27 15:55
see https://github.com/dhowe/AdNauseam/issues/1711, close this ticket for now

**Closed by cqx931** 2020-08-27 15:55 UTC
