### ISSUE TITLE
Don't click social buttons

### ISSUE THREAD

**Issue by chirag127** [dhowe/AdNauseam#2135] opened 2022-07-11 06:15 UTC
### Describe the issue
Don't collect social share button and don't click them. 

### screen shot
https://i.imgur.com/23jnV14.png
https://i.imgur.com/Rip8Y3Y.png

### Steps for anyone to reproduce the issue

Change settings to mine.
Go to https://indianexpress.com/article/political-pulse/from-distrust-to-acceptance-how-communists-shed-scepticism-for-constitution-8020444/

### Your settings

- OS/version: windows
- Browser/version:
![image](https://user-images.githubusercontent.com/76880977/178135116-00056c24-7521-4b2c-b0a5-36ac28a2457a.png)

![image](https://user-images.githubusercontent.com/76880977/178134996-28c82f38-c957-4d31-bf25-6e6d62373769.png)

- AdNauseam version:[image](https://user-images.githubusercontent.com/76880977/178134996-28c82f38-c957-4d31-bf25-6e6d62373769.png)
- AdNauseam settings: Default

##### Your filter lists
Default filter lists + AdGuard social filter + fanboy annoyance list 

### Your location/country
India

**Comment by dhowe** [comment] 2022-07-14 03:45
social media ads should be clicked, but not other buttons

**Comment by mneunomne** [comment] 2022-08-16 13:13
I cannot reproduce in this specific website (maybe because I don't have VPN option for india), will keep an eye for other cases.

**Comment by chirag127** [comment] 2022-08-16 14:51
> I cannot reproduce in this specific website (maybe because I don't have VPN option for india), will keep an eye for other cases.

you changed settings to mine?

**Comment by mneunomne** [comment] 2023-02-21 01:02
> you changed settings to mine? 

Yes, still cannot reproduce, closing for now.

**Closed by mneunomne** 2023-02-21 01:02 UTC
Labels: Cannot Reproduce
