### ISSUE TITLE
Can not run firefox version on branch merged1.12.2

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1030] opened 2017-05-02 02:10 UTC
Can not run firefox version on branch merged1.12.2
No error message from `tools/make-firefox.sh `
`tools/run-webext.sh` works fine

```
chenqianxun-2:adnauseam cqx931$ tools/run-ff.sh AdNauseamDev
*** AdNauseam::Firefox: Copying files
*** Packaging assets in dist/build/adnauseam.firefox/assets... done.
*** Generating locale files in dist/build/adnauseam.firefox... done.
*** AdNauseam::Firefox: Generating meta...
*** AdNauseam::Firefox: Package done.

JPM [info] Starting jpm run on undefined
JPM [warning] Using existing install.rdf. This file is usually auto-generated.
JPM [warning] Using existing bootstrap.js. This file is usually auto-generated.
JPM [info] Copying provided profile:
JPM [info]     /Users/cqx931/Library/Application Support/Firefox/Profiles/qjf4ajg0.AdNauseamDev
JPM [error] TypeError: Cannot convert undefined or null to object
/Users/cqx931/adnauseam
```
If I make-artifacts and try to load the xpi file, this is the error message from firefox
![image](https://cloud.githubusercontent.com/assets/3056154/25601488/19532bfe-2f1f-11e7-820f-49294422b68c.png)

**Comment by dhowe** [comment] 2017-05-02 02:29
I assume ublock works?
It may be some new requirement (perhaps in the manifest?) 
Can you test with an earlier FF version, to check if it is caused by an FF update or a code update ?

**Comment by dhowe** [comment] 2017-05-02 02:30
See also: https://blog.mozilla.org/addons/2017/04/05/compatibility-firefox-54/

**Comment by dhowe** [comment] 2017-05-02 02:37
Actually, look closer at this:

![image](https://cloud.githubusercontent.com/assets/737638/25602064/4d7ca03c-2f23-11e7-849d-b9e700f86cea.png)

**Comment by cqx931** [comment] 2017-05-02 02:39
uBlock 1.12.2 works fine. run-ff.sh on master branch still works so I think this should be caused by the merge

**Comment by cqx931** [comment] 2017-05-02 03:06
https://github.com/dhowe/AdNauseam/blob/master/tools/make-firefox.sh#L28
It is caused by this line of code. This line is removed in uBlock 1.12.2 and I kept this code from AdNauseam when I did the merge.
If I delete it, everything works fine again.

**Comment by cqx931** [comment] 2017-05-02 05:20
https://github.com/dhowe/AdNauseam/tree/merged1.12.2 fixed

**Comment by dhowe** [comment] 2017-05-05 04:13
I also see this error when I run tools/run-ff.sh.

Note that it is NOT present in merged1.11.4, but IS there in merged1.12.0

![image](https://cloud.githubusercontent.com/assets/737638/25733491/279ca2e8-318c-11e7-8b4e-08d2ff97f143.png)

**Comment by cqx931** [comment] 2017-05-05 05:13
It is caused by the syntax in install.rdf. Once I change the syntax back to the old one, tools/run-ff.sh works as expected.
https://github.com/dhowe/AdNauseam/commit/e8375f91cdfedc51029bb28d76bb1d9ca1f76f8f

**Closed** 2017-05-05 08:15 UTC
