### ISSUE TITLE
Resetting Every Time

### ISSUE THREAD

**Issue by siennk** [dhowe/AdNauseam#1314] opened 2018-01-05 22:38 UTC
### Describe the issue
This just started happening about maybe, a month ago? 
Every time I start my browser, the Adnauseum extension is reset. So all the settings I set, filters, whitelists, etc are are wiped clean and gone and the extension is blank like as if it was just installed.

When it first happened, I didn't think much of it. But now its happening EVERY SINGLE TIME.

### Your settings

- OS/version: Mac
- Browser/version: Firefox 55
- AdNauseam version: 3.3.403

I've tried using older Adnauseum versions but they just don't work. When I tried newer (WebExtensions) but it just stalled the browser to the point of freezing it. I let it run once with the WebExtensions versions, the browser remained frozen, computer heated up so badly, and the CPU/memory was ridiculously high.

**Comment by cqx931** [comment] 2018-01-10 06:52
Hi @siennk, thank you for reporting your issue.

I tried AdNauseam 3.3.403 on Firefox 55 and can't reproduce your issue.
All the settings, filters and whitelists work fine with me.
The latest AdNauseam 3.5.101 also works for me on Firefox 55.

What other extensions have you installed?
Have you tried it with the latest Firefox?

**Comment by dhowe** [comment] 2018-01-10 11:08
Can you try again with a new 'firefox profle' ?

**Comment by siennk** [comment] 2018-09-29 19:45
I tried a new profile and nothing is working. All setting, lists, specific filters are all gone every time I start Firefox.

**Comment by clarence112** [comment] 2020-09-13 00:55
I am also affected by this issue. I've had it happen on both Chrome and Firefox, on both Ubuntu 16.04 and Windows 8.1.

**Comment by Bulb4** [comment] 2020-11-04 12:23
Have the same problem. Windows 10, Firefox 82

**Comment by pbirnzain** [comment] 2020-12-15 13:20
I've had this too for a while (Fedora, Firefox 82).
After removing the extension, restarting firefox and re-adding the extension the problem seems to be gone.

**Comment by mneunomne** [comment] 2023-09-28 09:05
Seems to be outdated, closing unless reported once again.

**Closed by mneunomne** 2023-09-28 09:05 UTC
Labels: Needs-verification
