### ISSUE TITLE
Bug Report: 100% CPU Usage for Prolonged Periods

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1053] opened 2017-05-17 03:59 UTC
### Describe the issue
AdNauseam results in 100% CPU usage for prolonged periods of time and lock-up the browser for the same amount of time.

### One or more specific URLs where the issue occurs
http://www.theregister.co.uk

### Steps for anyone to reproduce the issue
- Middle-click on a link to open in a new tab.
- Wait 20-60 seconds before the browser becomes responsive again. The delay increases linearly if you manage to middle-click multiple links before the first link has fully loaded.

### Your settings

- OS/version: CentOS 7.x Linux 3.16.43
- Browser/version: Friefox 52.1.0
- AdNauseam version: 3.0.5
- Other extensions you have installed:
Ghostery, NoScript
- Location: UK

*ALL block lists are selected in AdNauseam configuration, full ad-clicking feature set enabled

from Gordan Bobic

**Comment by gordan-bobic** [comment] 2017-05-17 08:54
Configuration options of AdNauseam attached.
![settings](https://cloud.githubusercontent.com/assets/5469306/26146066/c69e5450-3ae6-11e7-98d3-21610d749f0c.png)
![filters](https://cloud.githubusercontent.com/assets/5469306/26146067/c6a1f786-3ae6-11e7-8295-34dfe30c86e6.png)

**Comment by gordan-bobic** [comment] 2017-05-17 08:55
As explained previously, the problem manifests at least as badly with Ghostery and NoScript disabled.

**Comment by cqx931** [comment] 2017-05-17 09:44
Just tested with the configuration options above:
AdNauseam 3.0.5
Friefox 52.1.0
Mac OS X Yosemite 10.10.5

CPU goes pretty high when many tabs are opened, but I didn't see an obvious delay of response time compared with no extension installed.  Still can't reproduce Lock-up issue with the browser.

**Comment by gordan-bobic** [comment] 2017-05-17 09:49
I noticed is that with the test site in question (http://www.theregister.co.uk), if I clear the history, kill all the processes and try again, the crippling CPU usage doesn't occur on articles I recently read. It only seems to affect the first click on each article.
I am purely theorizing here, but it could be that they only show particular ads the first time a page is visited, but not on subsequent visits. So on subsequent visits, the problem doesn't manifest. At first I thought it was related to toggling the "Don't click non-tracking ads" option, but I am now reasonably sure the manifestation of the high CPU usage and browser unresponsiveness only seems to happen the first (or first few) times a page is visited, and not on subsequent visits to the page (at least within a short period), even when history/caches are purged.

So it doesn't seem to affect pages that were recently opened, even if recent history is purged, but it does seem to affect pages that weren't opened before. It could be that some ads are only displayed once, and on subsequent loads they don't get sent, so the problem doesn't manifest.

**Comment by cqx931** [comment] 2017-05-17 12:09
This is very interesting. 
However, I still can't reproduce your issue if I only open new pages from http://www.theregister.co.uk.
Could you try to open the browser console(ctrl + shift + J) and see whether you could find any error message that is related to AdNauseam?

**Comment by gordan-bobic** [comment] 2017-05-17 12:56
I cannot see any errors specifically relating to AdNauseam. This is what the JS log says after opening 3 new documents:

TypeError: style is null  contentscript.js:537:15
TypeError: style is null[Learn More]  contentscript.js:537:15
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
uncaught exception: undefined  (unknown)
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: style is null[Learn More]  contentscript.js:537:15
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed May 17 2017 13:48:08 GMT+0100 (BST)
Full Message: Error: page-thumbnail:error
Full Stack: observe@resource://gre/modules/BackgroundPageThumbs.jsm:116:22
BackgroundPageThumbs._onCaptureOrTimeout@resource://gre/modules/BackgroundPageThumbs.jsm:305:7
Capture.prototype._done/done@resource://gre/modules/BackgroundPageThumbs.jsm:451:7
Capture.prototype._done@resource://gre/modules/BackgroundPageThumbs.jsm:471:7
Capture.prototype.notify@resource://gre/modules/BackgroundPageThumbs.jsm:428:5
  BackgroundPageThumbs.jsm:116
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
Use of nsIFile in content process is deprecated.  Content.js:26:17
Security wrapper denied access to property "chrome" on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.  contentscript.js:1105
TypeError: vAPI.prefs is undefined  parser.js:218:1
TypeError: docShell is null  backgroundPageThumbsContent.js:68:5
TypeError: style is null[Learn More]  contentscript.js:537:15
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: style is null[Learn More]  contentscript.js:537:15
TypeError: style is null[Learn More]  contentscript.js:537:15
TypeError: can't access dead object  webbrowser.js:2508:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: style is null[Learn More]  contentscript.js:537:15
TypeError: style is null[Learn More]  contentscript.js:537:15
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: can't access dead object  webbrowser.js:2508:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: can't access dead object  webbrowser.js:2508:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  container.html:14
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1
TypeError: can't access dead object  webbrowser.js:2508:1

**Comment by dhowe** [comment] 2017-05-18 02:36
@cqx931 should check these: 
```
TypeError: style is null contentscript.js:537:15
TypeError: style is null[Learn More] contentscript.js:537:15
```

**Comment by cqx931** [comment] 2017-05-18 04:54
A few findings about the error message `TypeError: style is null contentscript.js:537:15`:

1.This should be related to an existing bug in firefox, see [window.getComputedStyle() returns null inside an iframe with display: none](https://bugzilla.mozilla.org/show_bug.cgi?id=548397)
2. I can only reproduce this error message if I use an VPN from the UK. Possibly because I got different kinds of ad iframes in HK,and there are way more ads on the page in UK. When I browse from an server in UK, I do experience a longer page loading time. I don't think the browser really freezes but there are a few seconds when the page remains blank, and the page non-responsive if I leave too many new tabs to load.
3. I can still reproduce this using firefox 53

Another error I got quite frequently during my testing is: `gAdSets is undefined vault.js:921:21`, I will report back when I find out more about it.

**Comment by gordan-bobic** [comment] 2017-05-18 13:32
It is virtual certainty that the ad payload you get from HK is vastly different fromt he ad payload you get when you are in UK. You might also find that the ad providers are aware of your VPN provider's endpoint IP addresses and are thus restricting further what ads they will show you, which may be another thing getting in your way when reproducing the problem.

I find that the browser locks up to the point where the cursor doesn't even change when hovering over links by the time I have opened 4 new tabs in quick succession (middle click) with previously unvisited articles from the main page. At that point it can take anything up to a minute for FF CPU usage to drop below 105%, and it is only then that it wakes up starts being responsive again.

Note that I am using reasonably performant hardware, a Haswell i7 and a top of the range line Westmere Xeon. The issue manifests on both, although it is slightly more bearable on the Xeon, most likely due to bigger CPU caches on it.

**Comment by gordan-bobic** [comment] 2017-05-25 13:00
This CPU burn issue is becoming increasingly crippling. Have you been able to reproduce it yet? If you are struggling to reproduce it, there is a good chance that whatever ads are causing it are being issued from servers that are specifically not issuing them either to the country you are testing from and possibly to IP addresses that VPN traffic terminates from to avoid identification.

**Comment by dhowe** [comment] 2017-05-25 16:43
We have not been able to reproduce it as yet, however I will try a few more tests tomorrow. Thanks for your patience...
Note also that v3.3.331 has finally been approved by mozilla, so can be installed the usual way (though I don't imagine this will affect the problem in this ticket)

**Comment by dhowe** [comment] 2017-05-31 13:56
I cannot recreate this on v3.3.331

OS/version: Ubuntu 14.04.5 LTS 3.13.0-119-generic
Browser/version: Firefox 53.0.3
AdNauseam version: 3.3.331
Other extensions: None
Location: HK

![screenshot from 2017-05-31 21 48 23](https://cloud.githubusercontent.com/assets/737638/26635305/edff0826-464b-11e7-8ae5-cbb13a963983.png)

**Comment by gordan-bobic** [comment] 2017-05-31 14:14
I only see one theregister.co.uk tab in there, and only the main landing page. Open a few articles in quick succession in new tabs (middle click), and do it via a VPN terminated in UK.

If you still cannot reproduce it, perhaps I could provide a remote VNC session you could use to reproduce it?

**Comment by dhowe** [comment] 2017-06-01 03:13
can you provide a vpn or web proxy?

**Comment by gordan-bobic** [comment] 2017-06-07 17:03
I will look into setting up an authenticated proxy for you, but for now I have a new piece of information that seems pertinent:

1) If I use my regular FF session (persistent Google login, and possibly others that I use every day), the CPU burn happens as described above.

BUT:

2) If I open a new private browsing tab in FF - it doesn't.

**Comment by gordan-bobic** [comment] 2017-06-08 11:18
Additionally, when the lock-up / CPU depletion happen, it looks like no ads get clicked:
![adn2](https://user-images.githubusercontent.com/5469306/26926088-15bcbed2-4c44-11e7-9fff-deeaf6a06a2a.png)

When accessed in a private browsing window, 0 ads are detected. In a non-private browsing window, 8 ads are detected, huge amount of CPU is burned, browser locks up for a minute or so, and no ads are clicked by AdNauseam.

This is starting to look very much like an anti-AdNauseam counter-measure.

**Comment by andrewpapsujko** [comment] 2017-07-11 07:09
I have the same behavior as @gordan-bobic described above. When i open two articles on this site using middle mouse click Firefox gets stuck for a twenty seconds. At this moment, system monitor shows 100% CPU used by Firefox.

OS/version: Ubuntu 16.04 LTS
Browser/version: Firefox 54.0
AdNauseam version: 3.3.331
Other extensions: None
Location: RU

Also i can note that this is not the only site where i saw this behavior.

**Comment by gordan-bobic** [comment] 2017-07-11 09:35
As another few interesting data points:
1) The problem ceases to manifest in private browsing mode, presumably because some cookie somewhere is no longer accessible, and therefore the offending ads that cause the behaviour described in this ticket don't get served up.
2) I have yet to be able to get the problem to manifest on Chrome, even though I switched to using Chrome shortly after reporting this bug, because FF was becoming unusable.

**Comment by jadenPete** [comment] 2017-08-12 21:10
Can verify, it locks up a ton.

**Comment by dhowe** [comment] 2017-08-12 21:41
Do any other devs have access to a ubuntu machine or vm? (I don't for the next 2 weeks...)

**Comment by duane** [comment] 2017-08-21 15:53
I don't have information to add, but it seems to be happening on FF 54.0.1 and macos 10.12.6 for me as well. Removing ad nauseum resolved the mysterious hangs in my web browser—which is unfortunate, because this is my favorite extension!

**Comment by jadenPete** [comment] 2017-08-30 05:24
This is seriously becoming an issue, I find myself disabling AdNauseam a lot because the delay is too much to deal with.

**Comment by dhowe** [comment] 2017-08-30 06:29
I will look it into this ticket this week...

**Comment by jadenPete** [comment] 2017-08-30 06:52
Thank you so much!

**Comment by fche** [comment] 2017-09-21 00:32
Encountered similar-sounding phenomena here, when targeting a complex webapp site like facebook.  firefox's 'element inspector' identified many large (multi-second) garbage collection delays during the rendering of the pages.  With adnauseam extension disabled, those delays seem to go away.

**Comment by dhowe** [comment] 2017-09-21 01:25
Can someone try to recreate this using the [most recent release] (https://github.com/dhowe/AdNauseam/releases) ?

**Comment by jadenPete** [comment] 2017-09-21 03:08
Just installed it, I'll let you know if I get the issue again.

**Comment by dhowe** [comment] 2021-06-22 16:37
closing

**Closed by dhowe** 2021-06-22 16:37 UTC
