### ISSUE TITLE
Merge up to uBlock 1.12.2

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1025] opened 2017-05-01 05:35 UTC
one release at a time, following the these [instructions](https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-do-i-merge-in-upstream-ublock-code)

**Comment by cqx931** [comment] 2017-05-01 12:17
Please check: https://github.com/dhowe/AdNauseam/tree/merged1.12.2
I don't see any obvious bug that is caused by this merge so far.
Many changes have been made for Firefox webext, do we need to test anything on that yet?
Other than that, the branch merged1.12.2 is ready for testing and then merged into master branch.

**Comment by dhowe** [comment] 2017-05-01 17:27
we need to check that firefox-ext works as expected for adn as well

**Comment by cqx931** [comment] 2017-06-13 03:48
done and close

**Closed** 2017-06-13 03:48 UTC
Labels: PRIORITY: Low
