### ISSUE TITLE
AdNauseam not working in Youtube

### ISSUE THREAD

**Issue by q-l-p** [dhowe/AdNauseam#1658] opened 2020-05-10 22:33 UTC
My Firefox updated to version 76.0.1. Then  AdNauseam stopped working. Mind numbing ads on YouTube started to flood my screen. I then installed AdNauseam on Google Chrome, to see what happens – and it works like a charm.

The official issue tracker for uBlock Origin is at:

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps for anyone to reproduce the issue
In my case, an older version of Firefox updated to latest version, which is 76.0.1 (64-bit). After this update, AdNauseam can't hide ads on YouTube. 

### Your settings

- Windows 7 Ultimate 64-bit
- Firefox 76.0.1 (64-bit)
- AdNauseam v3.9.104 uBlock Origin v1.20.0 
- No other extensions installed.

##### Your filter lists
Default filter lists

### Your location/country
Bucharest, ROMANIA

**Comment by cqx931** [comment] 2020-05-10 22:39
I just take a quick look at the latest Firefox. AdNauseam seems to still work fine with sites with google ads at least. Might just be youtube only? Please provide a URL and a screenshot to help us reproduce the issue.

**Comment by cqx931** [comment] 2020-05-14 14:21
@q-l-p could you please provide a link where you see Youtube ads? I was not able to reproduce this issue on Youtube yet.

**Comment by freesomebody** [comment] 2020-05-14 15:14
I'm not the user who initially reported this, but I'm also a Firefox user with AdNauseum and I've noticed this issue as well. I can provide an example of where I've seen this.

Link: https://www.youtube.com/watch?v=_jQSxOCJZB0

Screenshot showing I got an ad playing from visiting above link: 
<img width="1431" alt="Screen Shot 2020-05-14 at 11 01 37" src="https://user-images.githubusercontent.com/23124658/81951348-0dc6ec80-95d3-11ea-98f6-08666db35b61.png">


I can say that I don't get an ad 100% of the time I visit a particular link. Sometimes they show up, sometimes they don't. I have noticed that I see it more often when I visit videos displayed from my front page or when I visit related videos in the side (and for reference I do stay logged in), but that might just be luck of the draw from going to a lot of vids.

Something else I've noticed -- I think this is from the past month or so -- is that sometimes when checking a vid, the page would load but in the video field it would just display a playback error message with ID. After a few seconds, the actual video would load up and play normally. I suspect that YT has done/did some tweaking to get around this, and initially it was able to mostly load up the ad, but something on AD's side blocked the video itself from playing. A few days ago, I now am starting to see the ads load and play on YT. I wasn't keeping on track with this so I can't be more specific with dates, unfortunately.

**Comment by cqx931** [comment] 2020-05-14 20:33
Hi @freesomebody! Thank you so much for the example! I tried it on both chrome and firefox(76) from both mac and windows, but unfortunately, I still couldn't reproduce it.

<img width="1119" alt="Screenshot 2020-05-14 at 4 19 33 PM" src="https://user-images.githubusercontent.com/3056154/81981731-b63e7600-95fe-11ea-93ea-d1106950fe27.png">
Could you open the logger before you go to a youtube video, then once the ad is loaded, take a screenshot of this popup window after clicking on the loggerStats icon :
<img width="30" alt="Screenshot 2020-05-14 at 4 31 58 PM" src="https://user-images.githubusercontent.com/3056154/81982866-7082ad00-9600-11ea-83a6-735fa7976ed0.png">



To open the logger, please first go to the menu by clicking the AdNauseam icon, then click on the "u" button at the bottom right corner. From there, the third icon in the first raw should bring up the logger.
![Screenshot 2020-02-24 at 2 26 04 PM](https://user-images.githubusercontent.com/3056154/81982628-24d00380-9600-11ea-8cc7-6920dc56b000.png)

**Comment by cqx931** [comment] 2020-05-18 14:38
Another example from email:

- Video it first started happening on: https://www.youtube.com/watch?v=WewhSliqWFk
- Settings: http://prntscr.com/shnbht
- Windows 7 Ultimate SP1
- Firefox 76.0.1 
- Latest AdNauseam, 3.9.104 (At least that's what Firefox tells me when I attempt to update it via the settings page)
- Extensions: http://prntscr.com/shn9lw http://prntscr.com/shn9xd
- No filters in use
- US with US IP address

**Comment by freesomebody** [comment] 2020-05-19 04:26
@cqx931 -- sorry for the delay as I've been rather occupied, though I was able to grab a couple of caps of the logger:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/23124658/82284171-61845d80-9966-11ea-9973-02f337be9200.png">

<img width="1431" alt="Screen Shot 2020-05-19 at 00 20 19" src="https://user-images.githubusercontent.com/23124658/82284243-8bd61b00-9966-11ea-8ef5-ae7e3998d86a.png">

(For reference the vid I saw this ad was https://www.youtube.com/watch?v=mvjP5BSbNGk&t=245s -- the timestamp in the URL is because I've previously seen this vid and stopped partway -- but again, I don't see ads 100% of the time I visit any particular video.)

These images are from the same video opened in a blank tab. I went and got a second cap as there was a tad bit more logging after my initial grab.

Forgot to mention my own settings, but I'm using Firefox 76.0.1 on Mac OS Catalina 10.15.4, in the US with US IP and default filters. I strongly suspect this is something from Youtube's side, though, since I've been on this browser version since it came out (May 8) and I didn't start to see ads until
 a few days after.

**Comment by ShinkoNet** [comment] 2020-06-10 04:29
Also happening for me on the same version but on Chromium. The skip button is gone so all the ads are unskippable.

**Comment by cqx931** [comment] 2020-06-10 11:40
Hi @ShinkoNet, can you try updating AdNauseam filters and see whether that will fix the issue for you?

**Comment by ShinkoNet** [comment] 2020-06-12 05:03
Yeah, the filters are up to date. I see it's being addressed in #1671 though

**Comment by dhowe** [comment] 2020-06-12 05:04
![image](https://user-images.githubusercontent.com/737638/84466970-4a0e6b00-acad-11ea-87eb-9fc0d9488cbf.png)

**Comment by pythonInRelay** [comment] 2020-06-14 21:54
> 
> 
> ![image](https://user-images.githubusercontent.com/737638/84466970-4a0e6b00-acad-11ea-87eb-9fc0d9488cbf.png)

Hey @dhowe could you stop posting this everywhere, it is incredibly uncivil and entirely impractical as it will not get anything solved any faster.

**Comment by pythonInRelay** [comment] 2020-06-14 21:57
> 
> 
> _image_

Hey @dhowe I know you work on this project but I don't understand why you are posting this everywhere without any context at all.

**Comment by dhowe** [comment] 2020-06-15 04:42
I posted this image in exactly two relevant tickets as further evidence of the specific problem we were having trouble recreating. Thanks for your feedback.

**Comment by cqx931** [comment] 2020-06-18 14:56
close for now as we have addressed this in the new release

**Closed by cqx931** 2020-06-18 14:56 UTC
