### ISSUE TITLE
webRequestInternal.eventHandled

### ISSUE THREAD

**Issue by Novablox** [dhowe/AdNauseam#2450] opened 2023-11-03 17:22 UTC
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension.
- [X] AdNauseam uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Error in event handler: TypeError: Error in invocation of webRequestInternal.eventHandled(string eventName, string subEventName, string requestId, integer webViewInstanceId, optional webRequest.BlockingResponse response): Error at parameter 'response': Error at property 'responseHeaders': Invalid type: expected webRequest.HttpHeaders, found object.

### Screenshot(s)

![jjjjj](https://github.com/dhowe/AdNauseam/assets/60800487/e5a57839-e480-4867-a765-8d1844b3dba7)

### Configuration

 default

**Comment by mneunomne** [comment] 2023-11-25 01:42
I verify this is occurring, but I am currently not sure where this error is coming from... it's to find since I can't trace it to a specific function in adn. Perhaps need to rollback and see when this has started.

**Comment by mneunomne** [comment] 2023-11-25 01:49
I can confirm this has started in v3.17.9b1 version, trying to find out why

**Comment by mneunomne** [comment] 2023-11-25 02:49
Seems like it is being caused here:

https://github.com/dhowe/AdNauseam/blob/ae3ade5987b3a4671fa82a1e2ec712d2ac968e6b/src/js/traffic.js#L811-L813

and the function:

https://github.com/dhowe/AdNauseam/blob/ae3ade5987b3a4671fa82a1e2ec712d2ac968e6b/src/js/traffic.js#L1262-L1288

**Comment by mneunomne** [comment] 2023-11-25 02:55
This commit:

https://github.com/dhowe/AdNauseam/commit/5ebdbf3e24393560156fdcd931e31f901471f7f3

**Comment by mneunomne** [comment] 2023-11-25 15:57
Fixing with https://github.com/dhowe/AdNauseam/pull/2471
The issue was how the `adnOnHeadersRecieved` function was being returned

```
return {responseHeaders: headers}
```

instead of

```
return responseHeaders
```

**Comment by mneunomne** [comment] 2023-11-26 02:29
Fixed, closing

**Closed by mneunomne** 2023-11-26 02:29 UTC
Labels: Bug
