### ISSUE TITLE
Ads on DNT pages should be labeled in menu, vault, and vault-inspector

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1168] opened 2017-09-09 05:41 UTC
Should get green color highlighting, and instead of 'Not yet visited' it should say something like: 'allowed for DNT site'.

This requires two parts:
- [x] A) ads items given the class 'dnt-allowed' in menu and vault  (@dhowe)
- [x] B) update css and text for visual display (@dhowe)
- [x] C) tweak visual display (@mushon)
- [x] D) translate new string (@cqx931)
- [x] E) link to FAQ in translated string (@cqx931)
- [x] F) add to release testing (@cqx931)

![image](https://user-images.githubusercontent.com/737638/30237446-068f0dac-9500-11e7-89b0-27f48a197e17.png)

**Comment by dhowe** [comment] 2017-09-09 05:43
Similarly, we might mark these ads somehow in the vault itself:

![image](https://user-images.githubusercontent.com/737638/30237454-497eef06-9500-11e7-8a1f-ae951a0f7320.png)

**Comment by dhowe** [comment] 2017-10-15 06:01
Also need to handle 'no-visit' ads (ads which are not to be visited b/c of frequency slider setting)

**Comment by dhowe** [comment] 2017-10-15 06:07
Should be done in menu -- please adjust color/visual-design

![screen shot 2017-10-15 at 2 06 48 pm](https://user-images.githubusercontent.com/737638/31582285-21dd0a22-b1b2-11e7-8137-ce625c2c65b1.png)

**Comment by dhowe** [comment] 2017-10-15 06:42
Should be done in vault -- please adjust color/visual-design

![image](https://user-images.githubusercontent.com/737638/31582494-1bcca296-b1b7-11e7-97d0-c2a3e5cbaf9f.png)

**Comment by dhowe** [comment] 2017-10-15 06:53
@cqx931 we need to translate the new string 'adnAllowedByDNT'
Also, is it possible to link the text for that string to the FAQ on DNT ?

**Comment by dhowe** [comment] 2017-10-15 07:08
@cqx931 we need to translate the new string 'adnAllowedByDNT'
Also, is it possible to link the text for that string to the FAQ on DNT ?
Also, we need to add checking of DNT visuals (menu/vault) to release testing...

**Comment by mushon** [comment] 2017-10-22 10:06
@dhowe this looks good to me, the use of the 'allowed' green color is in line with the rest of the color-coding logic. Do you think there is anything else I should review / consider?

**Comment by dhowe** [comment] 2017-10-22 10:08
1. also need a visual representation of 'no-visit' ads (ads which are not to be visited b/c of frequency slider setting)
1. the green color for DNT-ads doesn't look quite right to me

**Comment by mushon** [comment] 2017-10-22 10:17
another way we could go about this is to keep it to blue / purple / red (pending / clicked / failed) and add a badge or animation on those pending marking why they won't be attempted. @dhowe what say you?

**Comment by dhowe** [comment] 2017-10-22 10:20
either way works for me (your call), but note that we are talking about 3 different locations: menu, vault, and vault-inspector

**Comment by dhowe** [comment] 2017-10-22 10:29
Actually there may be more cases to be considered.
What if user settings say that DNT ads should not be hidden, but should be clicked?
It should be green in the menu, but purple or red in the vault/inspector...

**Comment by mushon** [comment] 2017-10-22 10:54
I suggest we drop the green labeling of ads and stick to action labeling with a note when it informed by a setting exception (like being unclicked due to DNT or frequency setting). We would represent this similarly in the ad vault's inspected ad, and we should consider whether it needs indication before the drill in.
![popup-notifications-status-note](https://user-images.githubusercontent.com/27123/31861129-10e264a0-b730-11e7-8b75-4d5bb5f01635.png)

**Comment by dhowe** [comment] 2017-10-22 11:09
We need to be sure we are considering the full set of cases, and any possible confusions that might arise.
For example, we don't want an ad marked as 'pending' (now blue), if we have no intention to ever visit it.
So need to make it clear (in the menu) why any ad is visible (DNT labelling), and similarly clear (in the vault) why any ad is not visited (either due to DNT or frequency).

Note also that the frequency might be quite high (say, 95%) and an individual ad might still be marked as never to be visited, so the labelling above (click-frequency: low) would be misleading...

The set of options are (I believe):

* Clickability: visitable (pending/visited/failed) || DNT-skipped || frequency-skipped 
* Visibility: hidden || DNT-visible

Which gives 6 distinct cases (or 10 if you include the visitable options)

**Comment by mushon** [comment] 2017-10-22 11:17
I agree though I would suggest a different categorization:
* State: unclicked (pending/DNT-skipped/frequency-skipped) || visited || failed

Additionally, I am not sure we should refer to visibility, as it refers only to the ads display and does not change the data we generate.

**Comment by dhowe** [comment] 2017-10-22 13:30
>I agree though I would suggest a different categorization:
* State: unclicked (pending/DNT-skipped/frequency-skipped) || visited || failed

Hmmm... 
So we've gotten several bug reports already of ads "stuck" in pending state... How would the user differentiate between an ad that hasn't yet been clicked, and one that will never be clicked ?

> Additionally, I am not sure we should refer to visibility, as it refers only to the ads display and does not change the data we generate.

We need to make it clear to users that a visible ad is showing up for good reason (otherwise, for most users, it appears to be a bug). The easiest way I can think to do this is to show it in the menu ("this ad was in fact detected, but was not hidden b/c of DNT"). Another option could be a mouse-over or outline on the ad itself, but this is a) more work and b) potentially distracting.

**Comment by mushon** [comment] 2017-10-22 14:49
Another attempt:
![popup-notifications-status-note](https://user-images.githubusercontent.com/27123/31863099-57db5e40-b751-11e7-89fa-ca56b2bdcef0.png)

**Comment by dhowe** [comment] 2017-10-22 23:53
This is potentially better, though slightly confusing in that they icons look like eyeballs, which makes me think of visibility, while they actually refer to clicks. And if clicking was disabled, these would all then need to disappear I guess.

But lets says this was the menu (I think we would need to change the notification to say that 'This page respects DNT, Ads are not hidden' instead of what we have now), how do we show this info in the vault ?

**Comment by mushon** [comment] 2017-10-23 06:00
I actually meant this as an icon that represents both visibility (eye on/off) and clicking status (unclicked / clicked / failed - via color) and additional note via text.

As for the vault, let’s decide on the menu first. I think it is the more important view as it is more granular and contextual. I think we can keep the visibility and click status notes to the drill-in / inspect mode.

**Comment by dhowe** [comment] 2017-10-24 10:55
I see -- this was a bit confusing b/c you would never have visible and non-visible ads in the same menu display.

This is good, but I would still argue for the 4 colors we have now for pending/visited/failed/skipped

**Comment by mushon** [comment] 2017-10-25 10:29
OK.
So here are the options. The one not mentioned here is the one for "FAILED" or should it be "FAILED 3 TIMES" / "FAILED 3 CLICKS"?
![popup-notifications-status-note](https://user-images.githubusercontent.com/27123/31994096-230f4bac-b988-11e7-94c6-15ca2752ac7d.png)

**Comment by mushon** [comment] 2017-10-25 10:32
With skipped being green, we should avoid using green for other things like estimated cost in the vault (which I suggest should be white or light gray instead).

**Comment by dhowe** [comment] 2017-10-27 15:45
How about?  'FAILED: 3 ATTEMPTS'

Also, the outline of the ads should match the color of the eyeball, yes?
So the first two ads above would be outline in green...

Your call on color for estimated cost, though I think it should attract the eye strongly, as it does now

**Comment by dhowe** [comment] 2017-11-04 04:42
status @mushon ?

**Comment by mushon** [comment] 2017-11-04 04:56
I hope to make the final design changes tomorrow and then post the assets and all. I’m afraid I won’t be able to implement them in html/css any time soon. (More on that via chat)

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by cqx931** [comment] 2017-11-19 19:19
@dhowe what is "link to FAQ in translated string"?

**Comment by dhowe** [comment] 2017-11-19 22:16
A link to the FAQ in the text (for example, for DNT)

**Comment by cqx931** [comment] 2017-12-01 00:29
Please check: https://github.com/dhowe/AdNauseam/pull/1291
1.Link to DNT FAQ
![image](https://user-images.githubusercontent.com/3056154/33460387-f1573422-d5fb-11e7-9d9c-1dd3f325c6f1.png)

2.Status icons update
Question:
Currently I am checking the DNT visibility by checking
1.whether the ad.pageURL is from DNT domain
2.the current DNT visible setting
However, if the user change the DNT setting and go back to the DNT page without refreshing the page, the result would not be accurate.
Another method would be saving this info when the ad is created, but I'm not sure whether this info should go into the ad data

**Comment by dhowe** [comment] 2017-12-01 04:27
1. (Link to DNT FAQ) Can we make the "?" icon smaller, and a bit higher (like a superscript) ?

2.  What case are you talking about for status icon update -- the menu, yes ? If so, then wouldn't the menu close and refresh when the user returns to the DNT page?  And wouldn't the ad.pageURL be the same for every ad in the menu (assuming there ads are from the current page, and not only 'recently found ads', which probably should not show visibility anyway) ? Do we have a spec for this behavior ?

**Comment by cqx931** [comment] 2017-12-07 16:10
If the user changes the DNT setting(Ex: from showing DNT to hiding DNT ads) without refreshing the page. Although the current setting is on "hiding DNT ads", the dnt ads are not hidden because the user hasn't refresh the page. So the issue is that the menu would be refreshed when the user returns to the DNT page but not the page itself.

**Comment by dhowe** [comment] 2017-12-07 17:36
as discussed offline, updates on settings changes should be a separate ticket for a future release (pls add the ticket under 'next tasks')

**Comment by cqx931** [comment] 2017-12-07 17:45
**Visibility and outline rules**

Visibility status considers:
- General hiding setting
- DNT visible
- Ignores "toggle cosmetic rules" in uBlock menu

----------------------------

**Menu**
Outline and visibility status

- Pending (visible/hidden)
- DNT allowed (visible/hidden)
- Visited (visible/hidden)
- Failed (visible/hidden)

**Vault**
Outline only

- Pending
- DNT allowed
- Visited
- Failed

**Logger**
(There is no visibility/outline issue in the current spec...)
See https://github.com/dhowe/AdNauseam/issues/389

**Comment by cqx931** [comment] 2017-12-08 00:55
Please check:
https://github.com/dhowe/AdNauseam/pull/1293
But I'm not hundred percent sure about the occasion when "Clicking disabled" should be displayed. 
In the implementation above, if clicking is disabled, all "Pending" and "Skipped" would be "SKIPPED: Clicking Disabled:".

**Comment by cqx931** [comment] 2017-12-09 17:29
Do we still want to show text about the cases, when ads visiting are skipped because user has already visited it?
https://github.com/dhowe/AdNauseam/issues/958

**Comment by dhowe** [comment] 2017-12-10 13:59
Yes, I suppose we need to, otherwise there would no way to know why that ad wasn't being visited

**Comment by cqx931** [comment] 2017-12-14 18:50
Added"Clicked by user"
https://github.com/dhowe/AdNauseam/commit/020cc25e088431fad32dcc3ac34221ff13e6c612

**Comment by cqx931** [comment] 2017-12-14 18:56
Release testing:

Test ad clicking status (Menu and Vault)
If an ad is not visited because of the clicking frequency, the ad should be marked as "SKIPPED: Click frequency "
If an ad is not visited because the user has already clicked it, the ad should be marked as "SKIPPED: Clicked by user "
When an ad is collected from a dnt site (Ex:duckduckgo), the ad should be marked as "SKIPPED: DNT allowed" ("Allowed via Do Not Track Policy" in vault)
When clicking is disabled, all ads that are not "visited" or "failed" should be marked as "SKIPPED: Clicking Disabled:"

**Comment by cqx931** [comment] 2017-12-21 06:07
@dhowe, can this one be closed?

**Closed** 2017-12-21 16:15 UTC
Labels: Enhancement, Needs-design, PRIORITY: High
