### ISSUE TITLE
Answer reviews/critiques on Mozilla addon page

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#858] opened 2017-02-15 06:03 UTC
draft response for issues raised on this [page](https://addons.mozilla.org/en-US/firefox/addon/adnauseam/) below (if we find any valid issues, pls create new ticket)

**Comment by cqx931** [comment] 2017-02-28 13:51
![image](https://cloud.githubusercontent.com/assets/3056154/23407519/4a03ab62-fdff-11e6-9c5f-407373218b99.png)

Hi Serhii,

Thanks for reporting the issue. We used to have some issues on facebook related sites, but the problem should be fixed by now.
I just checked on messager.com and everything looks ok.
Please make sure that your adnauseam filter is up to date and check whether the problem is solved for you as well.

You can update your adnauseam.txt file with the following steps:
1.Go to AdNauseam Settings page (from Menu), then open the 3rd-party-filters panel
2.Click 'purge-all-caches' - 'apply changes' - 'update now'
3.Reload the page on which you saw the problem

**Comment by dhowe** [comment] 2017-02-28 23:26
Good, please enter on mozilla site, and continue (here) responding. Make each response a separate comment and I will give it a thumbs up when Ok'd to post on mozilla.

**Comment by cqx931** [comment] 2017-03-01 01:44
![image](https://cloud.githubusercontent.com/assets/3056154/23442031/13c6ed68-fe61-11e6-9ade-d036fc753079.png)

AdNauseam is built based on ublock. Most adblockers work via a combination of blocking and hiding strategies. Requests for some ads are blocked outright, while other Ads(mostly text ads) are first downloaded, then made invisible on the page. In AdNauseam, we are allowing those requests that generate visual ads, because we want to collect the ads and be able to click them afterwards.

The number you see from the ublock badge indicates the amount of requests ublock blocked for you and has nothing to do with the amount of ads. In AdNauseam, the badge number means how many ads adnauseam successfully collected from the page. More ads could actually be hidden, but are not collected due to the format. (video ads, dynamic animated ads, etc.)

I hope this answers your question. Please checkout our [wiki page](https://github.com/dhowe/AdNauseam/wiki/FAQ) if you want to know more about how adnauseam works.

**Comment by cqx931** [comment] 2017-03-01 03:38
![image](https://cloud.githubusercontent.com/assets/3056154/23444984/5f5f9b3c-fe73-11e6-85e4-2b412ed05690.png)

I just checked the "block element" feature with right-click menu in Adnauseam, and it works for me.
May I know the exact case when this feature fails for you?

**Comment by cqx931** [comment] 2017-03-01 08:34
This is a bit strange...According to this ticket, block element should not work with 3.0.5...
I was able to get it work, but it did broke some times, so I think it's better that I ask the user to check the latest release when it is out.
https://github.com/dhowe/AdNauseam/issues/820

**Comment by cqx931** [comment] 2017-03-09 08:25
![image](https://cloud.githubusercontent.com/assets/3056154/23741625/5bc40e14-04e4-11e7-873e-7ed5b46fd322.png)

Translated from Russian:

> Useless addition - blocks on mail.ru games instead of advertising. Advertising does not block.


Please go to Settings - 3rd-party filters - Languages and check Russian ad-blocking filters. This should block the ads on mail.ru.
I also checked mail.ru and was not able to find a case when Adnauseam blocks a game from it. If you could provide me with an exact case, I could try to solve it.

**Comment by cqx931** [comment] 2017-03-09 08:26
![image](https://cloud.githubusercontent.com/assets/3056154/23741744/04dfc8e4-04e5-11e7-9bcb-53443807a6a5.png)
Not sure about this 100% CPU consuming case...

**Closed** 2017-09-22 13:45 UTC
