### ISSUE TITLE
Recommendations on DeviantArt posts do not show when adblocking is enabled.

### ISSUE THREAD

**Issue by OdysseyDutchAngle** [dhowe/AdNauseam#2365] opened 2023-08-01 05:56 UTC
### Describe the issue

*NOTE: if you are having a problem where ads are not collected, please FIRST TRY to create a new new Firefox profile as described [here](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile). A corrupt Firefox profile is the most common cause of this issue.*

After clicking on a post on DeviantArt, the side panel that shows recommendations always gets replaced by an error message saying "E_GURU_MEDITATION; Something's gone wrong on our end." This happens on both the Active and Strict modes, but does not happen when the addon is disabled on the website. 

### Screenshot in which the issue can be seen

![image](https://github.com/dhowe/AdNauseam/assets/42396926/657d89ad-d73f-4c71-b7a0-33955a006020)
![image](https://github.com/dhowe/AdNauseam/assets/42396926/94c09ad7-a425-4068-971a-2401fe322686)

### Steps for anyone to reproduce the issue

1. Install and enable the addon.
2. Head to [DeviantArt](deviantart.com) and click on any post/deviation.
3. If error does not appear on the right side of the page, scroll down until recommendations disappear and error appears on top-right.

### Your settings

- OS/version: Windows 10 Home 22H2
- Browser/version: Firefox 115.0.3 (64 bit)
- AdNauseam version: v3.17.0
- Other extensions you have installed:
Add-ons Search Detection
AdNauseam
Alternate Player for Twitch.tv
Augmented Steam
ChatReplay
ClearURLs
Cultivate: Shop Local, Shop Deals, Shop Smart
Dark Reader
Deviant Love
DeviantArt Filter
Don't Accept image/webp
Don't track me Google
DownThemAll!
Duolingo Boost
Enhancer for YouTube™
FrankerFaceZ
Greasemonkey
h264ify
Honey
I don't care about cookies
Imagus
LocalCDN
minerBlock
Mouse Dictionary
Privacy Badger
Privacy Possum
Read Aloud: A Text to Speech Voice Reader
Return YouTube Dislike
Search by Image
Tab Stash
TimerForge
Tranquility Reader
Truffle
Tumblr Savior
Twitch Adblock
Universal Bypass
WebChatGPT: ChatGPT with internet access
- AdNauseam settings: Mostly default, except for ads that were zapped/picked. Zip file with settings if needed: [AdNauseam_Settings_and_Ads_Export_7.31.2023.10.47.13PM.json.zip](https://github.com/dhowe/AdNauseam/files/12225060/AdNauseam_Settings_and_Ads_Export_7.31.2023.10.47.13PM.json.zip)

**Comment by mneunomne** [comment] 2023-09-18 12:02
<img width="1274" alt="Screenshot 2023-09-18 at 14 02 17" src="https://github.com/dhowe/AdNauseam/assets/4967860/3dc74fc3-f15f-45d2-bde2-acdc26ec9384">

Couldn't reproduce. Maybe it was an issue with the third-party filters which was fixed already?

**Comment by dhowe** [comment] 2023-09-19 03:45
closing for now, please re-open if this recurs

**Closed by dhowe** 2023-09-19 03:45 UTC
Labels: Needs-verification, Page Broken, Cannot Reproduce
