### ISSUE TITLE
AdNauseam picks up Facebook Profile Pics

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1654] opened 2020-04-20 21:20 UTC
People you may know:
![image](https://user-images.githubusercontent.com/3056154/79800537-65eb3580-832a-11ea-9b63-0bb5a22b45a6.png)

So far I can't reproduce this issue on chrome or firefox, only on Opera.

Our current method of filtering out FB profile pics is:
https://github.com/dhowe/AdNauseam/blob/master/src/js/adn/parser.js#L214

An example of profile pic image src
`https://scontent-bos3-1.xx.fbcdn.net/v/t1.0-1/c0.0.450.450a/1915424_520313725296_2589331_n.jpg?_nc_cat=107&_nc_sid=dbb9e7&_nc_ohc=Bu-MblO8O3sAX_KqdWM&_nc_ht=scontent-bos3-1.xx&oh=dd10e5ec4515b14b4625a7935bf99c7a&oe=5EC4E8AE`

An example of ad image src:
`https://scontent-bos3-1.xx.fbcdn.net/v/t45.1600-4/cp0/q75/spS444/p296x100/93114868_6163011065262_8109278698756112384_n.jpg?_nc_cat=104&_nc_sid=67cdda&_nc_ohc=26g-_ddV9eEAX-qZ7_N&_nc_ht=scontent-bos3-1.xx&oh=91f17c8e62a03ff72a13f361053fbfd7&oe=5EC4E02B`

**Comment by cqx931** [comment] 2020-04-20 21:44
These profile images are served in different image sizes and they are larger than the previous standard we set up for profile pics(<150).

Both the sizes and the src URL makes these profile pics hard to distinguish from real ad images(there are square shape ad images).

**Comment by cqx931** [comment] 2020-04-20 21:49
Another method would be to let AdNauseam parser stop processing rules that we can identify with Facebook's 'People you may know' section. 
The current method will still slow down the browser by parsing over 20 dom structures at the same time even if it doesn't collect the image at the end.

**Comment by mneunomne** [comment] 2023-02-21 01:22
Was not able to reproduce since long time, closing.

**Closed by mneunomne** 2023-02-21 01:22 UTC
