### ISSUE TITLE
Facebook: This post is private and has not been collected

### ISSUE THREAD

**Issue by Wolfsbane** [dhowe/AdNauseam#2309] opened 2023-03-04 02:29 UTC
When viewing Facebook posts from the top when viewed disappear and the message "This post is private and not collected" shows for one then multiple posts then the message disappears and the stories and "What's on your mind, ...?" sections are left with no posts below. Unfortunately the "This post is private and has not been collected" can not be screenshotted as it disappears as stated above in up to 10s.

AdNauseam: 3.16.2b0
Firefox: 112
filterset (summary): 
  network: 285037
  cosmetic: 334097
  scriptlet: 42669
  html: 1109
listset (total-discarded, last-updated): 
  removed: 
    eff-dnt-whitelist: null
  added: 
    adguard-generic: 68255-6525, 2d.15h.49m
    adguard-mobile: 8735-18, 2d.15h.50m
    adguard-spyware: 39193-14991, 2d.15h.49m
    adguard-spyware-url: 928-5, 2d.15h.51m
    block-lan: 44-0, 11d.2h.13m
    curben-phishing: 43364-13, 11h.27m
    curben-pup: 194-0, 11h.27m
    adguard-annoyance: 64466-7094, 2d.15h.48m
    adguard-social: 19941-1006, 2d.15h.48m
    fanboy-thirdparty_social: 69-0, 2d.1h.7m
    fanboy-annoyance: 82103-68539, 2d.1h.7m
    fanboy-cookiemonster: 45872-309, 2d.1h.7m
    fanboy-social: 22361-29, 4d.1m
    fanboy-ultimate: 165540-162438, 1d.21h.5m
    ublock-annoyances: 4802-5, 2d.15h.50m
    dpollock-0: 11396-92, 11d.2h.12m
    ALB-0: 301-4, 11h.28m
    ara-0: 2754-1, 11h.26m
    BGR-0: 1091-11, 23h.27m
    CHN-0: 28323-189, 2d.15h.48m
    [30 lists not shown]: [too many]
  default: 
    user-filters: 50-0, never
    adnauseam-filters: 502-2, 23h.26m
    ublock-filters: 32894-165, 2d.15h.47m
    ublock-badware: 4612-5, 2d.15h.46m
    ublock-privacy: 333-0, 2d.15h.46m
    ublock-abuse: 77-0, 2d.15h.46m
    ublock-unbreak: 1924-1, 2d.15h.46m
    ublock-quick-fixes: 339-1, 11h.25m
    easylist: 62997-1159, 5d.9m
    easyprivacy: 30976-1422, 5d.8m
    urlhaus-1: 6555-0, 11h.25m
filterset (user): [array of 50 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
untrustedset: 
  added: [array of 1 redacted]
  removed: 
    facebook.com
switchRuleset: 
  added: [array of 3 redacted]
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
    youtube.com * * strictBlock
    funnyordie.com * * strictBlock
modifiedUserSettings: 
  admap: [redacted]
  eventLogging: true
  firstInstall: false
  hidingAds: true
  clickingAds: true
  blockingMalware: true
  removeAdsInPrivate: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2463 ms (selfie)
  maxAssetCacheWait: 409 ms

**Comment by mneunomne** [comment] 2023-03-04 14:51
Related to https://github.com/dhowe/AdNauseam/issues/2310, will fix it asap. In the mean time I recommend disabling AdNauseam on Facebook to avoid this issue.

**Comment by Wolfsbane** [comment] 2023-03-16 07:48
Upon updating to v3.16.3b0 (beta), the original issue has ocurred once I re-activated on Facebook. Also while using v3.16.2, I re-activated on Facebook and on some days between part of the day to the whole day, the above issue was not occurring.

**Comment by mneunomne** [comment] 2023-04-12 14:25
I can confirm this is now fixed since last beta release

**Closed by mneunomne** 2023-04-12 14:25 UTC
Labels: PRIORITY: High, Page Broken
