### ISSUE TITLE
Ads still not collected in Firefox Private Windows

### ISSUE THREAD

**Issue by WhoAmI1000** [dhowe/AdNauseam#1628] opened 2020-02-03 02:45 UTC
My adnauseam settings say that it is version 3.9.103, and it still will not collect ads, despite the settings telling it to. It still does not work, despite being updated past 3.9.102.

**Comment by cqx931** [comment] 2020-02-03 13:49
Hi @WhoAmI1000, have you tried with a brand new profile and a newly installed AdNauseam(3.9.103)? It does work for me when I test it on firefox.
![image](https://user-images.githubusercontent.com/3056154/73658274-0bfb9d80-4662-11ea-9510-542a8b794520.png)


Here is a simple test page we use for testing purpose:
http://lab-lamp.scm.cityu.edu.hk/adntest/simple.html
If ad collection works for you on this page but not on other sites you frequently visit, please let us know the websites and I can look into it.

**Comment by WhoAmI1000** [comment] 2020-02-05 22:55
It works. Thanks!

**Comment by WhoAmI1000** [comment] 2020-02-05 22:57
Although, I decided to also test it on Forbes.com and it seems like it doesn't collect ads there, even though it will usually get 20 within the first minute (on non-private browsing mode).

**Comment by dhowe** [comment] 2020-02-06 07:08
Thanks @WhoAmI1000 I'm going to close this issue and open a new for Forbes.

**Closed by dhowe** 2020-02-06 07:08 UTC

**Comment by cqx931** [comment] 2020-02-06 15:19
@WhoAmI1000 
Just want to add it here that the issue you see in Forbes.com is caused by private browsing mode itself rather than AdNauseam not being able to collect ads.

Here are two example screenshots of ads showing in normal browsing window, but not rendered at all in private browsing mode. In both cases, Adnauseam has been disabled.


![Screen Shot 2020-02-06 at 10 15 08 AM](https://user-images.githubusercontent.com/3056154/73950410-e375dc80-48c9-11ea-92fe-6e8bf231d283.png)

![Screen Shot 2020-02-06 at 10 15 33 AM](https://user-images.githubusercontent.com/3056154/73950568-220b9700-48ca-11ea-8e31-e6a9c864f9e1.png)
