### ISSUE TITLE
Incoming cookies from requests allowed by exception rules in adnauseam.txt should be blocked

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1013] opened 2017-04-25 06:07 UTC
see https://github.com/dhowe/AdNauseam/wiki/Developer-FAQ#how-does-adnauseam-handle-incoming-and-outgoing-cookies

Test case: http://lab-lamp.scm.cityu.edu.hk/adntest/incomingCookies_exceptionAllow.html

**Comment by mneunomne** [comment] 2021-12-12 18:48
@dhowe i didn't understand this actually. The cookie allowed from exception rule should be blocked?

**Comment by dhowe** [comment] 2021-12-12 19:01
Correct. We generally block cookies from resources that trigger rules (so-called "bad" sites), but ignore/allow cookies for user-defined exceptions to those rules ("good" sites). However, we often have to write exceptions in adnauseam.txt to allow ads to be collected. But even though these are exception rules, they are still "bad" sites and we don't want to accept their cookies.

**Comment by mneunomne** [comment] 2021-12-12 19:11
I see. I checked the request from the test page and it is identified as type `image`. How to know it is actually a cookie?

The info from this cookie request:
```
aliasURL: undefined
docDomain: "cityu.edu.hk"
docHostname: "lab-lamp.scm.cityu.edu.hk"
docId: 0
docOrigin: "http://lab-lamp.scm.cityu.edu.hk"
domain: undefined
filter: undefined
frameId: -1
hostname: "bs.serving-sys.com"
id: "27167"
itype: 16
realm: ""
redirectURL: undefined
stype: "image"
tabDomain: "cityu.edu.hk"
tabHostname: "lab-lamp.scm.cityu.edu.hk"
tabId: 377
tabOrigin: "http://lab-lamp.scm.cityu.edu.hk"
tstamp: 0
url: "https://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=tf&c=19&mc=imp&pli=19393001&PluID=0&ord=280682432&rtu=-1"
type: (...)
[[Prototype]]: FilteringContext
```

**Comment by dhowe** [comment] 2021-12-12 19:27
see: https://github.com/dhowe/AdNauseam/blob/master/src/js/traffic.js#L724

**Comment by mneunomne** [comment] 2021-12-13 00:27
@dhowe im having a hard time understanding this part of the code. It seems that even when it is a cookie this first condition is never passed. But maybe this is intended? The sytax of `typeof modifiedHeadersForAdVisits != "boolean"` is quite confusing to me. 

https://github.com/dhowe/AdNauseam/blob/bada276526a19aa0b2ed155e8793e8743352ba3f/src/js/traffic.js#L706-L710

https://github.com/dhowe/AdNauseam/blob/bada276526a19aa0b2ed155e8793e8743352ba3f/src/js/traffic.js#L676-L700

**Comment by dhowe** [comment] 2021-12-13 09:49
below is the list of strings that can be returned from the typeof operator. so if the variable is not typed as a boolean, then return the headers...

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/737638/145789269-37e27101-c7b7-436e-a015-0f446ce8dd88.png">

**Comment by mneunomne** [comment] 2021-12-24 11:07
@dhowe which site were you testing this ? I can't really reproduce this message `[DNT] (AllowCookie1p) https://rednoise.org/adntest/cookie.php`

**Comment by dhowe** [comment] 2021-12-24 14:06
> @dhowe which site were you testing this ? I can't really reproduce this message [DNT] (AllowCookie1p) https://rednoise.org/adntest/cookie.php

nytimes maybe?

**Comment by mneunomne** [comment] 2021-12-25 12:06
This is what i can test at the moment with nytimes.com
 
It says block but i still see the cookie in the storage.

### Console output 
```
[COOKIE] (Block) nyt-gdpr=1; Expires=Sat, 25 Dec 2021 18:03:24 GMT; Path=/; Domain=.nytimes.com 1pDomain: www.nytimes.com  3pDomain: 1 log.js:30:17
[COOKIE] (Block) nyt-gdpr=1; Expires=Sat, 25 Dec 2021 18:03:55 GMT; Path=/; Domain=.nytimes.com 1pDomain: www.nytimes.com  3pDomain: 1 log.js:30:17
```
### Cookie at storage
![Screen Shot 2021-12-25 at 13 05 23](https://user-images.githubusercontent.com/4967860/147384518-23972960-3f13-446d-a16e-6f0c251c7741.png)

**Comment by mneunomne** [comment] 2021-12-26 12:37
@dhowe is this the expected result? I imagine not

**Comment by dhowe** [comment] 2021-12-26 12:40
No it is not. As suggested in the FAQ, there are 3 cookie-related functions, in order of importance:
1. cookies are blocked for ADN Ad visits 
2. cookies are blocked for ADN-allowed requests
3. cookies are NOT blocked for requests to DNT hosts

**Comment by mneunomne** [comment] 2021-12-26 12:42
@dhowe do we a real world example of a DNT website with cookies? I try duckduckgo but apparently it doesn't produce it///

**Comment by dhowe** [comment] 2021-12-26 12:49
http://rednoise.org/adntest/cookie.php

**Comment by mneunomne** [comment] 2021-12-27 09:25
@dhowe While testing I realized that the request coming from "rednoise" never goes to the `blockIncomingCookies` function, since it is not in the `allowedExceptions` list:

https://github.com/dhowe/AdNauseam/blob/e27ff20ce06a127931429c91637dcd74d0be3b91/src/js/adn/core.js#L1710-L1717

This happens because the @@allowed are not running the function `adnAllowRequest` as it should:

https://github.com/dhowe/AdNauseam/blob/e27ff20ce06a127931429c91637dcd74d0be3b91/src/js/adn/core.js#L1233-L1251

above there are these comments:

https://github.com/dhowe/AdNauseam/blob/e27ff20ce06a127931429c91637dcd74d0be3b91/src/js/adn/core.js#L1179-L1201

Isn't the point **5.B** wrong?  We need to block the requests coming from allowed request it seems. In the code it is happening that the @@allowed requests are just logged but not going to the `adnAllowRequest`:



`nytimes` is getting their cookies allowed basically because we to @@allow some of their rules to collect the ads. 

Based on our code, there shouldn't be point **5.B** actually, since we later check for the DNT cases inside the function `blockIncomingCookies` which happens when we go through point **5.D**

**Comment by mneunomne** [comment] 2021-12-28 07:27
> 1. cookies are blocked for ADN Ad visits
> 2. cookies are blocked for ADN-allowed requests
> 3. cookies are NOT blocked for requests to DNT hosts



@dhowe the point `2` includes __the filter lists that we adn-allow__ or this is __only related to what is in__ `adnauseam.txt`? 

*(For example, some of these cookies are generated because we adn-allow the blocking rules from EasyList)*

I believe this is what making making AdNauseam to be allowing more cookies than uBlock as tested bellow.

# nytimes.com tests

## Firefox

(with enabled cookies settings on preferences)

### uBlock

![Screen Shot 2021-12-28 at 07 17 37](https://user-images.githubusercontent.com/4967860/147539356-6d1f6ff4-4b31-453b-86a0-af60eed72f78.png)

### Adn

![Screen Shot 2021-12-28 at 07 17 22](https://user-images.githubusercontent.com/4967860/147539347-a962faa5-75ac-4fe5-bc90-d061df5a2b09.png)

## Chrome:

### uBlock

![Screen Shot 2021-12-27 at 09 44 42](https://user-images.githubusercontent.com/4967860/147539007-cff88151-7df6-4618-9e69-f34a69c4bf6a.png)

### Adn

![Screen Shot 2021-12-27 at 09 44 07](https://user-images.githubusercontent.com/4967860/147538998-f969f52f-2afd-47fe-93e8-c9477ba56474.png)

**Comment by mneunomne** [comment] 2021-12-28 07:31
I tested https://rednoise.org/adntest/cookie.php and it seems that we are allowing the cookies. But I am not sure if it is actually happening because of the behaviour i showed in the previous comment.

**Comment by mneunomne** [comment] 2022-01-04 21:43
I did a new test now, with a clean Firefox profile for both Adnauseam and uBlock, and the results seem to be the same actually. I believe now that the previous test I did had different results due to not having profiles clean from previous uses and accounts etc. 

Now that I understood correctly the code, it seems that it is working properly. It just needs some more comments to be more clear what is happening in certain segments.

![cookie-tests](https://user-images.githubusercontent.com/4967860/148127524-b4dd7542-9242-4ca8-9cac-f58b52e7d954.PNG)

**Comment by dhowe** [comment] 2022-01-04 22:34
we also need to document very clearly how to properly test for each of the 3 (or 4) cases

**Comment by mneunomne** [comment] 2022-01-05 12:34
It seems then that all the things that needed to be tested on this issue, are actually working. I will create another issue for us to investigate why we have some more cookies than uBlock. I believe we can close this.

**Comment by dhowe** [comment] 2022-01-05 12:37
pls link to where each cookie-related test-case is documented

**Comment by mneunomne** [comment] 2022-01-05 13:16
And btw, @dhowe how was this defined? I wanted to leave a comment on this
https://github.com/dhowe/AdNauseam/blob/7909153864f068e78bb685aae11e4d5ce3603752/src/js/traffic.js#L717

**Comment by dhowe** [comment] 2022-01-05 13:39
not sure

**Comment by mneunomne** [comment] 2022-01-07 12:23
Let's continue to investigate this on https://github.com/dhowe/AdNauseam/issues/2007, I think we can close this since the title of the issue was already verified

**Closed** 2022-01-07 13:13 UTC
