### ISSUE TITLE
Images don't load after I enable adnuseam after the newest update.

### ISSUE THREAD

**Issue by ekcja** [dhowe/AdNauseam#1646] opened 2020-03-24 11:59 UTC
### Describe the issue
As in the title, for example, when I visit youtube, It only happens when I have adnuseam on, no matter if I have any other addon enabled.

### Screenshot in which the issue can be seen

https://gyazo.com/37ca91df9220ccfadb66fe1d23cf706b
https://gyazo.com/b41dbcdd3babde020c0fc32ad8f74473

Similar thing on Reddit or other website, I can't see the upvotes, images, even videos on it.

### Steps for anyone to reproduce the issue

It's the newest update that caused it - 3.9.104, also, it happened sometime after I allowed it to use unlimited space on my drive, possibly one of the causes?

### Your settings

- OS/version: Windows 7
- Browser/version: Firefox 74.0 64 Bit
- AdNauseam version: AdNauseam v3.9.104/ uBlock Originv1.20.0
- Other extensions you have installed: None

##### Your filter lists

AdNauseam filters
EasyList
​​EasyPrivacy​
​​uBlock filters​
​​uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
​​uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Malware Domain List
Malware domains​
Facebook Annoyances Blocker​​​​​
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

Poland

**Comment by cqx931** [comment] 2020-03-24 13:51
Hi @ekcja, thank you for your report. However, I can't reproduce this issue on my side and we haven't received other issues similar to what you described here. 

Could you check that you haven't accidentally checked this option "Block media elements larger than XX KB"?
![image](https://user-images.githubusercontent.com/3056154/77432502-87e9aa80-6db4-11ea-9ac2-2e4b6a6acdda.png)

Another thing to check is to set up a brand new Firefox profile and install AdNauseam3.9.104 and see if the issue still exists.

**Comment by mneunomne** [comment] 2023-02-21 01:53
seems to be outdated, closing.

**Closed by mneunomne** 2023-02-21 01:53 UTC
