### ISSUE TITLE
AdNauseam not letting me delete filters I've added

### ISSUE THREAD

**Issue by ThorMjolnir667** [dhowe/AdNauseam#1735] opened 2020-11-05 21:47 UTC
### Describe the issue
I have added some filter lists which another, larger filter list has encompassed the same filters, and I would like to delete the extra filter lists, but as far as I can tell, there is no way to delete them, and so I have an ever expanding list of filter lists that I don't need, did I perhaps just not get it installed correctly? as I remember previously it worked identical to ublockorgin to get rid of filter lists.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 82.0.2 (64-bit)
- AdNauseam version: 3.9.201
- Other extensions you have installed: Duck Duck Go Privacy Essentials, Https Everywhere, Facebook Container, GreenBeam, Multi-accouint Containers, Dark Reader, Privacy Possum, Decentraleyes, FVD Speed Dial, Privacy Pass, Honey,  Startpage.com — Private Search Engine 
- AdNauseam settings:

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by Snaxeko** [comment] 2020-12-05 22:30
I think the issue is more than that, personally if I add a dynamic filter I can't redisable it... The extension seems broken. Once I locked something, I can't reset dynamic filters. Only the "erase" button works (before applying permanent settings). I cant edit dynamic filtering settings manually, or even import a custom file.
I don't experience this with static filtering.

**Comment by dhowe** [comment] 2020-12-07 09:02
@ThorMjolnir667 are you saying that you can disable the lists without problem, but you are not able to remove them altogether?

**Comment by dhowe** [comment] 2020-12-07 09:02
@Snaxeko - please provide a step-by-step on how to recreate the problem.
Also, can you clarify what you mean by: "Once I locked something, I can't reset dynamic filters"

**Comment by gwarser** [comment] 2020-12-07 13:01
![image](https://user-images.githubusercontent.com/886325/101353864-97524a80-3894-11eb-94c3-f7cbf5ec797c.png)

**Comment by ThorMjolnir667** [comment] 2020-12-23 13:57
sorry I have been super busy, but as @gwarser  stated this is my problem

**Comment by mneunomne** [comment] 2021-03-05 11:45
Fixed with https://github.com/dhowe/AdNauseam/pull/1760

For some reason the css classes were made for an `a` element instead of the `span`, which the element in fact was `<span class="fa-icon remove">`.

**Comment by dhowe** [comment] 2021-03-05 12:14
@ThorMjolnir667 - the issue should be fixed now. Please go to "3rd party filters" and click the update button besides "adnauseam filters”, and then let us know if the ad is correctly hidden. Thanks

**Closed** 2021-04-08 10:22 UTC
