### ISSUE TITLE
Ads visible on cointelegraph.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2006] opened 2021-12-30 08:59 UTC
https://cointelegraph.com/magazine/2021/12/19/6-questions-for-david-chaum-of-xx-network

<img width="995" alt="Screenshot 2021-12-30 at 4 58 39 PM" src="https://user-images.githubusercontent.com/737638/147736948-e2c29f73-47fd-45a2-92f2-88675806444d.png">

ADN: current beta

**Comment by mneunomne** [comment] 2022-01-05 12:53
Can't reproduce on my side

**Comment by dhowe** [comment] 2022-01-05 12:57
I still see this:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/737638/148221285-67f1ba78-65b9-4af4-b460-68621d0f0fb0.png">

**Comment by dhowe** [comment] 2022-01-05 13:00
![image](https://user-images.githubusercontent.com/737638/148221555-16589935-f9dd-48b7-8fde-551681ec54db.png)

**Comment by mneunomne** [comment] 2022-01-05 13:58
your VPN is in the US ? i Changed it to the US and still dont see it

**Comment by dhowe** [comment] 2022-01-05 21:03
asia/hk

**Comment by mneunomne** [comment] 2022-01-06 12:48
@dhowe it seems that this page was able to add itself to the whitelist ? Apparently the same thing that happened in https://github.com/dhowe/AdNauseam/issues/1990 this is a critical issue

![whitelisted](https://user-images.githubusercontent.com/4967860/148385288-690f2cf8-8200-4c5d-b92c-d00826a50558.PNG)

**Comment by mneunomne** [comment] 2022-01-06 13:28
It seems that the ad was persisting besides the whitelist issue, so I made a small adition to our filters https://github.com/dhowe/AdNauseam/pull/2011

**Comment by dhowe** [comment] 2022-01-07 03:18
certainly a critical issue if sites can whitelist themselves -- what evidence do we have that this happened? and which whitelist?

**Comment by mneunomne** [comment] 2022-01-07 12:10
Solved, closing

**Closed by mneunomne** 2022-01-07 12:10 UTC
Labels: Ads Visible
