### ISSUE TITLE
Ads visible on 1337x.to

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2359] opened 2023-07-28 14:33 UTC
https://www.1337x.to/search/detroit+become+human/1/

![256850586-293d2dae-9f5a-4918-ad30-b97795da4796](https://github.com/dhowe/AdNauseam/assets/737638/7f4d24e5-e486-4f8b-ba9c-211da25a767c)

**Comment by mneunomne** [comment] 2023-08-03 13:14
Couldn't reproduce on my side

![Screenshot 2023-08-03 at 15 13 11](https://github.com/dhowe/AdNauseam/assets/4967860/08fe8ab2-484c-472a-b84e-5475963bdb86)

**Comment by dhowe** [comment] 2023-08-03 18:18
I can verify this the US on FF 115, with ADN 3.17.0

**Comment by unbeatable-101** [comment] 2023-08-24 01:19
Can reproduce 

```
AdNauseam: 3.17.0
Firefox: 118
filterset (summary): 
  network: 366268
  cosmetic: 239290
  scriptlet: 42649
  html: 1207
listset (total-discarded, last-updated): 
  removed: 
    eff-dnt-whitelist: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/14.txt: 70049-5465, 1d.23h.22m
    https://neuter.mchang.xyz/filter: 151-0, 3h.34m
    https://neuter.mchang.xyz/filter/misc: 37-0, 4d.1m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7256-0, 1d.23h.22m
    https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/requests.txt: 5-0, 4d.1m
    https://raw.githubusercontent.com/paulgb/BarbBlock/master/blacklists/ublock-origin.txt: 550-6, 4d
    https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/duckduckgo/global.txt: 4194-0, 3h.34m
    https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92793-92426, 5d.23h.41m
    adguard-generic: 73014-6725, 1d.23h.23m
    adguard-mobile: 8559-62, 1d.23h.23m
    adguard-spyware: 55992-16944, 1d.23h.23m
    adguard-spyware-url: 1189-5, 1d.23h.23m
    block-lan: 48-0, 24d.20h.21m
    curben-phishing: 161204-79, 3h.35m
    curben-pup: 189-0, 3h.34m
    adguard-annoyance: 70085-70024, 20h.48m
    adguard-social: 21222-699, 1d.23h.22m
    fanboy-thirdparty_social: 68-0, 5d.23h.42m
    fanboy-annoyance: 76837-66315, 20h.48m
    fanboy-cookiemonster: 48148-273, 5d.23h.41m
    [5 lists not shown]: [too many]
  default: 
    user-filters: 114-5, never
    adnauseam-filters: 504-3, 4d.1m
    ublock-filters: 35156-178, 4d.1m
    ublock-badware: 7719-9, 4d.1m
    ublock-privacy: 493-0, 3d.7h.9m
    ublock-abuse: 75-75, 3d.7h.9m
    ublock-unbreak: 2155-1, 4d.1m
    ublock-quick-fixes: 339-12, 3h.35m
    easylist: 69870-714, 4d
    easyprivacy: 33300-581, 1d.23h.23m
    urlhaus-1: 5153-0, 3h.35m
filterset (user): [array of 126 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
untrustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 2 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
    youtube.com * * strictBlock
    funnyordie.com * * strictBlock
modifiedUserSettings: 
  admap: [redacted]
  firstInstall: false
  hidingAds: true
  clickingAds: true
  blockingMalware: true
  cloudStorageEnabled: true
  largeMediaSize: 1
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1040 ms (selfie)
  maxAssetCacheWait: 915 ms
```

**Comment by mneunomne** [comment] 2023-09-28 08:54
Fixed, closing

**Closed by mneunomne** 2023-09-28 08:54 UTC
Labels: PRIORITY: Medium, Ads Visible
