### ISSUE TITLE
Question about filters

### ISSUE THREAD

**Issue by JesseRacine** [dhowe/AdNauseam#2345] opened 2023-07-02 00:12 UTC
I don't fully understand how enabling filter lists effects the collecting of ads.

I had the EasyList + AdNauseam + uBlock filters enabled and I wasn't collecting any ads. Then, ,I disabled the uBlock filters, and now I only have EasyList + AdNauseam filters. I can see that ads are now being collected.

Is this expected then? Should we keep filter lists disabled if we want to have ads collected?

**Comment by mneunomne** [comment] 2023-07-02 09:41
hey @JesseRacine, this is somewhat expected depending on the website you are navigating. 

You were now able to collect more ads because less blocking rules were active from uBlock, which allowed more ads to be rendered, and therefore collected. We need to keep uBlock filters enabled though, because otherwise there will be even more ads appearing for users (there are already some that pass our `adn-allow` rule, so disabling one filter list as a whole will greatly increase these occurrences).

Can you maybe share the specific websites in which you saw this behaviour, i'm curious what exactly were the filters which were triggering this distinction in behaviour.

**Comment by mneunomne** [comment] 2023-09-18 12:10
since this is expected behaviour, I'll close this for now. @JesseRacine if you have more doubts please submit it in our [discussion page](https://github.com/dhowe/AdNauseam/discussions)!

**Closed by mneunomne** 2023-09-18 12:10 UTC
Labels: Question
