### ISSUE TITLE
Blank ads in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1843] opened 2021-05-15 03:22 UTC
Example page generating such an ad: https://hongkongfp.com/2021/05/03/hong-kong-broadcaster-rthk-to-delete-shows-over-a-year-old-from-internet-as-viewers-scramble-to-save-backups/

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/737638/118346722-02086000-b570-11eb-8e4c-c4abe3ba92a4.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/737638/118346681-cec5d100-b56f-11eb-85e7-728e0f1f7782.png">

**Comment by mneunomne** [comment] 2021-05-17 15:49
The issue is that within the html tree within the identified `AMP-AD` tag, there is an element with a transparent image with the following source: `data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9Ijc4IiB3aWR0aD0iNDAwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIvPg==`
I'm not sure how to avoid this false detection yet, but it is not a bug in the collection system, but a misleading detection of a an image src in html tree.

**Comment by mneunomne** [comment] 2021-08-23 14:52
Fixed now with the PR above.

These elements use `AMP-IMG` tag name, which has a "fake" transparent images which was causing our detection to miss. Also this tag doesn't have ".complete" parameter, so I let it go through without this check.

More about this tag: https://amp.dev/documentation/components/amp-img/

Captures:
![captures](https://user-images.githubusercontent.com/4967860/130468803-c9722d4e-4cf1-40d4-be66-7e1625a5edf3.PNG)

**Closed** 2021-08-23 16:10 UTC
Labels: PRIORITY: High
