### ISSUE TITLE
namemc.com: ads

### ISSUE THREAD

**Issue by Cats1337** [dhowe/AdNauseam#2509] opened 2024-01-30 00:53 UTC
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

Whole-page advertisements appear at times, sometimes it's just popup banners across the bottom of the screen.

### URL(s) where the issue occurs.

https://namemc.com/

### Screenshot(s)

![Screenshot 2024-01-29 at 19-48-19 adnauseam Search](https://github.com/dhowe/AdNauseam/assets/42129397/32d80962-12a4-4525-b9d7-2f0456f8a475)

### Steps to Reproduce

Best way I'v been able to replicate is
1. Seach a name
2. Wait for about 30 seconds
3. Ads apepar

### Configuration

<details>

```yaml
AdNauseam: 3.20.0
Firefox: 122
filterset (summary):
 network: 137418
 cosmetic: 199135
 scriptlet: 31305
 html: 2266
listset (total-discarded, last-updated):
 added:
  adguard-social: 22481-877, now
  adguard-cookies: 28487-60, now
  ublock-cookies-adguard: 913-0, now
  adguard-popup-overlays: 26889-1620, now
  adguard-mobile-app-banners: 4923-1074, now
  adguard-other-annoyances: 14125-332, now
  adguard-widgets: 2428-1, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4333-122, now
  easylist-chat: 180-13, now
  fanboy-cookiemonster: 49585-3842, now
  ublock-cookies-easylist: 913-913, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  adnauseam-filters: 518-2, now
  eff-dnt-whitelist: 657-0, now
  ublock-filters: 37467-502, now
  ublock-badware: 7803-10, now
  ublock-privacy: 988-0, now
  ublock-unbreak: 2244-0, now
  ublock-quick-fixes: 134-0, now
  easylist: 80281-671, now
  easyprivacy: 43597-290, now
  urlhaus-1: 8310-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
hostRuleset:
 removed:
  youtube.com * * strictBlock
  funnyordie.com * * strictBlock
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
 disableClickingForDNT: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 800 ms (selfie)
 maxAssetCacheWait: 152 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  adnxs.com: 4
  aniview.com: 1
  anonymised.io: 1
  bidswitch.net: 2
  btloader.com: 1
  criteo.com: 2
  googletagmanager.com: 2
  id5-sync.com: 1
  media.net: 1
  pbstck.com: 1
  quantserve.com: 1
  rubiconproject.com: 1
  smartadserver.com: 1
 extended:
  ##.ad-container
  ###skin_wrapper
  ##[name^="google_ads_iframe"]
  ##div[data-google-query-id]
  ##+js(abort-current-script, setTimeout, runInIframe)
  ##+js(abort-on-property-write, deployads)
  ###google_image_div
  ##.img_ad
  ##a[href^="https://googleads.g.doubleclick.net/pcs/click"]
```
</details>

**Comment by mneunomne** [comment] 2024-01-30 16:08
Was not able to reproduce. @Cats1337 could you please share your location? Perhaps this is country specific.

**Comment by Cats1337** [comment] 2024-01-30 16:13
East Coast United States

**Comment by mneunomne** [comment] 2024-02-21 05:06
I was not able to reproduce this issue, I tried different locations, also tried logged in but nothing

**Comment by mneunomne** [comment] 2024-07-26 21:27
Could not reproduce, closing.

**Closed by mneunomne** 2024-07-26 21:27 UTC
Labels: Ads Visible, Cannot Reproduce
