### ISSUE TITLE
Firefox "Standard" content blocking still causes issues

### ISSUE THREAD

**Issue by nickavem** [dhowe/AdNauseam#1762] opened 2021-03-08 14:15 UTC
### Firefox "Standard" content blocking still causes issues

Should there be a warning about this? What custom settings should I have enabled/disabled for an optimal experience?

### Screenshot in which the issue can be seen
[3 refreshes and page scrolls with content blocking fully disabled on nytimes.com](https://ibb.co/HC7nphM)

[Same experiment with "standard" content blocking](https://ibb.co/4dtZBTJ)

### Steps for anyone to reproduce the issue
1. Have Firefox standard "Standard" content blocking enabled (default).

### Your settings

- OS/version:
Fedora Linux Silverblue 33
- Browser/version:
Name 	Firefox
Version 	86.0
Build ID 	20210222142601
Distribution ID 	mozilla-flatpak
- AdNauseam version:
AdNauseam v3.9.201 uBlock Originv1.29.0 
- Other extensions you have installed:
AdNauseam	extension	3.9.201	true	adnauseam@rednoise.org
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Copy PlainText	extension	1.12	true	copyplaintext@eros.man
Dark Reader	extension	4.9.29	true	addon@darkreader.org
Decentraleyes	extension	2.0.15	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Emoji	extension	3.10.2	true	emoji@saveriomorelli.com
Firefox Relay	extension	1.5.1	true	private-relay@firefox.com
Google	extension	1.1	true	google@search.mozilla.org
Grammar and Spell Checker — LanguageTool	extension	3.3.4	true	languagetool-webextension@languagetool.org
I don't care about cookies	extension	3.2.8	true	jid1-KKzOGWgsW3Ao4Q@jetpack
Imagus	extension	0.9.8.74	true	{00000f2a-7cde-4f20-83ed-434fcb420d71}
LASER CAT	extension	22.17.1	true	{e981cbfb-2e31-4be3-85ce-c4a058a38f94}
Netflix 1080p	extension	1.15.2	true	{f18f0257-10ad-4ff7-b51e-6895edeccfc8}
Search by Image	extension	3.6.0	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
To Google Translate	extension	4.1.0	true	jid1-93WyvpgvxzGATw@jetpack
Web Archives	extension	2.1.0	true	{d07ccf11-c0cd-4938-a265-2a4d6ad01189}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
English (CA) Language Pack	locale	86.0buildid20210222142601	true	langpack-en-CA@firefox.mozilla.org
English (GB) Language Pack	locale	86.0buildid20210222142601	true	langpack-en-GB@firefox.mozilla.org
- AdNauseam settings:

##### Your filter lists

Default
### Your location/country
EN/US

**Comment by nickavem** [comment] 2021-03-08 14:54
For now having my privacy settings look like this seems to work best.
![Screenshot from 2021-03-08 09-53-02](https://user-images.githubusercontent.com/72708798/110337726-3e5d9400-7ff4-11eb-910b-2a49ddede03e.png)

**Comment by dhowe** [comment] 2021-03-09 06:43
Enabling 'Cookies' should also be OK. Potential conflicts with AdNauseam _should_ only be related to the 'Tracking content' option. With that said, it may make sense to add a warning when that option is selected.

**Comment by nickavem** [comment] 2021-03-09 12:18
So what exactly is causing the issue? What would be the optimal config for Nauseam?

**Comment by nickavem** [comment] 2021-03-09 15:34
So this actually appears to be an issue with the cache somewhere (could be related to #1685 ). Fixed by deleting Firefox profile (.mozilla) and re-syncing everything.

**Comment by dhowe** [comment] 2021-03-30 12:25
We need add a warning for Firefox blocking when ‘Tracking Content’ is selected, as this will interfere with ADN's ad collection. 

A question is whether we do this ONLY when 'in all windows' is selected, or even when 'only in private windows' is selected (the latter being the default). I think that for now, assuming we can differentiate between the two, we only need to worry about the former case, and not the default tracking protection case. 

In any case, I am moving this to the next release. Meantime please add an entry in the FAQ: 'Will Firefox's 

To detect settings, see 'trackingProtectionMode' on this page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites


![image](https://user-images.githubusercontent.com/737638/112987863-beab8b00-9195-11eb-8d4a-811e91565ad4.png)

**Comment by nickavem** [comment] 2021-03-30 12:32
Alright. I think another thing that should be made clearer is that ADN doesn't collect/click on *all* ads which led me to believe it was somehow broken as well.

**Comment by dhowe** [comment] 2021-03-30 12:47
well, it tries its best :) but yes, there will be ads it cannot collect

@mneunomne can we add this to the FAQ ?

**Comment by dhowe** [comment] 2021-03-30 18:04
I have confirmed that warnings for firefox tracker-blocking are working as expected, except for a css issue which appears to be cutting of some the text:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/737638/113035059-63918c80-91c5-11eb-950c-0bc594c51d51.png">

**Comment by mneunomne** [comment] 2021-03-31 13:16
@dhowe Could we possibly come up with a smaller text for this warning? its gonna be tricky to fit this text in 400px width without having to change quite a few things in the notification css

**Comment by dhowe** [comment] 2021-03-31 19:35
Q1: Do all the other warning fit in that space?
Q2: Can we include a link to more info (in the wiki perhaps)

I worry that with the above wording it's not clear _where_ those settings are (in the browser) or how to fix them (though the latter is not clear in either case)

**Comment by mneunomne** [comment] 2021-04-05 19:50
>Q: Do all the other warning fit in that space?

@dhowe No, also because since there are multiple languages supported and some of the translated text is quite longer than the english one.

>I worry that with the above wording it's not clear where those settings are (in the browser) or how to fix them, though if we can fit the '?' link as in the other warnings, which goes to a nice wiki explanation of how to fix the problem for the various browsers (edge, firefox, etc.), then even the following would be ok:

The '?' is already there in this warning actually, but the css is now showing it. Perhaps this solution using the `text-overflow: ellipsis;` is reasonable since we cannot guarantee all texts in all languages will fit the small space we have for the menu:
![Screen Shot 2021-04-05 at 21 47 41](https://user-images.githubusercontent.com/4967860/113619038-c1f0bc00-9658-11eb-8c7c-24d84f5ab2ea.png)

**Comment by dhowe** [comment] 2021-04-06 03:32
As long as the '?' is always showing, that seems like a good solution.

**Comment by mneunomne** [comment] 2021-04-07 12:02
Solution to text overflow with https://github.com/dhowe/AdNauseam/pull/1797

![Screen Shot 2021-04-07 at 13 56 59](https://user-images.githubusercontent.com/4967860/113863063-7c8fd400-97a9-11eb-85aa-bb564f15a1e1.png)

**Closed** 2021-04-08 21:10 UTC
Labels: Enhancement, Question
