### ISSUE TITLE
anime2you.de: ads

### ISSUE THREAD

**Issue by TanukiAI** [dhowe/AdNauseam#2487] opened 2023-12-19 23:40 UTC
### I tried to reproduce the issue when...

- [X] AdNauseam is the only extension
- [X] AdNauseam uses default lists and settings
- [X] Using a new, unmodified browser profile

### Description

With AdNauseam I have ads in the left, right and top after some seconds.

### URL(s) where the issue occurs.

`https://www.anime2you.de/news/750569/oregairu-light-novel-figur-yukino/`

### Screenshot(s)

![grafik](https://github.com/dhowe/AdNauseam/assets/46388493/aabffe4a-ab38-4010-9b0a-0cb3f7b2e2a9)

### Steps to Reproduce

1. Visit the website
2. Wait some seconds for some requests to be made

### Configuration

<details>

```yaml
AdNauseam: 3.19.0
Firefox: 120
filterset (summary):
 network: 99211
 cosmetic: 49334
 scriptlet: 19510
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  adnauseam-filters: 509-2, 1d.6h.19m
  eff-dnt-whitelist: 684-0, 1d.6h.19m
  ublock-filters: 37319-246, 2h.50m
  ublock-badware: 7623-11, 1d.6h.19m
  ublock-privacy: 945-4, 2h.50m
  ublock-unbreak: 2222-1, 2h.50m
  ublock-quick-fixes: 116-0, 8h.51m
  easylist: 75917-376, 2h.50m
  easyprivacy: 33118-35, 2h.50m
  urlhaus-1: 4273-0, 50m
  DEU-0: 7230-2, 50m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 18 redacted]
userSettings:
 admap: [redacted]
 firstInstall: false
 hidingAds: true
 clickingAds: true
 blockingMalware: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2921 ms (selfie)
 maxAssetCacheWait: 251 ms
popupPanel:
 blocked: 144
 network:
  adform.net: 9
  adnxs.com: 15
  adsrvr.org: 2
  aniview.com: 2
  bidr.io: 1
  bidswitch.net: 6
  confiant-integrations.net: 1
  consentmanager.net: 1
  criteo.com: 2
  criteo.net: 1
  doubleclick.net: 4
  dspx.tv: 3
  id5-sync.com: 5
  otto.de: 10
  outbrain.com: 12
  pbstck.com: 1
  pghub.io: 1
  quantserve.com: 1
  rlcdn.com: 2
  rubiconproject.com: 8
  smartadserver.com: 28
  vidazoo.com: 2
  viralize.tv: 23
  visx.net: 4
 extended:
  ##.ad_platzhalter
  ##.ad_banner
  ###Ad-Content
  ##.werbung
  ##div[id^="outbrain_widget"]
  ##iframe[src*="amazon-adsystem.com"]
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##[name^="google_ads_iframe"]
  ##div[data-google-query-id]
  #@#[id^="google_ads_iframe"]
  ##.ad-element
  ##iframe[src*="imasdk.googleapis.com/js"]
  ##+js(xml-prune, VAST, , adnxs)
  ##div[id^="ad_position_"]
  ##.GoogleActiveViewElement > div:not(#reward_close_button_widget…
  ###abgb
  ###mys-content
  ##.GoogleActiveViewElement:not(:has(> #reward_close_button_widge…
  ###adunit
  ##.content-ads
  ##.ad-1
  ##.advertiser
  ##a[href^="https://adclick.g.doubleclick.net/"]
  ###ad_unit
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by dhowe** [comment] 2023-12-19 23:50
Could not recreate from US location

**Comment by TanukiAI** [comment] 2023-12-20 06:58
Germany.

**Comment by mneunomne** [comment] 2023-12-20 08:53
Could not reproduce on same location. Perhaps outdated filter-lists?

**Comment by TanukiAI** [comment] 2023-12-22 11:11
Deleted caches and reloaded all lists, still not working.
Ads appear after making an request to https://ads.viralize.tv/player/?zid=AAEsZ3ezHBGHsD5_&sid=01eea0ba86285366e5b74cd9d39015b2&activation=adfill-onview&experiment=ops.&u=https%3A%2F%2Fwww.anime2you.de%2Fnews%2F750569%2Foregairu-light-novel-figur-yukino%2F&ahd=1&player_session=%7B%22page_id%22%3A%22018c9136f3dcc3015e537c3be26dac00%22%2C%22screen%22%3A%7B%22width%22%3A2048%2C%22height%22%3A1152%7D%2C%22page%22%3A%7B%22width%22%3A2031%2C%22height%22%3A4646%7D%2C%22viewport%22%3A%7B%22width%22%3A2048%2C%22height%22%3A633%7D%2C%22player_size%22%3A%7B%22width%22%3A0%2C%22height%22%3A0%7D%7D&sc=2&cmp=available&dd=anime2you.de&content_adplayer=1&hcid=Njc3NTE1ng6JawdD8nU%3D&enable_branding=0&pub_platform=&gdpr=1&cs=CP3FURgP3FURgAfCEBDEAfEsAP_gAEPgAAYgJctV9H_fbWFHOXp3YPs0eY0f19h75uQxBheBE-AFyDuE-JQX12EyNAygNCQCEBAAoRZBIAAsDBlERVCgQIgVITHsIgCQhRIKIsBEACMRQ0RACAgIEAEgEAAYhUJtJ1QAmCrwadruRNQAhIAgDyAAAAEBAKiNAgNBHGE4QAAQgQIEwqTAAgJEcAAAAAEKQQgIUQBACACAIAgCCXLVfR_321hRzl6d2D7NHmNH9fYe-bkMQYXgRPgBcg7hPiUF9dhMjQMoDQkAhAQAKEWQSAALAwZREVQoECIFSEx7CIAkIUSCiLARAAjEUNEQAgICBABIBAAGIVCbSdUAJgq8Gna7kTUAISAIA8gAAABAQCojQIDQRxhOEAAEIECBMKkwAICRHAAAAABCkEICFEAQAgAgCAIAgAA&us_privacy=

Blocking this address makes it disappear

**Comment by mneunomne** [comment] 2023-12-30 18:20
Implemneted the following filter that keeps the ad collection working and blocks possible ads that are going through on this case:

```
||ads.viralize.tv/$domain=www.anime2you.de,important
```

Closing.

**Closed by mneunomne** 2023-12-30 18:20 UTC
Labels: Ads Visible, Cannot Reproduce
