### ISSUE TITLE
Pinterest home feed ads not collected

### ISSUE THREAD

**Issue by thankfulmachine** [dhowe/AdNauseam#2492] opened 2023-12-26 00:52 UTC
### What type of Ad is not being collected

- [X] Image
- [X] Text
- [ ] Video
- [ ] Mid-roll Video Ad
- [ ] Popup

### URL(s) where the ads appear.

https://pinterest.com

### Your location/country.

USA

### Screenshot(s) of uncollected ads (disable AdNauseam if they are being correctly hidden)

I do not see any ads being collected either on initial load or as I scroll. Here are a few examples.

Note: you must turn off ad hiding currently, otherwise the entire home feed is blank. See https://github.com/dhowe/AdNauseam/issues/2491

![Screenshot 2023-12-25 165004](https://github.com/dhowe/AdNauseam/assets/124486332/88f7a560-dcea-4e9a-a202-a69103ee9db5)

![Screenshot 2023-12-25 165009](https://github.com/dhowe/AdNauseam/assets/124486332/6511a254-bcb1-4081-a7a8-09a2facbecdb)

![Screenshot 2023-12-25 165049](https://github.com/dhowe/AdNauseam/assets/124486332/f03e669f-b44f-4196-99b4-108e830babd8)

**Comment by mneunomne** [comment] 2024-01-04 18:47
This is happening because ad-hiding is disabled, https://github.com/dhowe/AdNauseam/issues/2491 is already fixed, so it can be enabled once again.

I can collect quite a few ads on pinterest:

<img width="329" alt="Screenshot 2024-01-04 at 18 45 45" src="https://github.com/dhowe/AdNauseam/assets/4967860/89ec2140-14e5-46cd-a955-cbc4464afb76">

**Comment by mneunomne** [comment] 2024-07-26 21:28
Fixed, further issues could not be reproduced, closing.

**Closed by mneunomne** 2024-07-26 21:28 UTC
Labels: Ads Not Collected, Cannot Reproduce
