### ISSUE TITLE
[v3.10.1rc3] Tests report 

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1822] opened 2021-04-22 22:46 UTC
### Tests

>[ ] If an ad is not visited because the user has already clicked it, the ad should be marked as "SKIPPED: Clicked by user "

Couldn't find a case to be able to reproduce this. 

>[ ] Check that the dashboard (if open) is updated when notifications change

Notifications don't appear immediately in open dashboard right after settings are changed. But when "reactivate" button is clicked, the behaviour is as expected. Ad Vault tab shows and hides notifications imediatelly as they need to be displayed or hidden. Occurs both in Firefox and Chrome

>[ ] DNT-header is being sent correctly for ALL requests (including Ad visits) if either disableClickingForDNT and disableHidingForDNT are enabled (and vice versa) 

Testing in Firefox I was only able to detect the `DNT: 1` in the request header if the `Send web sites a “Do Not Track” signal that you don’t want to be trackedLearn more` was selected as `Always` in the __Privacy & Security__ preferences.

>[ ]  DNT Cookies are allowed (v3.1 and later)

What determines a `DNT Cookie` and how to identify it? could we have more information on that? 

>[ ]  Requests are not blocked when domain is 3rd-party iff disableHidingForDNT is checked([here](http://lab-lamp.scm.cityu.edu.hk/adntest/effTestPage.html)) 

`lab-lamp.scm.cityu.edu.hk` is not being identified as DNT website. The other DNT websites was hard to find ad examples to be collected. Will look more into it.

### My settings

- OS/version: Mac OS 10.13.6
- Browser/version:  `Firefox 88.0 (64-bit)` & `Chrome v90.0 (x86_64)`
- AdNauseam version: [v3.10.1rc3 Pre-release](https://github.com/dhowe/AdNauseam/releases/tag/v3.10.1rc3)

**Comment by dhowe** [comment] 2021-04-23 07:13
>>[ ] If an ad is not visited because the user has already clicked it, the ad should be marked as "SKIPPED: Clicked by user "

>Couldn't find a case to be able to reproduce this. 

Did you test by clicking an ad?

**Comment by dhowe** [comment] 2021-04-23 07:14
>> What determines a DNT Cookie and how to identify it? could we have more information on that?

A cookie set by a DNT site should be allowed

**Comment by dhowe** [comment] 2021-04-23 07:14
> lab-lamp.scm.cityu.edu.hk is not being identified as DNT website. The other DNT websites was hard to find ad examples to be collected. Will look more into it.

rednoise.org is a DNT site - tests should be done there

**Comment by dhowe** [comment] 2021-04-23 07:15
>Testing in Firefox I was only able to detect the DNT: 1 in the request header if the "Send web sites a “Do Not Track” signal that you don’t want to be tracked - Learn more" was selected as Always in the Privacy & Security preferences.

So FF's DNT setting is overriding AdNauseam behavior?

**Comment by mneunomne** [comment] 2021-04-23 09:43
> Did you test by clicking an ad?

Do you mean in the menu interface after they are collected but before they are clicked? In that can yes, but the label "Clicked by user" did not appear. I think we need to be more specific in the description. 

> A cookie set by a DNT site should be allowed

I think we need more information (with screenshots) of what is expected to identified here.

From this test page https://rednoise.org/adntest/cookie-setting-ad.html is this what is expected?

![Screen Shot 2021-04-23 at 11 31 22](https://user-images.githubusercontent.com/4967860/115852025-e81fa580-a427-11eb-9310-62649c6cc8a6.png)![Screen Shot 2021-04-23 at 11 31 17](https://user-images.githubusercontent.com/4967860/115852027-e950d280-a427-11eb-941d-267b8383857a.png)

> rednoise.org is a DNT site - tests should be done there

Ah ok, I didn't know `rednoise.org` had the same pages as in `lab-lamp.scm.cityu.edu.hk`. Will substitute in the documentation for the DNT test cases.

> So FF's DNT setting is overriding AdNauseam behavior?

As far as I understood yes. Wasn't able to detect the DNT otherwise.

**Comment by Real-John-Cheung** [comment] 2021-04-23 14:52
>[ ] If an ad is not visited because the user has already clicked it, the ad should be marked as "SKIPPED: Clicked by user "

>Couldn't find a case to be able to reproduce this. 

Hmm I successfully recreated this (Firefox 88.0 & Chrome 90.0.4430.85, macOS 10.15.7) by clicking them manually before adn does (sorry because my browser setting the following screenshots are in Chinese, but the first ads are marked as 'skip: click by user' and stay blue)
<img width="300" alt="螢幕截圖 2021-04-23 下午10 36 31" src="https://user-images.githubusercontent.com/61215358/115887280-5b570500-a484-11eb-8289-86ec69915d60.png"><img width="300" alt="螢幕截圖 2021-04-23 下午10 32 35" src="https://user-images.githubusercontent.com/61215358/115886743-cf44dd80-a483-11eb-9e36-07841a0b95cb.png">

> Do you mean in the menu interface after they are collected but before they are clicked? In that can yes, but the label "Clicked by user" did not appear. I think we need to be more specific in the description.

@mneunomne  I am not sure if I understand correctly... but I reproduced it by clicking the ads from the menu (the one in the above screenshots). I guess I did the same thing as you?

> -- I mean simply manually clicking an ad on a website. If the user clicks the ad, then adn should not.

@dhowe I am a bit confused about that: I think since the ads are hidden by adn, users cannot see them and click them on the website right? BTW I also tried to disable ad hiding and enable ad clicking only, but in that case no ad is captured by adn, and I am not sure if it should behave like that...

**Comment by Real-John-Cheung** [comment] 2021-04-23 15:02
And on my machine, the first-run page does not occur when adn is installed (in Firefox, via `about:debugging` - `load temporary add-on`; in Chrome, via `chrome://extensions/` - `load unpacked add-on`), but the dashboard page is opened instead...

**Comment by Real-John-Cheung** [comment] 2021-04-23 15:19
> A cookie set by a DNT site should be allowed

This works for me too... 
<img width="1009" alt="螢幕截圖 2021-04-23 下午11 09 27" src="https://user-images.githubusercontent.com/61215358/115891699-f651de00-a488-11eb-98ad-fb5723b9a56e.png">
<img width="1003" alt="螢幕截圖 2021-04-23 下午11 10 01" src="https://user-images.githubusercontent.com/61215358/115891774-09fd4480-a489-11eb-8468-f6b1560b67a2.png">

**Comment by mneunomne** [comment] 2021-04-23 16:19
> > A cookie set by a DNT site should be allowed
> 
> This works for me too...

Cool, was able to reproduce this as well, would be nice to add some of these screenshots to the documentation as reference.

**Comment by mneunomne** [comment] 2021-04-23 16:26
> @mneunomne I am not sure if I understand correctly... but I reproduced it by clicking the ads from the menu (the one in the above screenshots). I guess I did the same thing as you?

Ah ok, now I was able to make it work, since I had disabled click in the dashboard, it was only appearing "clicking disabled". I had to enable clicking again to show "clicked by the user"

**Comment by dhowe** [comment] 2021-04-24 05:13
> 
> 
>         A cookie set by a DNT site should be allowed
> 
>     This works for me too...
> 
> Cool, was able to reproduce this as well, would be nice to add some of these screenshots to the documentation as reference.

Good (and good idea)

**Comment by dhowe** [comment] 2021-04-24 05:13
> 
> 
>     @mneunomne I am not sure if I understand correctly... but I reproduced it by clicking the ads from the menu (the one in the above screenshots). I guess I did the same thing as you?
> 
> Ah ok, now I was able to make it work, since I had disabled click in the dashboard, it was only appearing "clicking disabled". I had to enable clicking again to show "clicked by the user"

Good

**Comment by dhowe** [comment] 2021-04-24 05:15
> And on my machine, the first-run page does not occur when adn is installed (in Firefox, via `about:debugging` - `load temporary add-on`; in Chrome, via `chrome://extensions/` - `load unpacked add-on`), but the dashboard page is opened instead...

this is INTENTIONAL -- when running in dev mode, the first-run menu is not supposed to open: all options are enabled by default, debugging is enabled, and the settings page is opened

@mneunomne please note this wherever necessary so that this does not keep getting reported

**Closed** 2021-05-02 06:41 UTC
