### ISSUE TITLE
Youtube detects Ad Nausium

### ISSUE THREAD

**Issue by hieusStorm** [dhowe/AdNauseam#2476] opened 2023-11-26 23:27 UTC
### Describe the issue
YouTube is detecting adnauseam and blocking videos from being played

![image](https://github.com/dhowe/AdNauseam/assets/58410926/77699dd4-7d7e-4344-afe2-038504600294)

### Steps for anyone to reproduce the issue
Load YouTube with adnauseam enabled and YouTube should block it

### Your settings

- OS/version: Windows 10
- Browser/version: latest Firefox
- AdNauseam version: latest
- Other extensions you have installed: Malwarebytes w/ ads disabled
- AdNauseam settings: Default

##### Your filter lists
default list

**Comment by uwidev** [comment] 2023-11-27 02:41
v3.19.0 seems to fix this. I installed it via github. At the moment firefox store isn't updated yet, so if you want it now, you'll have to do it manually. If you do this, however, iirc the extension is unsigned, which means you may not be able to install it on normal firefox browsers.

**Comment by dhowe** [comment] 2023-11-28 08:21
duplicate of https://github.com/dhowe/AdNauseam/issues/2475

**Closed by dhowe** 2023-11-28 08:21 UTC
