### ISSUE TITLE
[3.12] Gray ad bar at top of nytimes.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1987] opened 2021-12-13 11:20 UTC
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/737638/145803376-12d18b45-3357-43f8-ae15-d04f9a18f48f.png">

**Comment by mneunomne** [comment] 2021-12-18 15:30
Fixed, closing

**Comment by mneunomne** [comment] 2021-12-19 12:21
https://github.com/dhowe/AdNauseam/issues/1995 was caused by this change actually, reversing and reopening

**Comment by mneunomne** [comment] 2021-12-23 14:30
this is not happening with me any longer on master

**Closed** 2021-12-23 16:33 UTC
Labels: PRIORITY: High
