### ISSUE TITLE
webExt - can't open vault or settings page from menu 

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1137] opened 2017-08-30 21:29 UTC
master branch, Firefox web extension

To reproduce:
1. click on adnauseam icon to open menu
2. click on 'settings' or 'view ad vault', the popup menu closes itself, but no page is opened.

**Comment by cqx931** [comment] 2017-08-30 22:55
Went through the debugger, but I don't see any performance difference between AdNauseam and current uBlock. The warning messages I got for AdNauseam also happens for uBlock.

**Comment by dhowe** [comment] 2017-08-31 02:09
can you include a screenshot?

**Comment by cqx931** [comment] 2017-08-31 02:12
I have added some steps to reproduce the issues above

**Comment by dhowe** [comment] 2017-08-31 02:27
This is what I see after clicking 'Lets Go', then the toolbar icon ?

![image](https://user-images.githubusercontent.com/737638/29903530-568ba0b6-8dd2-11e7-85bc-080f8c586b3d.png)

**Comment by dhowe** [comment] 2017-08-31 02:40
Fixed

**Comment by cqx931** [comment] 2017-08-31 12:03
The issue you mentioned in the screenshot is fixed, but this is not what I'm talking about in this ticket.

**Comment by dhowe** [comment] 2017-08-31 12:59
cannot recreate with  merged1.13.0 on Firefox 56.0b6

**Comment by greysonevins** [comment] 2017-08-31 15:45
I can't reproduce the issue either @cqx931

**Comment by dhowe** [comment] 2017-08-31 16:13
closing for now, will re-open if occurs again

**Closed by dhowe** 2017-08-31 16:13 UTC
Labels: PRIORITY: High, WebExt
