### ISSUE TITLE
"Waiting for the AdNauseam extension to load"

### ISSUE THREAD

**Issue by rdbox** [dhowe/AdNauseam#974] opened 2017-04-10 07:30 UTC
With the use of your application from today, the pages have long been loaded. As soon as I turn off AdNauseam everything works fine.
Why is that?

**Comment by rdbox** [comment] 2017-04-10 07:35
At the bottom of the screen an inscription,
**Waits for the AdNauseam extension to load**. And the browser hangs free

![image](https://cloud.githubusercontent.com/assets/18515862/24850591/5a1f4f48-1dd9-11e7-8b9d-b23e24f6f021.png)

**Comment by dhowe** [comment] 2017-04-12 11:45
OS, browser, and AdNauseam versions?

**Comment by rdbox** [comment] 2017-04-12 12:31
browser ver  57.0.2987.133 
AdNauseam v3.3.32

**Comment by dhowe** [comment] 2017-04-13 02:33
operating system?

**Comment by SkeLLLa** [comment] 2017-04-13 06:19
It happened to few times. Mostly this is caused by sites that contain a lot of ads or some messy code that inserts them in runtime. Most of them are news websites with mixed-type ads (text, video, image, iframes, etc.). Sometimes it can be also caused bu uncaught exceptions in adnausem itself.

I've observed such behavior on both windows and linux in chrome 58 and 59.

**Comment by cqx931** [comment] 2017-04-13 06:44
By observing the parser, this seems to be caused by dynamically generated href attribute for a tag.
When AdNauseam catches the ad div, the element looks like below and the href attribute is "http:"
![screen shot 2017-04-13 at 2 28 12 pm](https://cloud.githubusercontent.com/assets/3056154/24992804/e5c47acc-2055-11e7-884e-864726c48ef6.png)
And this is how it looks like after the page fully loaded (inspect element):
![image](https://cloud.githubusercontent.com/assets/3056154/24992825/fe74af1a-2055-11e7-8e77-fc766bacdca4.png)

To solve this, one way is to update the targetUrl if the a tag that got matched with an ad object has been dynamically changed. But I'm not sure whether this would slow down the page loading.
@dhowe What are your thoughts on this?

**Comment by dhowe** [comment] 2017-04-13 07:43
Thanks! Would be great if you could paste any uncaught exceptions here as well...

**Comment by dhowe** [comment] 2017-04-13 08:01
@cqx931 can you try to recreate this on windows ?

**Comment by rdbox** [comment] 2017-04-13 08:45
@dhowe 
Win 7 pro x64 
 Microsoft Windows [Version 6.1.7601]

**Comment by SkeLLLa** [comment] 2017-04-13 08:47
@dhowe I've reported some of them already. And I've found few more, but it seems that they are not related to this issue. It's more about specific websites and exceptions right in their code. Sometimes advertising networks inject their scripts that can't handle adblocking properly and cause high cpu usage.

**Comment by rdbox** [comment] 2017-04-13 08:49
Here is an example of sites where it happens a long wait
https://e.mail.ru/messages/inboxm
mail.ru
nnmclub.to

**Comment by cqx931** [comment] 2017-04-13 10:43
I tested pages above with the following settings, but I didn't see the message "Waiting for the AdNauseam extension to load". The browser doesn't hang and the loading time seems to be ok.
(Except that I got 404 error for this url: https://e.mail.ru/messages/inboxm after a relatively long waiting time, but that is not related to AdNauseam)

Chrome 57.0.2987.133
AdNauseam v3.3.32
Windows 7 Enterprise and Windows 7 Professional

What other extensions have you installed? @rdbox

**Comment by rdbox** [comment] 2017-04-13 11:14
That's the problem. Message the download is waiting unexpectedly, accidentally

**Comment by dhowe** [comment] 2017-04-13 11:43
Can you try to recreate this with a fresh 'person' and only adnauseam installed?

![image](https://cloud.githubusercontent.com/assets/737638/25003334/7f6f342a-2081-11e7-8ec6-51b3fa278678.png)

**Comment by dhowe** [comment] 2017-04-13 14:09
see also: https://github.com/gorhill/uBlock/issues/2534#issuecomment-293887281

**Comment by dhowe** [comment] 2017-04-24 02:23
closing for now as cannot recreate

**Closed by dhowe** 2017-04-24 02:23 UTC
Labels: Needs-verification, PRIORITY: Medium
