### ISSUE TITLE
uBlock element picker and zapper no longer working

### ISSUE THREAD

**Issue by booleancoercion** [dhowe/AdNauseam#2214] opened 2022-11-19 15:35 UTC
### Describe the issue

The element picker/zapper buttons in the uBlock menu no longer do anything - clicking them is simply a no-op.

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 107.0
- AdNauseam version: AdNauseam v3.15.1 / uBlock Origin v1.44.4
- Other extensions you have installed: None (I verified that this happens without other extensions)
- AdNauseam settings: Default, without the exceptions for non-tracking ads.

##### Your filter lists
Default filter lists + all annoyances

**Comment by Slater91** [comment] 2022-11-24 12:38
I can confirm this on Linux with Firefox 107.0 and AdNauseam 3.15.1.

**Comment by Pocarai** [comment] 2022-11-25 14:42
Yeah.. Me too I was afraid of this and this is important, I wish this will get fix asap.

**Comment by mneunomne** [comment] 2022-11-26 15:52
Sorry, somehow missed this. Tested again and seems that sometimes it works, sometimes it doesn't. It works When reloading the extension, but then it stops working. Will try to fix asap

**Comment by mneunomne** [comment] 2022-11-27 03:12
It seems that the issues occurs after this error popups up.

![Screenshot 2022-11-27 at 04 11 11](https://user-images.githubusercontent.com/4967860/204117518-c1b470af-1860-4902-ac4a-07165e23dbea.png)

**Comment by MultiTea** [comment] 2022-11-29 09:34
I can confirm too on Windows 10 64-bit with Opera 93.0.4585.21 (Chromium :107.0.5304.110)

**Comment by mneunomne** [comment] 2022-11-29 15:02
Still trying to figure out the reason why this is happening. What I understood so far:

- It initially works then after navegating for some time it stops working.
- the issue seems to be that Adnauseam fails to inject the epicker.js scriplet, but no error appears. While debuging I can't tell any difference in the code flow. it executes the webext function `webext.tabs.executeScript`, but doesn't inject for some reason.
- when it stops working, it stops working on all new tabs that are opened, but some tabs that were open before still can work. So it is either an issue with the tabId, or some kind of error in the contentscript side.
- It is not an issue with scriptlet injection in general, it seems that other scriptlets are being injected.

Next step is to rollback and figure out what caused this issue to appear. Problem is that the last merge had quite a few changes in the filtering mechanism so it will take some work to understand what is the underlying issue.

**Comment by mneunomne** [comment] 2022-11-30 16:26
https://github.com/dhowe/AdNauseam/pull/2220 Seems to fix it. I fast-forwarded some of the scriptlets for the epicker, since it seems there were some style issues in the ublock version we are currently on.

But weirdly it seems that this simple exception https://github.com/dhowe/AdNauseam/issues/2195 check was causing this error, I can't see why, but either way, seems to be working now. Need to do some more testing.

**Comment by mneunomne** [comment] 2022-12-01 12:33
Made a pre-release with this bug fix, will test more and update on the stores as soon as I can. https://github.com/dhowe/AdNauseam/releases/tag/v3.15.2b0

**Comment by mneunomne** [comment] 2023-02-17 14:41
This is currently fixed on latest release, closing

**Closed by mneunomne** 2023-02-17 14:41 UTC
Labels: PRIORITY: High
