### ISSUE TITLE
Error when trying to install extension in Chrome

### ISSUE THREAD

**Issue by robmoore** [dhowe/AdNauseam#193] opened 2016-05-29 15:31 UTC
I followed the instructions listed [here](https://github.com/dhowe/AdNauseam/wiki/Help-test-AdNauseam-for-Chrome) and received the following error. I had the same result on both a Chromebook and a Linux laptop.

> Failed to load extension from: /home/rob/Downloads/adnauseam.chromium.Manifest file is missing or unreadable.

**Comment by CyrusSUEN** [comment] 2016-05-29 18:21
Could you show me the content of your ``adnauseam.chromium`` folder?

Do you mind trying AdNauseam on Firefox on your Linux? For that you can follow the instruction here: https://github.com/dhowe/AdNauseam/wiki/Installing-AdNauseam

**Comment by robmoore** [comment] 2016-05-29 19:07
I installed the Firefox version and it seems to work just fine.

Here are the contents of the unzipped file on my machine:

```.
./META-INF
./META-INF/MANIFEST.MF
./adnauseam.chromium
./adnauseam.chromium/assets
./adnauseam.chromium/assets/thirdparties
./adnauseam.chromium/assets/thirdparties/publicsuffix.org
./adnauseam.chromium/assets/thirdparties/publicsuffix.org/list
./adnauseam.chromium/assets/thirdparties/publicsuffix.org/list/effective_tld_names.dat
./adnauseam.chromium/assets/thirdparties/www.malwaredomainlist.com
./adnauseam.chromium/assets/thirdparties/www.malwaredomainlist.com/hostslist
./adnauseam.chromium/assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt
./adnauseam.chromium/assets/thirdparties/www.malwaredomainlist.com/hostslist/README.md
./adnauseam.chromium/assets/thirdparties/pgl.yoyo.org
./adnauseam.chromium/assets/thirdparties/pgl.yoyo.org/as
./adnauseam.chromium/assets/thirdparties/pgl.yoyo.org/as/README.md
./adnauseam.chromium/assets/thirdparties/pgl.yoyo.org/as/serverlist
./adnauseam.chromium/assets/thirdparties/mirror1.malwaredomains.com
./adnauseam.chromium/assets/thirdparties/mirror1.malwaredomains.com/files
./adnauseam.chromium/assets/thirdparties/mirror1.malwaredomains.com/files/justdomains
./adnauseam.chromium/assets/thirdparties/mirror1.malwaredomains.com/files/README.md
./adnauseam.chromium/assets/thirdparties/easylist-downloads.adblockplus.org
./adnauseam.chromium/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt
./adnauseam.chromium/assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
./adnauseam.chromium/assets/checksums.txt
./adnauseam.chromium/assets/ublock
./adnauseam.chromium/assets/ublock/filters.txt
./adnauseam.chromium/assets/ublock/filter-lists.json
./adnauseam.chromium/assets/ublock/experimental.txt
./adnauseam.chromium/assets/ublock/resources.txt
./adnauseam.chromium/assets/ublock/unbreak.txt
./adnauseam.chromium/assets/ublock/badware.txt
./adnauseam.chromium/assets/ublock/adnauseam.txt
./adnauseam.chromium/assets/ublock/privacy.txt
./adnauseam.chromium/asset-viewer.html
./adnauseam.chromium/about.html
./adnauseam.chromium/options.html
./adnauseam.chromium/manifest.json
./adnauseam.chromium/LICENSE.txt
./adnauseam.chromium/dyna-rules.html
./adnauseam.chromium/vault.html
./adnauseam.chromium/settings.html
./adnauseam.chromium/menu.html
./adnauseam.chromium/document-blocked.html
./adnauseam.chromium/img
./adnauseam.chromium/img/paused.png
./adnauseam.chromium/img/paused@2x.png
./adnauseam.chromium/img/log.png
./adnauseam.chromium/img/icon-32.png
./adnauseam.chromium/img/black.png
./adnauseam.chromium/img/browsericons
./adnauseam.chromium/img/browsericons/icon38-off.png
./adnauseam.chromium/img/browsericons/icon19-off.png
./adnauseam.chromium/img/browsericons/icon38.png
./adnauseam.chromium/img/browsericons/icon19.png
./adnauseam.chromium/img/help16.png
./adnauseam.chromium/img/alert.png
./adnauseam.chromium/img/active@2x.png
./adnauseam.chromium/img/disabled.png
./adnauseam.chromium/img/preloader.gif
./adnauseam.chromium/img/gray_grid.png
./adnauseam.chromium/img/log@2x.png
./adnauseam.chromium/img/active.png
./adnauseam.chromium/img/firstrun.png
./adnauseam.chromium/img/icon_16.png
./adnauseam.chromium/img/icon_128.png
./adnauseam.chromium/img/cloud.png
./adnauseam.chromium/unit-tests.html
./adnauseam.chromium/_locales
./adnauseam.chromium/_locales/zh_TW
./adnauseam.chromium/_locales/zh_TW/messages.json
./adnauseam.chromium/_locales/en
./adnauseam.chromium/_locales/en/messages.json
./adnauseam.chromium/_locales/zh_CN
./adnauseam.chromium/_locales/zh_CN/messages.json
./adnauseam.chromium/lib
./adnauseam.chromium/lib/publicsuffixlist.js
./adnauseam.chromium/lib/yamd5.js
./adnauseam.chromium/lib/packery.min.js
./adnauseam.chromium/lib/imagesloaded.min.js
./adnauseam.chromium/lib/punycode.js
./adnauseam.chromium/lib/jquery.js
./adnauseam.chromium/lib/jquery.mousewheel.min.js
./adnauseam.chromium/lib/d3.min.js
./adnauseam.chromium/css
./adnauseam.chromium/css/settings.css
./adnauseam.chromium/css/dashboard.css
./adnauseam.chromium/css/3p-filters.css
./adnauseam.chromium/css/menu.css
./adnauseam.chromium/css/logger-ui-inspector.css
./adnauseam.chromium/css/common.css
./adnauseam.chromium/css/1p-filters.css
./adnauseam.chromium/css/whitelist.css
./adnauseam.chromium/css/dyna-rules.css
./adnauseam.chromium/css/logger-ui.css
./adnauseam.chromium/css/fonts
./adnauseam.chromium/css/fonts/bebasneue_regular-webfont.svg
./adnauseam.chromium/css/fonts/bebasneue_regular-webfont.eot
./adnauseam.chromium/css/fonts/fontawesome-webfont.ttf
./adnauseam.chromium/css/fonts/OFL.txt
./adnauseam.chromium/css/fonts/bebasneue_regular-webfont.ttf
./adnauseam.chromium/css/fonts/stylesheet.css
./adnauseam.chromium/css/fonts/bebasneue_regular-webfont.woff
./adnauseam.chromium/css/fonts/bebasneue_regular-webfont.woff2
./adnauseam.chromium/css/log.css
./adnauseam.chromium/css/about.css
./adnauseam.chromium/css/vault.css
./adnauseam.chromium/css/cloud-ui.css
./adnauseam.chromium/css/popup.css
./adnauseam.chromium/css/dashboard-common.css
./adnauseam.chromium/whitelist.html
./adnauseam.chromium/dashboard.html
./adnauseam.chromium/js
./adnauseam.chromium/js/background.js
./adnauseam.chromium/js/pagestore.js
./adnauseam.chromium/js/utils.js
./adnauseam.chromium/js/reverselookup.js
./adnauseam.chromium/js/start.js
./adnauseam.chromium/js/i18n.js
./adnauseam.chromium/js/options_ui.js
./adnauseam.chromium/js/profiler.js
./adnauseam.chromium/js/hnswitches.js
./adnauseam.chromium/js/contentscript-end.js
./adnauseam.chromium/js/dashboard-common.js
./adnauseam.chromium/js/rpcreceiver.js
./adnauseam.chromium/js/1p-filters.js
./adnauseam.chromium/js/dynamic-net-filtering.js
./adnauseam.chromium/js/storage.js
./adnauseam.chromium/js/asset-viewer.js
./adnauseam.chromium/js/dyna-rules.js
./adnauseam.chromium/js/vapi-common.js
./adnauseam.chromium/js/is-webrtc-supported.js
./adnauseam.chromium/js/about.js
./adnauseam.chromium/js/vapi-polyfill.js
./adnauseam.chromium/js/vapi-background.js
./adnauseam.chromium/js/dashboard.js
./adnauseam.chromium/js/logger.js
./adnauseam.chromium/js/url-net-filtering.js
./adnauseam.chromium/js/reverselookup-worker.js
./adnauseam.chromium/js/redirect-engine.js
./adnauseam.chromium/js/settings.js
./adnauseam.chromium/js/document-blocked.js
./adnauseam.chromium/js/static-net-filtering.js
./adnauseam.chromium/js/vapi-client.js
./adnauseam.chromium/js/contextmenu.js
./adnauseam.chromium/js/adn
./adnauseam.chromium/js/adn/menu.js
./adnauseam.chromium/js/adn/vault.js
./adnauseam.chromium/js/adn/tests.js
./adnauseam.chromium/js/adn/extract.js
./adnauseam.chromium/js/adn/options.js
./adnauseam.chromium/js/adn/core.js
./adnauseam.chromium/js/adn/shared.js
./adnauseam.chromium/js/traffic.js
./adnauseam.chromium/js/popup.js
./adnauseam.chromium/js/uritools.js
./adnauseam.chromium/js/ublock.js
./adnauseam.chromium/js/logger-ui.js
./adnauseam.chromium/js/whitelist.js
./adnauseam.chromium/js/logger-ui-inspector.js
./adnauseam.chromium/js/assets.js
./adnauseam.chromium/js/scriptlets
./adnauseam.chromium/js/scriptlets/load-large-media-interactive.js
./adnauseam.chromium/js/scriptlets/cosmetic-off.js
./adnauseam.chromium/js/scriptlets/element-picker.js
./adnauseam.chromium/js/scriptlets/cosmetic-survey.js
./adnauseam.chromium/js/scriptlets/load-large-media-all.js
./adnauseam.chromium/js/scriptlets/cosmetic-on.js
./adnauseam.chromium/js/scriptlets/dom-inspector.js
./adnauseam.chromium/js/scriptlets/subscriber.js
./adnauseam.chromium/js/scriptlets/cosmetic-logger.js
./adnauseam.chromium/js/contentscript-start.js
./adnauseam.chromium/js/tab.js
./adnauseam.chromium/js/udom.js
./adnauseam.chromium/js/messaging.js
./adnauseam.chromium/js/3p-filters.js
./adnauseam.chromium/js/cosmetic-filtering.js
./adnauseam.chromium/js/cloud-ui.js
./adnauseam.chromium/popup.html
./adnauseam.chromium/1p-filters.html
./adnauseam.chromium/3p-filters.html
./adnauseam.chromium/logger-ui.html
./adnauseam.chromium/links.html
./adnauseam.chromium/managed_storage.json
./adnauseam.chromium/background.html
./adnauseam.chromium/epicker.html
./adnauseam.chromium/options_ui.html
./adnauseam.chromium/is-webrtc-supported.html
```

**Comment by dhowe** [comment] 2016-05-30 05:51
Works as expected for me on debian:

![screen shot 2016-05-30 at 1 50 25 pm](https://cloud.githubusercontent.com/assets/737638/15640728/9c243cdc-266d-11e6-9b05-c540f44de87c.png)

**Comment by CyrusSUEN** [comment] 2016-05-30 07:00
![capture](https://cloud.githubusercontent.com/assets/2461812/15641972/e04864de-2676-11e6-8d4d-64bad7a06406.PNG)

I have no problem installing it on Ubuntu 16.04.

Did you drag both META-INF and adnauseam.chromium folder to ``chrome://extensions`` page?

**Comment by dhowe** [comment] 2016-05-30 08:05
To be clear, you should NOT drag META-INF (future zips won't have this)...
Closing

**Closed by dhowe** 2016-05-30 08:05 UTC
Labels: Chrome, Needs-verification, Question

**Comment by robmoore** [comment] 2016-05-30 15:22
Indeed, that fixed the issue for me. Might want to update directions page to reflect this. It may be obvious to you but I'd assumed the META-INF was required.

**Comment by mushon** [comment] 2016-06-01 11:45
@dhowe:
> To be clear, you should NOT drag META-INF (future zips won't have this)...

The version that was uploaded on May 27th and is referred to from the Chrome beta testing page does still include the META-INF folder. Since the unzipped folder that contains the two folder has the same name as the internal one that should be dragged into Chrome, this will undoubtedly lead to more users unable to install the dev script:
 
![image](https://cloud.githubusercontent.com/assets/27123/15708403/12981d4e-2807-11e6-9be5-919d5d02eabb.png)

If you can confirm let's open another issue for making sure the unzipped folder is the only one that needs to be installed with no caveats.

**Comment by dhowe** [comment] 2016-06-01 11:48
I updated the instructions to be clear about this, however, if you want to update the current zip as well, I am not against it of course (just download, unzip, remove the META-INF, re-zip, and replace)

**Comment by mushon** [comment] 2016-06-01 13:25
what's that META-INF thing anyway? Is there a reason why we want it there?

**Comment by dhowe** [comment] 2016-06-01 13:27
Nope, its junk

**Comment by mushon** [comment] 2016-06-01 13:33
done.

**Comment by dhowe** [comment] 2016-06-01 16:54
confirmed
