### ISSUE TITLE
Web-ext errors on open settings

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1073] opened 2017-06-14 11:32 UTC
Load adn, then click setting:

```
- TypeError: details.storageUsed is undefined moz-extension://e6c039bd-acf5-0d44-9bbf-28ddc774e07b/js/adn/options.js 37`

- Unknown localization message toggle adnauseam on/off 1 i18n.js:152

- reqPageStore is undefined 1 core.js:1986
	exports.adsForPage moz-extension://ebfe00da-ad2f-464b-b8e3-7a4e81168089/js/adn/core.js:1986:9

- No pageStore Object { what: "adsForPage", tabId: 1 } undefined undefined 1 core.js:839:7

- Invalid match pattern: 'moz-extension://130b65b5-2f93-3c4e-acf9-5e74607288a4/dashboard.html' 1 MatchPattern.jsm:53

```

**Comment by dhowe** [comment] 2017-06-15 04:36
To see these errors more clearly, open the console (cmd-shift-j) as soon as firefox opens.
When loading stuff finishes, clear the console, then go to settings in the adnauseam menu.

**Comment by dhowe** [comment] 2017-06-15 04:42
remember only to fix stuff in our code for web-ext, as the other issues will likely be fixed in ublock itself  (but leave a comment to this effect in the relevant place)

**Comment by cqx931** [comment] 2017-06-15 05:03
> Unknown localization message toggle adnauseam on/off 1 i18n.js:152

It seems like that i18n.js will go through all title attribute in the page and try to replace them with an entry in the locale file.
In menu.html, we have the following html code and there is no corresponding locale entry that matches with "Toggle AdNauseam On/Off".
```
          <a href="http://adnauseam.io" target="new">
            <span id="toggle-button" background="" title="Toggle AdNauseam On/Off">ADNAUSEAM</span>
          </a>
```

In this case the title message is no more accurate as the icon currently links to the homepage... 
So I suggest:
1.replace the title with "goToAdNauseamWebsite"
2.Add a corresponding entry in the locale file -> "Go to AdNauseam website"

**Comment by cqx931** [comment] 2017-06-15 05:28
For more general cases, there are many title attributes in AdNauseam and most of them doesn't have a 
According to the [documentation from mozilla](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/getMessage) If the message can't be found in messages.json:
Firefox returns ""??" and logs an error
Chrome returns "" and does not log an error.

I added a substitutions parameter to the code for title tag, so it won't return any error if no message can be found in messages.json
`text = vAPI.i18n(elem.getAttribute('title',''));`

**Comment by cqx931** [comment] 2017-06-15 05:32
I can't reproduce this error :
- No pageStore Object { what: "adsForPage", tabId: 1 } undefined undefined 1 core.js:839:7

Please check here for the rest:
https://github.com/dhowe/AdNauseam/pull/1074

**Comment by cqx931** [comment] 2017-06-20 01:21
Can you still see this error message ?

> No pageStore Object { what: "adsForPage", tabId: 1 } undefined undefined 1 core.js:839:7

**Comment by dhowe** [comment] 2017-06-20 15:56
I haven't seen that one, but I still get this one:

```
23:53:58.502 reqPageStore is undefined 1 core.js:1984
	exports.adsForPage moz-extension://19c5f729-981e-044d-8179-fd5e6bc8e007/js/adn/core.js:1984:9
	<anonymous> moz-extension://19c5f729-981e-044d-8179-fd5e6bc8e007/js/adn/core.js:2020:16
	vAPI.messaging.onPortMessage moz-extension://19c5f729-981e-044d-8179-fd5e6bc8e007/js/vapi-background.js:801:17
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:133:38
	addListener/asyncWithoutClone/< resource://gre/modules/ExtensionUtils.jsm:655:63

```
![image](https://user-images.githubusercontent.com/737638/27342935-1901d080-5614-11e7-854f-278a6f14c03d.png)

**Comment by dhowe** [comment] 2017-06-20 15:57
And this one:

23:53:58.310 Unknown localization message toggle adnauseam on/off 1 i18n.js:152
	localizeMessage resource://gre/modules/ExtensionUtils.jsm:495:17
	localizeMessage resource://gre/modules/ExtensionContent.jsm:845:44
	getMessage chrome://extensions/content/ext-i18n.js:15:16
	callFunction resource://gre/modules/ExtensionCommon.jsm:490:36
	stub resource://gre/modules/Schemas.jsm:1790:16
	vAPI.i18n.render moz-extension://19c5f729-981e-044d-8179-fd5e6bc8e007/js/i18n.js:152:16
	<anonymous> moz-extension://19c5f729-981e-044d-8179-fd5e6bc8e007/js/i18n.js:176:1
	<anonymous> moz-extension://19c5f729-981e-044d-8179-fd5e6bc8e007/js/i18n.js:29:2

**Comment by greysonevins** [comment] 2017-06-20 16:22
I can't replicate this issue either.

**Comment by dhowe** [comment] 2017-06-20 16:35
Which one (please be specific)?

**Comment by greysonevins** [comment] 2017-06-20 17:08
```
- Unknown localization message toggle adnauseam on/off  i18n.js:152
-ReferenceError: reference to undefined property "background"[Learn More]  ext-utils.js:479:7
-Invalid match pattern: 'moz-extension://a297d542-d1ba-4647-9d57-9d3e09758666/dashboard.html'  MatchPattern.jsm:52
-ReferenceError: reference to undefined property "getBytesInUse"[Learn More]  storage.js:37:1
-details.storageUsed is undefined  options.js:37
1497977485596	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
-1497977485597	Toolkit.GMP	ERROR	GMPInstallManager.simpleCheckAndInstall Could not check for addons: {"status":"failed","results":[{"id":"gmp-gmpopenh264","result":"failed"}]}  Log.jsm:748
-ReferenceError: reference to undefined property "guid"[Learn More]
```

These are the errors I am getting

**Comment by dhowe** [comment] 2017-06-20 17:25
Please remove the warnings first (unclick 'javascript->warnings' in the console)

**Comment by cqx931** [comment] 2017-06-21 03:51
The fixes were done in firstrun branch....Sorry for the confusion, merged into master now.
https://github.com/dhowe/AdNauseam/pull/1083

**Comment by cqx931** [comment] 2017-06-21 04:14
Also, `text = vAPI.i18n(elem.getAttribute('title',''));` doesn't seem to solve the error message from Firefox...
So to completely remove this error message from firefox, we need to:
Translate every title attribute that in AdNauseam.

**Comment by dhowe** [comment] 2017-06-21 04:17
How many of these are there? And can you give an example?

**Comment by cqx931** [comment] 2017-06-21 04:59
**Menu**
AdNauseam Icon: 
Currently the title message is"Toggle AdNauseam On/Off"
(Better change to "Go to AdNauseam website", because the icon links to the website)

**3p filters**
`Unknown localization message http`
'http' is the title for this 'unsecure' icon, this title is already there in uBlock, but I don't see any error message caused by this in uBlock.
![image](https://user-images.githubusercontent.com/3056154/27367375-261ff2d6-567f-11e7-9811-72dde3a5c6f2.png)

**Comment by dhowe** [comment] 2017-06-21 05:34
how many?

**Comment by cqx931** [comment] 2017-06-21 05:40
AdNauseam only added one new title attribute, which is the one in the menu.

**Comment by cqx931** [comment] 2017-06-21 10:20
Fixed i18n error messages except this one: `Unknown localization message http` (3p filters page)
https://github.com/dhowe/AdNauseam/pull/1085

**Closed** 2017-08-31 16:14 UTC
Labels: WebExt
