### ISSUE TITLE
Should hide sponsored ads on instagram

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2254] opened 2023-01-19 23:18 UTC
<img width="613" alt="image" src="https://user-images.githubusercontent.com/737638/213583632-266a9a89-704f-4658-a67e-e02135cf0a68.png">

**Comment by mneunomne** [comment] 2023-01-27 15:31
I was not able to reproduce on my end, tried different VPN and didn't appear. (it actually collected some).

It's interesting because instagram ads are user-generated, so even if i use VPN it still knows I live in Germany. But i'm not sure if the ad scripts are different depending on the *assumed location* of a user.

I will keep an eye on it. If you want to try to figure it out you would need to try to check what is the adn-allowed script generating the ad. And maybe it is indeed a location-specific script that is getting adn-allowed.

**Comment by Patricek0056** [comment] 2023-02-13 18:04
Also, sponsored ads on Facebook are still visible, even with AdNauseam enabled.

**Comment by dhowe** [comment] 2023-02-15 03:22
> Also, sponsored ads on Facebook are still visible, even with AdNauseam enabled.

@mneunomne pls test this...

**Comment by mneunomne** [comment] 2023-02-15 12:26
This is not Adn specific, ads are also showing in uBlock Origin:

<img width="1427" alt="Screenshot 2023-02-15 at 13 19 28" src="https://user-images.githubusercontent.com/4967860/219025816-90b0bfa7-1752-4a2b-ab77-9f3660170413.png">

We have discussed this before https://github.com/dhowe/AdNauseam/issues/1894, seems that facebook manages to be ahead of uBlock most of the time in terms of ad blocking.

The reason for that I believe is that the HTML structure is completely compiled, and even the word "advertised" doesn't render as usual plain-text in html, but as svg, probably to avoid procedural filters such as `:has-text(Ads)`.

Check here for the ongoing discussion https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by mneunomne** [comment] 2023-02-15 12:37
regarding instagram, I was able to now reproduce it as well. Not sure why this is happening, even with strict mode it is appearing. Will check further.

**Comment by mneunomne** [comment] 2023-02-17 12:44
The issue is that now Adnauseam is a bit far behind uBlock in terms of the its filter assets. This can be fixed by simply clicking "Update" in the third-party filters list tab.

@dhowe maybe to avoid this we should consider an force-auto-update on launch?

https://github.com/dhowe/AdNauseam/blob/f33d620612d713f6c7f794c31de420a276666f52/src/js/messaging.js#L178-L183

We will always be a bit behind uBlock, so for me this makes sense.

**Comment by mneunomne** [comment] 2023-02-17 13:58
Actually a better way this can also be fixed is by decreasing the delay times of the `autoUpdate` function:

(values are in seconds)

### from:
```
autoUpdateAssetFetchPeriod: 60
autoUpdateDelayAfterLaunch: 105
``` 
### to:
```
autoUpdateAssetFetchPeriod: 10
autoUpdateDelayAfterLaunch: 5
``` 

What is important is to decrease the delay after launch significantly so that we ensure Adnauseam has all the filters as the user starts using it. We need it quicker than uBlock since our local assets tend to be out of date with uBlock's.

**Comment by mneunomne** [comment] 2023-02-21 00:57
This should be fixed by simply updating filter. Last merge enforces updates faster, and also updated the submodules. Should be closed if cannot be reproduced after updating filters.

**Comment by mneunomne** [comment] 2023-02-26 16:24
Fixed, closing

**Closed by mneunomne** 2023-02-26 16:24 UTC
Labels: PRIORITY: High, Ads Visible
