### ISSUE TITLE
[3.12] Ads not collected on nytimes.com

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1891] opened 2021-07-05 21:31 UTC
The nytimes (nytimes.com) homepage has many ads, yet none are collected by AdNauseam.  (accessed from US and HK)

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/737638/145803872-8b626674-deea-4fc3-8b13-6f642f540109.png">

<img width="1010" alt="Screenshot 2021-12-13 at 7 26 18 PM" src="https://user-images.githubusercontent.com/737638/145804262-6ea5d5d5-fb07-4e53-953d-f553a0e968aa.png">

<img width="759" alt="Screenshot 2021-12-13 at 7 24 02 PM" src="https://user-images.githubusercontent.com/737638/145803997-6fd813a2-07ad-4c70-b232-31d4536c183d.png">

**Comment by mneunomne** [comment] 2021-07-06 17:01
These ads don't appear in my location (Germany). If they are not collected it is probably due to a cosmetic filter too high up the dom or the content is being blocked and needs to make an exception for it

**Comment by dhowe** [comment] 2021-07-06 21:40
Please check NYT from Germany with ADN disabled, and make note of all the ads that appear, as you scroll down. Then compare to the number of ads that are collected....

**Comment by mneunomne** [comment] 2021-07-07 22:28
I had to create an accont for these to show, and even then only "internal ads" showed up:

![nyt](https://user-images.githubusercontent.com/4967860/124836497-55e96100-df83-11eb-867d-660263958546.PNG)
![nyt2](https://user-images.githubusercontent.com/4967860/124836500-5681f780-df83-11eb-9160-c801c72b7118.PNG)

**Comment by dhowe** [comment] 2021-07-07 22:29
Do you have access to a VPN ?

**Comment by dhowe** [comment] 2021-07-16 03:09
A concrete example: for this page: https://www.nytimes.com/2021/07/13/opinion/data-privacy-rights.html, I am shown the ad below with ADN disabled, but see zero ads collected with ADN enabled:

![Screenshot 2021-07-15 at 11 07 17 PM](https://user-images.githubusercontent.com/737638/125885724-29b3276d-cacf-4caa-8420-1b7ab6df0894.png)

**Comment by mneunomne** [comment] 2021-07-16 10:49
@dhowe it doesnt seem that this ad is an image, but a html constructure ad. This page shows some ads to me but all of the are either video ads, or "html ads"

**Comment by dhowe** [comment] 2021-09-12 07:56
If so then we need to create a text-ad filter for nytimes

**Comment by dhowe** [comment] 2021-09-12 08:01
More uncollected:

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/737638/132978811-9b7742cc-91f2-498c-ab3d-302e3ef5c93c.png">

**Comment by mneunomne** [comment] 2022-01-05 14:22
Now i finally installed VPN, and indeed on the US more collectable ads are not being collected, will check this soon. Takes some time since need to check what requests should be allowed to make them render with Adn on. Right now they are not rendering

**Comment by dhowe** [comment] 2022-07-26 17:28
@mneunomne can you verify and close this if done ?

**Comment by mneunomne** [comment] 2022-07-27 09:45
hey @dhowe I have been attempting for quite sometime to improve this. There is one issue though, it seems that the method I had developed for ads that had the GoogleActiveElement structure, are not being collected any longer.

Google makes it in a way that the ads is an iframe inside an iframe inside another iframe, and our content script is not being loaded onto all these layers. I have also tested uBlock and the same happens (but uBlock blocks the parent element, so for their case it doesn't matter if the iframe doesn't load on the layers bellow.

Coming back to nytimes, it seems the issue is not nytimes specific, but since most ads that appear there follow this structure, we can't collect many of them....

I'm not sure what to do next, I'll try to see if there are other ways for the content script to be loaded on all layers of iframe.

Documentation on previous GoogleActiveViewElement is here https://github.com/dhowe/AdNauseam/issues/1932

**Comment by mneunomne** [comment] 2022-07-27 09:47
(+ I have an issue for testing, I don't have nytimes subscription, so I can only check one same page during a certain period of time)

**Comment by mneunomne** [comment] 2022-08-16 17:22
As far as I can test, it seems that ads are in fact being collected in nytimes.com:

![Screenshot 2022-08-16 at 19 12 05](https://user-images.githubusercontent.com/4967860/184938831-298e9986-944b-4bab-afd7-b0d1895b9fc7.png)

There will always be non-collected ads for multiple reasons. The most important cases are the GoogleActiveElements ads, which I will create a new issue for it.

**Comment by dhowe** [comment] 2022-08-16 20:51
>  The most important cases are the GoogleActiveElements ads, which I will create a new issue for it.

this should be very high priority

**Comment by mneunomne** [comment] 2022-10-24 11:01
Expanding the underlying issue to https://github.com/dhowe/AdNauseam/issues/2196

**Comment by mneunomne** [comment] 2022-10-24 12:42
Closing this issue, migrating the discussion to [google_ads_iframe are not consistently collected](https://github.com/dhowe/AdNauseam/issues/2196) https://github.com/dhowe/AdNauseam/issues/2196

**Closed by mneunomne** 2022-10-24 12:43 UTC
Labels: PRIORITY: High, Ads Not Collected
